// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user/v1/user.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Profile struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AvatarUrl       string                 `protobuf:"bytes,2,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	NickName        string                 `protobuf:"bytes,3,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	Phone           string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	RealNameAuth    int32                  `protobuf:"varint,5,opt,name=real_name_auth,json=realNameAuth,proto3" json:"real_name_auth,omitempty"`
	AccountStatus   int32                  `protobuf:"varint,6,opt,name=account_status,json=accountStatus,proto3" json:"account_status,omitempty"`
	IsEnterprise    bool                   `protobuf:"varint,7,opt,name=is_enterprise,json=isEnterprise,proto3" json:"is_enterprise,omitempty"`
	QueryCountToday int32                  `protobuf:"varint,8,opt,name=query_count_today,json=queryCountToday,proto3" json:"query_count_today,omitempty"`
	CreateTime      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *Profile) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Profile) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Profile) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *Profile) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Profile) GetRealNameAuth() int32 {
	if x != nil {
		return x.RealNameAuth
	}
	return 0
}

func (x *Profile) GetAccountStatus() int32 {
	if x != nil {
		return x.AccountStatus
	}
	return 0
}

func (x *Profile) GetIsEnterprise() bool {
	if x != nil {
		return x.IsEnterprise
	}
	return false
}

func (x *Profile) GetQueryCountToday() int32 {
	if x != nil {
		return x.QueryCountToday
	}
	return 0
}

func (x *Profile) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Profile) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetProfileRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UpdateAvatarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,2,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAvatarRequest) Reset() {
	*x = UpdateAvatarRequest{}
	mi := &file_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAvatarRequest) ProtoMessage() {}

func (x *UpdateAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAvatarRequest.ProtoReflect.Descriptor instead.
func (*UpdateAvatarRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateAvatarRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateAvatarRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type UpdateNicknameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NickName      string                 `protobuf:"bytes,2,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNicknameRequest) Reset() {
	*x = UpdateNicknameRequest{}
	mi := &file_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNicknameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNicknameRequest) ProtoMessage() {}

func (x *UpdateNicknameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNicknameRequest.ProtoReflect.Descriptor instead.
func (*UpdateNicknameRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateNicknameRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateNicknameRequest) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

type AuthStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RealNameAuth  int32                  `protobuf:"varint,2,opt,name=real_name_auth,json=realNameAuth,proto3" json:"real_name_auth,omitempty"`
	RejectReason  string                 `protobuf:"bytes,3,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthStatus) Reset() {
	*x = AuthStatus{}
	mi := &file_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthStatus) ProtoMessage() {}

func (x *AuthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthStatus.ProtoReflect.Descriptor instead.
func (*AuthStatus) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *AuthStatus) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AuthStatus) GetRealNameAuth() int32 {
	if x != nil {
		return x.RealNameAuth
	}
	return 0
}

func (x *AuthStatus) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

type GetAuthStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthStatusRequest) Reset() {
	*x = GetAuthStatusRequest{}
	mi := &file_user_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthStatusRequest) ProtoMessage() {}

func (x *GetAuthStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAuthStatusRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetAuthStatusRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AccountStatusInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountStatus    int32                  `protobuf:"varint,2,opt,name=account_status,json=accountStatus,proto3" json:"account_status,omitempty"`
	RealNameAuth     int32                  `protobuf:"varint,3,opt,name=real_name_auth,json=realNameAuth,proto3" json:"real_name_auth,omitempty"`
	IsEnterprise     bool                   `protobuf:"varint,4,opt,name=is_enterprise,json=isEnterprise,proto3" json:"is_enterprise,omitempty"`
	CanModifyProfile bool                   `protobuf:"varint,5,opt,name=can_modify_profile,json=canModifyProfile,proto3" json:"can_modify_profile,omitempty"`
	CanManageAddress bool                   `protobuf:"varint,6,opt,name=can_manage_address,json=canManageAddress,proto3" json:"can_manage_address,omitempty"`
	CanQueryHistory  bool                   `protobuf:"varint,7,opt,name=can_query_history,json=canQueryHistory,proto3" json:"can_query_history,omitempty"`
	CanExport        bool                   `protobuf:"varint,8,opt,name=can_export,json=canExport,proto3" json:"can_export,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AccountStatusInfo) Reset() {
	*x = AccountStatusInfo{}
	mi := &file_user_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountStatusInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountStatusInfo) ProtoMessage() {}

func (x *AccountStatusInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountStatusInfo.ProtoReflect.Descriptor instead.
func (*AccountStatusInfo) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *AccountStatusInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AccountStatusInfo) GetAccountStatus() int32 {
	if x != nil {
		return x.AccountStatus
	}
	return 0
}

func (x *AccountStatusInfo) GetRealNameAuth() int32 {
	if x != nil {
		return x.RealNameAuth
	}
	return 0
}

func (x *AccountStatusInfo) GetIsEnterprise() bool {
	if x != nil {
		return x.IsEnterprise
	}
	return false
}

func (x *AccountStatusInfo) GetCanModifyProfile() bool {
	if x != nil {
		return x.CanModifyProfile
	}
	return false
}

func (x *AccountStatusInfo) GetCanManageAddress() bool {
	if x != nil {
		return x.CanManageAddress
	}
	return false
}

func (x *AccountStatusInfo) GetCanQueryHistory() bool {
	if x != nil {
		return x.CanQueryHistory
	}
	return false
}

func (x *AccountStatusInfo) GetCanExport() bool {
	if x != nil {
		return x.CanExport
	}
	return false
}

type GetAccountStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountStatusRequest) Reset() {
	*x = GetAccountStatusRequest{}
	mi := &file_user_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountStatusRequest) ProtoMessage() {}

func (x *GetAccountStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAccountStatusRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetAccountStatusRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_user_v1_user_proto protoreflect.FileDescriptor

const file_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x12user/v1/user.proto\x12\auser.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\x03\n" +
	"\aProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x02 \x01(\tR\tavatarUrl\x12\x1b\n" +
	"\tnick_name\x18\x03 \x01(\tR\bnickName\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12$\n" +
	"\x0ereal_name_auth\x18\x05 \x01(\x05R\frealNameAuth\x12%\n" +
	"\x0eaccount_status\x18\x06 \x01(\x05R\raccountStatus\x12#\n" +
	"\ris_enterprise\x18\a \x01(\bR\fisEnterprise\x12*\n" +
	"\x11query_count_today\x18\b \x01(\x05R\x0fqueryCountToday\x12;\n" +
	"\vcreate_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"1\n" +
	"\x11GetProfileRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x06userId\"W\n" +
	"\x13UpdateAvatarRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x06userId\x12\"\n" +
	"\n" +
	"avatar_url\x18\x02 \x01(\tB\x03\xe0A\x02R\tavatarUrl\"W\n" +
	"\x15UpdateNicknameRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x06userId\x12 \n" +
	"\tnick_name\x18\x02 \x01(\tB\x03\xe0A\x02R\bnickName\"p\n" +
	"\n" +
	"AuthStatus\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12$\n" +
	"\x0ereal_name_auth\x18\x02 \x01(\x05R\frealNameAuth\x12#\n" +
	"\rreject_reason\x18\x03 \x01(\tR\frejectReason\"4\n" +
	"\x14GetAuthStatusRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x06userId\"\xc5\x02\n" +
	"\x11AccountStatusInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12%\n" +
	"\x0eaccount_status\x18\x02 \x01(\x05R\raccountStatus\x12$\n" +
	"\x0ereal_name_auth\x18\x03 \x01(\x05R\frealNameAuth\x12#\n" +
	"\ris_enterprise\x18\x04 \x01(\bR\fisEnterprise\x12,\n" +
	"\x12can_modify_profile\x18\x05 \x01(\bR\x10canModifyProfile\x12,\n" +
	"\x12can_manage_address\x18\x06 \x01(\bR\x10canManageAddress\x12*\n" +
	"\x11can_query_history\x18\a \x01(\bR\x0fcanQueryHistory\x12\x1d\n" +
	"\n" +
	"can_export\x18\b \x01(\bR\tcanExport\"7\n" +
	"\x17GetAccountStatusRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x06userId2\x8c\x04\n" +
	"\vUserService\x12U\n" +
	"\n" +
	"GetProfile\x12\x1a.user.v1.GetProfileRequest\x1a\x10.user.v1.Profile\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/user/profile\x12c\n" +
	"\fUpdateAvatar\x12\x1c.user.v1.UpdateAvatarRequest\x1a\x10.user.v1.Profile\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\x1a\x18/api/user/profile/avatar\x12i\n" +
	"\x0eUpdateNickname\x12\x1e.user.v1.UpdateNicknameRequest\x1a\x10.user.v1.Profile\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\x1a\x1a/api/user/profile/nickname\x12b\n" +
	"\rGetAuthStatus\x12\x1d.user.v1.GetAuthStatusRequest\x1a\x13.user.v1.AuthStatus\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/user/auth/status\x12r\n" +
	"\x10GetAccountStatus\x12 .user.v1.GetAccountStatusRequest\x1a\x1a.user.v1.AccountStatusInfo\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/user/account/statusBL\n" +
	"\x18io.grpc.examples.user.v1B\tUserProtoP\x01Z#shunfeng-miniprogram/api/user/v1;v1b\x06proto3"

var (
	file_user_v1_user_proto_rawDescOnce sync.Once
	file_user_v1_user_proto_rawDescData []byte
)

func file_user_v1_user_proto_rawDescGZIP() []byte {
	file_user_v1_user_proto_rawDescOnce.Do(func() {
		file_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)))
	})
	return file_user_v1_user_proto_rawDescData
}

var file_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_user_v1_user_proto_goTypes = []any{
	(*Profile)(nil),                 // 0: user.v1.Profile
	(*GetProfileRequest)(nil),       // 1: user.v1.GetProfileRequest
	(*UpdateAvatarRequest)(nil),     // 2: user.v1.UpdateAvatarRequest
	(*UpdateNicknameRequest)(nil),   // 3: user.v1.UpdateNicknameRequest
	(*AuthStatus)(nil),              // 4: user.v1.AuthStatus
	(*GetAuthStatusRequest)(nil),    // 5: user.v1.GetAuthStatusRequest
	(*AccountStatusInfo)(nil),       // 6: user.v1.AccountStatusInfo
	(*GetAccountStatusRequest)(nil), // 7: user.v1.GetAccountStatusRequest
	(*timestamppb.Timestamp)(nil),   // 8: google.protobuf.Timestamp
}
var file_user_v1_user_proto_depIdxs = []int32{
	8, // 0: user.v1.Profile.create_time:type_name -> google.protobuf.Timestamp
	8, // 1: user.v1.Profile.update_time:type_name -> google.protobuf.Timestamp
	1, // 2: user.v1.UserService.GetProfile:input_type -> user.v1.GetProfileRequest
	2, // 3: user.v1.UserService.UpdateAvatar:input_type -> user.v1.UpdateAvatarRequest
	3, // 4: user.v1.UserService.UpdateNickname:input_type -> user.v1.UpdateNicknameRequest
	5, // 5: user.v1.UserService.GetAuthStatus:input_type -> user.v1.GetAuthStatusRequest
	7, // 6: user.v1.UserService.GetAccountStatus:input_type -> user.v1.GetAccountStatusRequest
	0, // 7: user.v1.UserService.GetProfile:output_type -> user.v1.Profile
	0, // 8: user.v1.UserService.UpdateAvatar:output_type -> user.v1.Profile
	0, // 9: user.v1.UserService.UpdateNickname:output_type -> user.v1.Profile
	4, // 10: user.v1.UserService.GetAuthStatus:output_type -> user.v1.AuthStatus
	6, // 11: user.v1.UserService.GetAccountStatus:output_type -> user.v1.AccountStatusInfo
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_user_v1_user_proto_init() }
func file_user_v1_user_proto_init() {
	if File_user_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_user_proto_goTypes,
		DependencyIndexes: file_user_v1_user_proto_depIdxs,
		MessageInfos:      file_user_v1_user_proto_msgTypes,
	}.Build()
	File_user_v1_user_proto = out.File
	file_user_v1_user_proto_goTypes = nil
	file_user_v1_user_proto_depIdxs = nil
}
