// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: user/v1/user.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationUserServiceGetAccountStatus = "/user.v1.UserService/GetAccountStatus"
const OperationUserServiceGetAuthStatus = "/user.v1.UserService/GetAuthStatus"
const OperationUserServiceGetProfile = "/user.v1.UserService/GetProfile"
const OperationUserServiceUpdateAvatar = "/user.v1.UserService/UpdateAvatar"
const OperationUserServiceUpdateNickname = "/user.v1.UserService/UpdateNickname"

type UserServiceHTTPServer interface {
	GetAccountStatus(context.Context, *GetAccountStatusRequest) (*AccountStatusInfo, error)
	GetAuthStatus(context.Context, *GetAuthStatusRequest) (*AuthStatus, error)
	GetProfile(context.Context, *GetProfileRequest) (*Profile, error)
	UpdateAvatar(context.Context, *UpdateAvatarRequest) (*Profile, error)
	UpdateNickname(context.Context, *UpdateNicknameRequest) (*Profile, error)
}

func RegisterUserServiceHTTPServer(s *http.Server, srv UserServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/api/user/profile", _UserService_GetProfile0_HTTP_Handler(srv))
	r.Handle("PUT", "/api/user/profile/avatar", _UserService_UpdateAvatar0_HTTP_Handler(srv))
	r.Handle("PUT", "/api/user/profile/nickname", _UserService_UpdateNickname0_HTTP_Handler(srv))
	r.Handle("GET", "/api/user/auth/status", _UserService_GetAuthStatus0_HTTP_Handler(srv))
	r.Handle("GET", "/api/user/account/status", _UserService_GetAccountStatus0_HTTP_Handler(srv))
}

func _UserService_GetProfile0_HTTP_Handler(srv UserServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProfileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserServiceGetProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProfile(ctx, req.(*GetProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Profile)
		return ctx.Result(200, reply)
	}
}

func _UserService_UpdateAvatar0_HTTP_Handler(srv UserServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateAvatarRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserServiceUpdateAvatar)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateAvatar(ctx, req.(*UpdateAvatarRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Profile)
		return ctx.Result(200, reply)
	}
}

func _UserService_UpdateNickname0_HTTP_Handler(srv UserServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateNicknameRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserServiceUpdateNickname)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateNickname(ctx, req.(*UpdateNicknameRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Profile)
		return ctx.Result(200, reply)
	}
}

func _UserService_GetAuthStatus0_HTTP_Handler(srv UserServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAuthStatusRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserServiceGetAuthStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAuthStatus(ctx, req.(*GetAuthStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AuthStatus)
		return ctx.Result(200, reply)
	}
}

func _UserService_GetAccountStatus0_HTTP_Handler(srv UserServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAccountStatusRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserServiceGetAccountStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAccountStatus(ctx, req.(*GetAccountStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AccountStatusInfo)
		return ctx.Result(200, reply)
	}
}

type UserServiceHTTPClient interface {
	GetAccountStatus(ctx context.Context, req *GetAccountStatusRequest, opts ...http.CallOption) (rsp *AccountStatusInfo, err error)
	GetAuthStatus(ctx context.Context, req *GetAuthStatusRequest, opts ...http.CallOption) (rsp *AuthStatus, err error)
	GetProfile(ctx context.Context, req *GetProfileRequest, opts ...http.CallOption) (rsp *Profile, err error)
	UpdateAvatar(ctx context.Context, req *UpdateAvatarRequest, opts ...http.CallOption) (rsp *Profile, err error)
	UpdateNickname(ctx context.Context, req *UpdateNicknameRequest, opts ...http.CallOption) (rsp *Profile, err error)
}

type UserServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewUserServiceHTTPClient(client *http.Client) UserServiceHTTPClient {
	return &UserServiceHTTPClientImpl{client}
}

func (c *UserServiceHTTPClientImpl) GetAccountStatus(ctx context.Context, in *GetAccountStatusRequest, opts ...http.CallOption) (*AccountStatusInfo, error) {
	var out AccountStatusInfo
	pattern := "/api/user/account/status"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationUserServiceGetAccountStatus),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *UserServiceHTTPClientImpl) GetAuthStatus(ctx context.Context, in *GetAuthStatusRequest, opts ...http.CallOption) (*AuthStatus, error) {
	var out AuthStatus
	pattern := "/api/user/auth/status"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationUserServiceGetAuthStatus),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *UserServiceHTTPClientImpl) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...http.CallOption) (*Profile, error) {
	var out Profile
	pattern := "/api/user/profile"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationUserServiceGetProfile),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *UserServiceHTTPClientImpl) UpdateAvatar(ctx context.Context, in *UpdateAvatarRequest, opts ...http.CallOption) (*Profile, error) {
	var out Profile
	pattern := "/api/user/profile/avatar"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationUserServiceUpdateAvatar),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *UserServiceHTTPClientImpl) UpdateNickname(ctx context.Context, in *UpdateNicknameRequest, opts ...http.CallOption) (*Profile, error) {
	var out Profile
	pattern := "/api/user/profile/nickname"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationUserServiceUpdateNickname),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
