// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: address/v1/address.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddressType int32

const (
	AddressType_ADDRESS_TYPE_UNSPECIFIED   AddressType = 0
	AddressType_ADDRESS_TYPE_MAINLAND      AddressType = 1
	AddressType_ADDRESS_TYPE_HK_MO_TW      AddressType = 2
	AddressType_ADDRESS_TYPE_INTERNATIONAL AddressType = 3
)

// Enum value maps for AddressType.
var (
	AddressType_name = map[int32]string{
		0: "ADDRESS_TYPE_UNSPECIFIED",
		1: "ADDRESS_TYPE_MAINLAND",
		2: "ADDRESS_TYPE_HK_MO_TW",
		3: "ADDRESS_TYPE_INTERNATIONAL",
	}
	AddressType_value = map[string]int32{
		"ADDRESS_TYPE_UNSPECIFIED":   0,
		"ADDRESS_TYPE_MAINLAND":      1,
		"ADDRESS_TYPE_HK_MO_TW":      2,
		"ADDRESS_TYPE_INTERNATIONAL": 3,
	}
)

func (x AddressType) Enum() *AddressType {
	p := new(AddressType)
	*p = x
	return p
}

func (x AddressType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddressType) Descriptor() protoreflect.EnumDescriptor {
	return file_address_v1_address_proto_enumTypes[0].Descriptor()
}

func (AddressType) Type() protoreflect.EnumType {
	return &file_address_v1_address_proto_enumTypes[0]
}

func (x AddressType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddressType.Descriptor instead.
func (AddressType) EnumDescriptor() ([]byte, []int) {
	return file_address_v1_address_proto_rawDescGZIP(), []int{0}
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AddrType      AddressType            `protobuf:"varint,3,opt,name=addr_type,json=addrType,proto3,enum=address.v1.AddressType" json:"addr_type,omitempty"`
	ReceiverName  string                 `protobuf:"bytes,4,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`
	ReceiverPhone string                 `protobuf:"bytes,5,opt,name=receiver_phone,json=receiverPhone,proto3" json:"receiver_phone,omitempty"`
	Province      string                 `protobuf:"bytes,6,opt,name=province,proto3" json:"province,omitempty"`
	City          string                 `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`
	District      string                 `protobuf:"bytes,8,opt,name=district,proto3" json:"district,omitempty"`
	DetailAddr    string                 `protobuf:"bytes,9,opt,name=detail_addr,json=detailAddr,proto3" json:"detail_addr,omitempty"`
	IsDefault     bool                   `protobuf:"varint,10,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	DelFlag       bool                   `protobuf:"varint,13,opt,name=del_flag,json=delFlag,proto3" json:"del_flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_address_v1_address_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_address_v1_address_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_address_v1_address_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Address) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Address) GetAddrType() AddressType {
	if x != nil {
		return x.AddrType
	}
	return AddressType_ADDRESS_TYPE_UNSPECIFIED
}

func (x *Address) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *Address) GetReceiverPhone() string {
	if x != nil {
		return x.ReceiverPhone
	}
	return ""
}

func (x *Address) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *Address) GetDetailAddr() string {
	if x != nil {
		return x.DetailAddr
	}
	return ""
}

func (x *Address) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *Address) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Address) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Address) GetDelFlag() bool {
	if x != nil {
		return x.DelFlag
	}
	return false
}

type AddressSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []*Address             `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressSet) Reset() {
	*x = AddressSet{}
	mi := &file_address_v1_address_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressSet) ProtoMessage() {}

func (x *AddressSet) ProtoReflect() protoreflect.Message {
	mi := &file_address_v1_address_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressSet.ProtoReflect.Descriptor instead.
func (*AddressSet) Descriptor() ([]byte, []int) {
	return file_address_v1_address_proto_rawDescGZIP(), []int{1}
}

func (x *AddressSet) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *AddressSet) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *Address               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddressRequest) Reset() {
	*x = CreateAddressRequest{}
	mi := &file_address_v1_address_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressRequest) ProtoMessage() {}

func (x *CreateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_address_v1_address_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressRequest.ProtoReflect.Descriptor instead.
func (*CreateAddressRequest) Descriptor() ([]byte, []int) {
	return file_address_v1_address_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAddressRequest) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type UpdateAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *Address               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAddressRequest) Reset() {
	*x = UpdateAddressRequest{}
	mi := &file_address_v1_address_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddressRequest) ProtoMessage() {}

func (x *UpdateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_address_v1_address_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddressRequest.ProtoReflect.Descriptor instead.
func (*UpdateAddressRequest) Descriptor() ([]byte, []int) {
	return file_address_v1_address_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateAddressRequest) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *UpdateAddressRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type ListAddressesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AddrType      AddressType            `protobuf:"varint,2,opt,name=addr_type,json=addrType,proto3,enum=address.v1.AddressType" json:"addr_type,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAddressesRequest) Reset() {
	*x = ListAddressesRequest{}
	mi := &file_address_v1_address_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddressesRequest) ProtoMessage() {}

func (x *ListAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_address_v1_address_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddressesRequest.ProtoReflect.Descriptor instead.
func (*ListAddressesRequest) Descriptor() ([]byte, []int) {
	return file_address_v1_address_proto_rawDescGZIP(), []int{4}
}

func (x *ListAddressesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListAddressesRequest) GetAddrType() AddressType {
	if x != nil {
		return x.AddrType
	}
	return AddressType_ADDRESS_TYPE_UNSPECIFIED
}

func (x *ListAddressesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAddressesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type DeleteAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAddressRequest) Reset() {
	*x = DeleteAddressRequest{}
	mi := &file_address_v1_address_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddressRequest) ProtoMessage() {}

func (x *DeleteAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_address_v1_address_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddressRequest.ProtoReflect.Descriptor instead.
func (*DeleteAddressRequest) Descriptor() ([]byte, []int) {
	return file_address_v1_address_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteAddressRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteAddressRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BatchDeleteAddressesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Ids           []int64                `protobuf:"varint,2,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeleteAddressesRequest) Reset() {
	*x = BatchDeleteAddressesRequest{}
	mi := &file_address_v1_address_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeleteAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeleteAddressesRequest) ProtoMessage() {}

func (x *BatchDeleteAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_address_v1_address_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeleteAddressesRequest.ProtoReflect.Descriptor instead.
func (*BatchDeleteAddressesRequest) Descriptor() ([]byte, []int) {
	return file_address_v1_address_proto_rawDescGZIP(), []int{6}
}

func (x *BatchDeleteAddressesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BatchDeleteAddressesRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type BatchDeleteAddressesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int32                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeleteAddressesReply) Reset() {
	*x = BatchDeleteAddressesReply{}
	mi := &file_address_v1_address_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeleteAddressesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeleteAddressesReply) ProtoMessage() {}

func (x *BatchDeleteAddressesReply) ProtoReflect() protoreflect.Message {
	mi := &file_address_v1_address_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeleteAddressesReply.ProtoReflect.Descriptor instead.
func (*BatchDeleteAddressesReply) Descriptor() ([]byte, []int) {
	return file_address_v1_address_proto_rawDescGZIP(), []int{7}
}

func (x *BatchDeleteAddressesReply) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

type ParseAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseAddressRequest) Reset() {
	*x = ParseAddressRequest{}
	mi := &file_address_v1_address_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseAddressRequest) ProtoMessage() {}

func (x *ParseAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_address_v1_address_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseAddressRequest.ProtoReflect.Descriptor instead.
func (*ParseAddressRequest) Descriptor() ([]byte, []int) {
	return file_address_v1_address_proto_rawDescGZIP(), []int{8}
}

func (x *ParseAddressRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ParseAddressReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *Address               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseAddressReply) Reset() {
	*x = ParseAddressReply{}
	mi := &file_address_v1_address_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseAddressReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseAddressReply) ProtoMessage() {}

func (x *ParseAddressReply) ProtoReflect() protoreflect.Message {
	mi := &file_address_v1_address_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseAddressReply.ProtoReflect.Descriptor instead.
func (*ParseAddressReply) Descriptor() ([]byte, []int) {
	return file_address_v1_address_proto_rawDescGZIP(), []int{9}
}

func (x *ParseAddressReply) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

var File_address_v1_address_proto protoreflect.FileDescriptor

const file_address_v1_address_proto_rawDesc = "" +
	"\n" +
	"\x18address/v1/address.proto\x12\n" +
	"address.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd5\x03\n" +
	"\aAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x124\n" +
	"\taddr_type\x18\x03 \x01(\x0e2\x17.address.v1.AddressTypeR\baddrType\x12#\n" +
	"\rreceiver_name\x18\x04 \x01(\tR\freceiverName\x12%\n" +
	"\x0ereceiver_phone\x18\x05 \x01(\tR\rreceiverPhone\x12\x1a\n" +
	"\bprovince\x18\x06 \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\a \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\b \x01(\tR\bdistrict\x12\x1f\n" +
	"\vdetail_addr\x18\t \x01(\tR\n" +
	"detailAddr\x12\x1d\n" +
	"\n" +
	"is_default\x18\n" +
	" \x01(\bR\tisDefault\x12;\n" +
	"\vcreate_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12\x19\n" +
	"\bdel_flag\x18\r \x01(\bR\adelFlag\"g\n" +
	"\n" +
	"AddressSet\x121\n" +
	"\taddresses\x18\x01 \x03(\v2\x13.address.v1.AddressR\taddresses\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"J\n" +
	"\x14CreateAddressRequest\x122\n" +
	"\aaddress\x18\x01 \x01(\v2\x13.address.v1.AddressB\x03\xe0A\x02R\aaddress\"\x8c\x01\n" +
	"\x14UpdateAddressRequest\x122\n" +
	"\aaddress\x18\x01 \x01(\v2\x13.address.v1.AddressB\x03\xe0A\x02R\aaddress\x12@\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02R\n" +
	"updateMask\"\xa6\x01\n" +
	"\x14ListAddressesRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x06userId\x124\n" +
	"\taddr_type\x18\x02 \x01(\x0e2\x17.address.v1.AddressTypeR\baddrType\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"I\n" +
	"\x14DeleteAddressRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x06userId\x12\x13\n" +
	"\x02id\x18\x02 \x01(\x03B\x03\xe0A\x02R\x02id\"R\n" +
	"\x1bBatchDeleteAddressesRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x06userId\x12\x15\n" +
	"\x03ids\x18\x02 \x03(\x03B\x03\xe0A\x02R\x03ids\"@\n" +
	"\x19BatchDeleteAddressesReply\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x05R\fdeletedCount\"4\n" +
	"\x13ParseAddressRequest\x12\x1d\n" +
	"\acontent\x18\x01 \x01(\tB\x03\xe0A\x02R\acontent\"B\n" +
	"\x11ParseAddressReply\x12-\n" +
	"\aaddress\x18\x01 \x01(\v2\x13.address.v1.AddressR\aaddress*\x81\x01\n" +
	"\vAddressType\x12\x1c\n" +
	"\x18ADDRESS_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ADDRESS_TYPE_MAINLAND\x10\x01\x12\x19\n" +
	"\x15ADDRESS_TYPE_HK_MO_TW\x10\x02\x12\x1e\n" +
	"\x1aADDRESS_TYPE_INTERNATIONAL\x10\x032\xd6\x05\n" +
	"\x0eAddressService\x12h\n" +
	"\rListAddresses\x12 .address.v1.ListAddressesRequest\x1a\x16.address.v1.AddressSet\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/user/address/list\x12m\n" +
	"\rCreateAddress\x12 .address.v1.CreateAddressRequest\x1a\x13.address.v1.Address\"%\x82\xd3\xe4\x93\x02\x1f:\aaddress\"\x14/v1/user/address/add\x12{\n" +
	"\rUpdateAddress\x12 .address.v1.UpdateAddressRequest\x1a\x13.address.v1.Address\"3\x82\xd3\xe4\x93\x02-:\aaddress\x1a\"/v1/user/address/edit/{address.id}\x12h\n" +
	"\rDeleteAddress\x12 .address.v1.DeleteAddressRequest\x1a\x16.google.protobuf.Empty\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/v1/user/address/{id}\x12\x8d\x01\n" +
	"\x14BatchDeleteAddresses\x12'.address.v1.BatchDeleteAddressesRequest\x1a%.address.v1.BatchDeleteAddressesReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/user/address/batch/del\x12t\n" +
	"\fParseAddress\x12\x1f.address.v1.ParseAddressRequest\x1a\x1d.address.v1.ParseAddressReply\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/user/address/ai/parseBU\n" +
	"\x1bio.grpc.examples.address.v1B\fAddressProtoP\x01Z&shunfeng-miniprogram/api/address/v1;v1b\x06proto3"

var (
	file_address_v1_address_proto_rawDescOnce sync.Once
	file_address_v1_address_proto_rawDescData []byte
)

func file_address_v1_address_proto_rawDescGZIP() []byte {
	file_address_v1_address_proto_rawDescOnce.Do(func() {
		file_address_v1_address_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_address_v1_address_proto_rawDesc), len(file_address_v1_address_proto_rawDesc)))
	})
	return file_address_v1_address_proto_rawDescData
}

var file_address_v1_address_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_address_v1_address_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_address_v1_address_proto_goTypes = []any{
	(AddressType)(0),                    // 0: address.v1.AddressType
	(*Address)(nil),                     // 1: address.v1.Address
	(*AddressSet)(nil),                  // 2: address.v1.AddressSet
	(*CreateAddressRequest)(nil),        // 3: address.v1.CreateAddressRequest
	(*UpdateAddressRequest)(nil),        // 4: address.v1.UpdateAddressRequest
	(*ListAddressesRequest)(nil),        // 5: address.v1.ListAddressesRequest
	(*DeleteAddressRequest)(nil),        // 6: address.v1.DeleteAddressRequest
	(*BatchDeleteAddressesRequest)(nil), // 7: address.v1.BatchDeleteAddressesRequest
	(*BatchDeleteAddressesReply)(nil),   // 8: address.v1.BatchDeleteAddressesReply
	(*ParseAddressRequest)(nil),         // 9: address.v1.ParseAddressRequest
	(*ParseAddressReply)(nil),           // 10: address.v1.ParseAddressReply
	(*timestamppb.Timestamp)(nil),       // 11: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),       // 12: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),               // 13: google.protobuf.Empty
}
var file_address_v1_address_proto_depIdxs = []int32{
	0,  // 0: address.v1.Address.addr_type:type_name -> address.v1.AddressType
	11, // 1: address.v1.Address.create_time:type_name -> google.protobuf.Timestamp
	11, // 2: address.v1.Address.update_time:type_name -> google.protobuf.Timestamp
	1,  // 3: address.v1.AddressSet.addresses:type_name -> address.v1.Address
	1,  // 4: address.v1.CreateAddressRequest.address:type_name -> address.v1.Address
	1,  // 5: address.v1.UpdateAddressRequest.address:type_name -> address.v1.Address
	12, // 6: address.v1.UpdateAddressRequest.update_mask:type_name -> google.protobuf.FieldMask
	0,  // 7: address.v1.ListAddressesRequest.addr_type:type_name -> address.v1.AddressType
	1,  // 8: address.v1.ParseAddressReply.address:type_name -> address.v1.Address
	5,  // 9: address.v1.AddressService.ListAddresses:input_type -> address.v1.ListAddressesRequest
	3,  // 10: address.v1.AddressService.CreateAddress:input_type -> address.v1.CreateAddressRequest
	4,  // 11: address.v1.AddressService.UpdateAddress:input_type -> address.v1.UpdateAddressRequest
	6,  // 12: address.v1.AddressService.DeleteAddress:input_type -> address.v1.DeleteAddressRequest
	7,  // 13: address.v1.AddressService.BatchDeleteAddresses:input_type -> address.v1.BatchDeleteAddressesRequest
	9,  // 14: address.v1.AddressService.ParseAddress:input_type -> address.v1.ParseAddressRequest
	2,  // 15: address.v1.AddressService.ListAddresses:output_type -> address.v1.AddressSet
	1,  // 16: address.v1.AddressService.CreateAddress:output_type -> address.v1.Address
	1,  // 17: address.v1.AddressService.UpdateAddress:output_type -> address.v1.Address
	13, // 18: address.v1.AddressService.DeleteAddress:output_type -> google.protobuf.Empty
	8,  // 19: address.v1.AddressService.BatchDeleteAddresses:output_type -> address.v1.BatchDeleteAddressesReply
	10, // 20: address.v1.AddressService.ParseAddress:output_type -> address.v1.ParseAddressReply
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_address_v1_address_proto_init() }
func file_address_v1_address_proto_init() {
	if File_address_v1_address_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_address_v1_address_proto_rawDesc), len(file_address_v1_address_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_address_v1_address_proto_goTypes,
		DependencyIndexes: file_address_v1_address_proto_depIdxs,
		EnumInfos:         file_address_v1_address_proto_enumTypes,
		MessageInfos:      file_address_v1_address_proto_msgTypes,
	}.Build()
	File_address_v1_address_proto = out.File
	file_address_v1_address_proto_goTypes = nil
	file_address_v1_address_proto_depIdxs = nil
}
