// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: address/v1/address.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationAddressServiceBatchDeleteAddresses = "/address.v1.AddressService/BatchDeleteAddresses"
const OperationAddressServiceCreateAddress = "/address.v1.AddressService/CreateAddress"
const OperationAddressServiceDeleteAddress = "/address.v1.AddressService/DeleteAddress"
const OperationAddressServiceListAddresses = "/address.v1.AddressService/ListAddresses"
const OperationAddressServiceParseAddress = "/address.v1.AddressService/ParseAddress"
const OperationAddressServiceUpdateAddress = "/address.v1.AddressService/UpdateAddress"

type AddressServiceHTTPServer interface {
	BatchDeleteAddresses(context.Context, *BatchDeleteAddressesRequest) (*BatchDeleteAddressesReply, error)
	CreateAddress(context.Context, *CreateAddressRequest) (*Address, error)
	DeleteAddress(context.Context, *DeleteAddressRequest) (*emptypb.Empty, error)
	ListAddresses(context.Context, *ListAddressesRequest) (*AddressSet, error)
	ParseAddress(context.Context, *ParseAddressRequest) (*ParseAddressReply, error)
	UpdateAddress(context.Context, *UpdateAddressRequest) (*Address, error)
}

func RegisterAddressServiceHTTPServer(s *http.Server, srv AddressServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/user/address/list", _AddressService_ListAddresses0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/user/address/add", _AddressService_CreateAddress0_HTTP_Handler(srv))
	r.Handle("PUT", "/v1/user/address/edit/{address.id}", _AddressService_UpdateAddress0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/user/address/{id}", _AddressService_DeleteAddress0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/user/address/batch/del", _AddressService_BatchDeleteAddresses0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/user/address/ai/parse", _AddressService_ParseAddress0_HTTP_Handler(srv))
}

func _AddressService_ListAddresses0_HTTP_Handler(srv AddressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAddressesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAddressServiceListAddresses)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAddresses(ctx, req.(*ListAddressesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddressSet)
		return ctx.Result(200, reply)
	}
}

func _AddressService_CreateAddress0_HTTP_Handler(srv AddressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAddressRequest
		if err := ctx.Bind(&in.Address); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAddressServiceCreateAddress)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAddress(ctx, req.(*CreateAddressRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Address)
		return ctx.Result(200, reply)
	}
}

func _AddressService_UpdateAddress0_HTTP_Handler(srv AddressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateAddressRequest
		if err := ctx.Bind(&in.Address); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAddressServiceUpdateAddress)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateAddress(ctx, req.(*UpdateAddressRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Address)
		return ctx.Result(200, reply)
	}
}

func _AddressService_DeleteAddress0_HTTP_Handler(srv AddressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteAddressRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAddressServiceDeleteAddress)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteAddress(ctx, req.(*DeleteAddressRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _AddressService_BatchDeleteAddresses0_HTTP_Handler(srv AddressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BatchDeleteAddressesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAddressServiceBatchDeleteAddresses)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BatchDeleteAddresses(ctx, req.(*BatchDeleteAddressesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BatchDeleteAddressesReply)
		return ctx.Result(200, reply)
	}
}

func _AddressService_ParseAddress0_HTTP_Handler(srv AddressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ParseAddressRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAddressServiceParseAddress)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ParseAddress(ctx, req.(*ParseAddressRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ParseAddressReply)
		return ctx.Result(200, reply)
	}
}

type AddressServiceHTTPClient interface {
	BatchDeleteAddresses(ctx context.Context, req *BatchDeleteAddressesRequest, opts ...http.CallOption) (rsp *BatchDeleteAddressesReply, err error)
	CreateAddress(ctx context.Context, req *CreateAddressRequest, opts ...http.CallOption) (rsp *Address, err error)
	DeleteAddress(ctx context.Context, req *DeleteAddressRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	ListAddresses(ctx context.Context, req *ListAddressesRequest, opts ...http.CallOption) (rsp *AddressSet, err error)
	ParseAddress(ctx context.Context, req *ParseAddressRequest, opts ...http.CallOption) (rsp *ParseAddressReply, err error)
	UpdateAddress(ctx context.Context, req *UpdateAddressRequest, opts ...http.CallOption) (rsp *Address, err error)
}

type AddressServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAddressServiceHTTPClient(client *http.Client) AddressServiceHTTPClient {
	return &AddressServiceHTTPClientImpl{client}
}

func (c *AddressServiceHTTPClientImpl) BatchDeleteAddresses(ctx context.Context, in *BatchDeleteAddressesRequest, opts ...http.CallOption) (*BatchDeleteAddressesReply, error) {
	var out BatchDeleteAddressesReply
	pattern := "/v1/user/address/batch/del"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAddressServiceBatchDeleteAddresses),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AddressServiceHTTPClientImpl) CreateAddress(ctx context.Context, in *CreateAddressRequest, opts ...http.CallOption) (*Address, error) {
	var out Address
	pattern := "/v1/user/address/add"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("address"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAddressServiceCreateAddress),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in.Address, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AddressServiceHTTPClientImpl) DeleteAddress(ctx context.Context, in *DeleteAddressRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/user/address/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAddressServiceDeleteAddress),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AddressServiceHTTPClientImpl) ListAddresses(ctx context.Context, in *ListAddressesRequest, opts ...http.CallOption) (*AddressSet, error) {
	var out AddressSet
	pattern := "/v1/user/address/list"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAddressServiceListAddresses),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AddressServiceHTTPClientImpl) ParseAddress(ctx context.Context, in *ParseAddressRequest, opts ...http.CallOption) (*ParseAddressReply, error) {
	var out ParseAddressReply
	pattern := "/v1/user/address/ai/parse"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAddressServiceParseAddress),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AddressServiceHTTPClientImpl) UpdateAddress(ctx context.Context, in *UpdateAddressRequest, opts ...http.CallOption) (*Address, error) {
	var out Address
	pattern := "/v1/user/address/edit/{address.id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("address"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAddressServiceUpdateAddress),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in.Address, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
