// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: order/v1/order.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationOrderServiceExportHistory = "/order.v1.OrderService/ExportHistory"
const OperationOrderServiceGetHistoryCount = "/order.v1.OrderService/GetHistoryCount"
const OperationOrderServiceListHistoryRecords = "/order.v1.OrderService/ListHistoryRecords"

type OrderServiceHTTPServer interface {
	ExportHistory(context.Context, *ExportHistoryRequest) (*ExportHistoryReply, error)
	GetHistoryCount(context.Context, *GetHistoryCountRequest) (*HistoryCount, error)
	ListHistoryRecords(context.Context, *ListHistoryRecordsRequest) (*HistoryRecordSet, error)
}

func RegisterOrderServiceHTTPServer(s *http.Server, srv OrderServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/api/order/history/count", _OrderService_GetHistoryCount0_HTTP_Handler(srv))
	r.Handle("GET", "/api/order/history/list", _OrderService_ListHistoryRecords0_HTTP_Handler(srv))
	r.Handle("GET", "/api/order/history/export", _OrderService_ExportHistory0_HTTP_Handler(srv))
}

func _OrderService_GetHistoryCount0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetHistoryCountRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceGetHistoryCount)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetHistoryCount(ctx, req.(*GetHistoryCountRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HistoryCount)
		return ctx.Result(200, reply)
	}
}

func _OrderService_ListHistoryRecords0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListHistoryRecordsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceListHistoryRecords)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListHistoryRecords(ctx, req.(*ListHistoryRecordsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HistoryRecordSet)
		return ctx.Result(200, reply)
	}
}

func _OrderService_ExportHistory0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ExportHistoryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceExportHistory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExportHistory(ctx, req.(*ExportHistoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExportHistoryReply)
		return ctx.Result(200, reply)
	}
}

type OrderServiceHTTPClient interface {
	ExportHistory(ctx context.Context, req *ExportHistoryRequest, opts ...http.CallOption) (rsp *ExportHistoryReply, err error)
	GetHistoryCount(ctx context.Context, req *GetHistoryCountRequest, opts ...http.CallOption) (rsp *HistoryCount, err error)
	ListHistoryRecords(ctx context.Context, req *ListHistoryRecordsRequest, opts ...http.CallOption) (rsp *HistoryRecordSet, err error)
}

type OrderServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewOrderServiceHTTPClient(client *http.Client) OrderServiceHTTPClient {
	return &OrderServiceHTTPClientImpl{client}
}

func (c *OrderServiceHTTPClientImpl) ExportHistory(ctx context.Context, in *ExportHistoryRequest, opts ...http.CallOption) (*ExportHistoryReply, error) {
	var out ExportHistoryReply
	pattern := "/api/order/history/export"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationOrderServiceExportHistory),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrderServiceHTTPClientImpl) GetHistoryCount(ctx context.Context, in *GetHistoryCountRequest, opts ...http.CallOption) (*HistoryCount, error) {
	var out HistoryCount
	pattern := "/api/order/history/count"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationOrderServiceGetHistoryCount),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrderServiceHTTPClientImpl) ListHistoryRecords(ctx context.Context, in *ListHistoryRecordsRequest, opts ...http.CallOption) (*HistoryRecordSet, error) {
	var out HistoryRecordSet
	pattern := "/api/order/history/list"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationOrderServiceListHistoryRecords),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
