// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: order/v2/order.proto

package v2

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationOrderServiceEstimateFreight = "/order.v2.OrderService/EstimateFreight"

type OrderServiceHTTPServer interface {
	EstimateFreight(context.Context, *EstimateFreightRequest) (*EstimateFreightReply, error)
}

func RegisterOrderServiceHTTPServer(s *http.Server, srv OrderServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/api/order/freight/estimate", _OrderService_EstimateFreight0_HTTP_Handler(srv))
}

func _OrderService_EstimateFreight0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in EstimateFreightRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceEstimateFreight)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.EstimateFreight(ctx, req.(*EstimateFreightRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EstimateFreightReply)
		return ctx.Result(200, reply)
	}
}

type OrderServiceHTTPClient interface {
	EstimateFreight(ctx context.Context, req *EstimateFreightRequest, opts ...http.CallOption) (rsp *EstimateFreightReply, err error)
}

type OrderServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewOrderServiceHTTPClient(client *http.Client) OrderServiceHTTPClient {
	return &OrderServiceHTTPClientImpl{client}
}

func (c *OrderServiceHTTPClientImpl) EstimateFreight(ctx context.Context, in *EstimateFreightRequest, opts ...http.CallOption) (*EstimateFreightReply, error) {
	var out EstimateFreightReply
	pattern := "/api/order/freight/estimate"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationOrderServiceEstimateFreight),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
