// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: order/v2/order.proto

package v2

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 运费预估请求
type EstimateFreightRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 寄件信息
	SenderProvince string `protobuf:"bytes,1,opt,name=sender_province,json=senderProvince,proto3" json:"sender_province,omitempty"`
	SenderCity     string `protobuf:"bytes,2,opt,name=sender_city,json=senderCity,proto3" json:"sender_city,omitempty"`
	SenderArea     string `protobuf:"bytes,3,opt,name=sender_area,json=senderArea,proto3" json:"sender_area,omitempty"`
	// 收件信息
	ReceiverProvince string `protobuf:"bytes,4,opt,name=receiver_province,json=receiverProvince,proto3" json:"receiver_province,omitempty"`
	ReceiverCity     string `protobuf:"bytes,5,opt,name=receiver_city,json=receiverCity,proto3" json:"receiver_city,omitempty"`
	ReceiverArea     string `protobuf:"bytes,6,opt,name=receiver_area,json=receiverArea,proto3" json:"receiver_area,omitempty"`
	// 包裹参数
	Weight float64 `protobuf:"fixed64,7,opt,name=weight,proto3" json:"weight,omitempty"`
	Length int32   `protobuf:"varint,8,opt,name=length,proto3" json:"length,omitempty"`
	Width  int32   `protobuf:"varint,9,opt,name=width,proto3" json:"width,omitempty"`
	Height int32   `protobuf:"varint,10,opt,name=height,proto3" json:"height,omitempty"`
	// 快递类型：1标快 2特快 3特惠
	ExpressType int32 `protobuf:"varint,11,opt,name=express_type,json=expressType,proto3" json:"express_type,omitempty"`
	// 保价金额 0=不保价
	InsureValue   float64 `protobuf:"fixed64,12,opt,name=insure_value,json=insureValue,proto3" json:"insure_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstimateFreightRequest) Reset() {
	*x = EstimateFreightRequest{}
	mi := &file_order_v2_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateFreightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateFreightRequest) ProtoMessage() {}

func (x *EstimateFreightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v2_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateFreightRequest.ProtoReflect.Descriptor instead.
func (*EstimateFreightRequest) Descriptor() ([]byte, []int) {
	return file_order_v2_order_proto_rawDescGZIP(), []int{0}
}

func (x *EstimateFreightRequest) GetSenderProvince() string {
	if x != nil {
		return x.SenderProvince
	}
	return ""
}

func (x *EstimateFreightRequest) GetSenderCity() string {
	if x != nil {
		return x.SenderCity
	}
	return ""
}

func (x *EstimateFreightRequest) GetSenderArea() string {
	if x != nil {
		return x.SenderArea
	}
	return ""
}

func (x *EstimateFreightRequest) GetReceiverProvince() string {
	if x != nil {
		return x.ReceiverProvince
	}
	return ""
}

func (x *EstimateFreightRequest) GetReceiverCity() string {
	if x != nil {
		return x.ReceiverCity
	}
	return ""
}

func (x *EstimateFreightRequest) GetReceiverArea() string {
	if x != nil {
		return x.ReceiverArea
	}
	return ""
}

func (x *EstimateFreightRequest) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *EstimateFreightRequest) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *EstimateFreightRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *EstimateFreightRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *EstimateFreightRequest) GetExpressType() int32 {
	if x != nil {
		return x.ExpressType
	}
	return 0
}

func (x *EstimateFreightRequest) GetInsureValue() float64 {
	if x != nil {
		return x.InsureValue
	}
	return 0
}

// 运费预估返回结果
type EstimateFreightReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseFreight   float64                `protobuf:"fixed64,1,opt,name=base_freight,json=baseFreight,proto3" json:"base_freight,omitempty"`
	InsureFee     float64                `protobuf:"fixed64,2,opt,name=insure_fee,json=insureFee,proto3" json:"insure_fee,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,3,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	CalcWeight    float64                `protobuf:"fixed64,4,opt,name=calc_weight,json=calcWeight,proto3" json:"calc_weight,omitempty"`
	Tips          string                 `protobuf:"bytes,5,opt,name=tips,proto3" json:"tips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstimateFreightReply) Reset() {
	*x = EstimateFreightReply{}
	mi := &file_order_v2_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateFreightReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateFreightReply) ProtoMessage() {}

func (x *EstimateFreightReply) ProtoReflect() protoreflect.Message {
	mi := &file_order_v2_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateFreightReply.ProtoReflect.Descriptor instead.
func (*EstimateFreightReply) Descriptor() ([]byte, []int) {
	return file_order_v2_order_proto_rawDescGZIP(), []int{1}
}

func (x *EstimateFreightReply) GetBaseFreight() float64 {
	if x != nil {
		return x.BaseFreight
	}
	return 0
}

func (x *EstimateFreightReply) GetInsureFee() float64 {
	if x != nil {
		return x.InsureFee
	}
	return 0
}

func (x *EstimateFreightReply) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *EstimateFreightReply) GetCalcWeight() float64 {
	if x != nil {
		return x.CalcWeight
	}
	return 0
}

func (x *EstimateFreightReply) GetTips() string {
	if x != nil {
		return x.Tips
	}
	return ""
}

var File_order_v2_order_proto protoreflect.FileDescriptor

const file_order_v2_order_proto_rawDesc = "" +
	"\n" +
	"\x14order/v2/order.proto\x12\border.v2\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\"\xbc\x03\n" +
	"\x16EstimateFreightRequest\x12,\n" +
	"\x0fsender_province\x18\x01 \x01(\tB\x03\xe0A\x02R\x0esenderProvince\x12$\n" +
	"\vsender_city\x18\x02 \x01(\tB\x03\xe0A\x02R\n" +
	"senderCity\x12\x1f\n" +
	"\vsender_area\x18\x03 \x01(\tR\n" +
	"senderArea\x120\n" +
	"\x11receiver_province\x18\x04 \x01(\tB\x03\xe0A\x02R\x10receiverProvince\x12(\n" +
	"\rreceiver_city\x18\x05 \x01(\tB\x03\xe0A\x02R\freceiverCity\x12#\n" +
	"\rreceiver_area\x18\x06 \x01(\tR\freceiverArea\x12\x1b\n" +
	"\x06weight\x18\a \x01(\x01B\x03\xe0A\x02R\x06weight\x12\x16\n" +
	"\x06length\x18\b \x01(\x05R\x06length\x12\x14\n" +
	"\x05width\x18\t \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\n" +
	" \x01(\x05R\x06height\x12&\n" +
	"\fexpress_type\x18\v \x01(\x05B\x03\xe0A\x02R\vexpressType\x12!\n" +
	"\finsure_value\x18\f \x01(\x01R\vinsureValue\"\xae\x01\n" +
	"\x14EstimateFreightReply\x12!\n" +
	"\fbase_freight\x18\x01 \x01(\x01R\vbaseFreight\x12\x1d\n" +
	"\n" +
	"insure_fee\x18\x02 \x01(\x01R\tinsureFee\x12\x1f\n" +
	"\vtotal_price\x18\x03 \x01(\x01R\n" +
	"totalPrice\x12\x1f\n" +
	"\vcalc_weight\x18\x04 \x01(\x01R\n" +
	"calcWeight\x12\x12\n" +
	"\x04tips\x18\x05 \x01(\tR\x04tips2\x8b\x01\n" +
	"\fOrderService\x12{\n" +
	"\x0fEstimateFreight\x12 .order.v2.EstimateFreightRequest\x1a\x1e.order.v2.EstimateFreightReply\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/order/freight/estimateBO\n" +
	"\x19io.grpc.examples.order.v2B\n" +
	"OrderProtoP\x01Z$shunfeng-miniprogram/api/order/v2;v2b\x06proto3"

var (
	file_order_v2_order_proto_rawDescOnce sync.Once
	file_order_v2_order_proto_rawDescData []byte
)

func file_order_v2_order_proto_rawDescGZIP() []byte {
	file_order_v2_order_proto_rawDescOnce.Do(func() {
		file_order_v2_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_v2_order_proto_rawDesc), len(file_order_v2_order_proto_rawDesc)))
	})
	return file_order_v2_order_proto_rawDescData
}

var file_order_v2_order_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_order_v2_order_proto_goTypes = []any{
	(*EstimateFreightRequest)(nil), // 0: order.v2.EstimateFreightRequest
	(*EstimateFreightReply)(nil),   // 1: order.v2.EstimateFreightReply
}
var file_order_v2_order_proto_depIdxs = []int32{
	0, // 0: order.v2.OrderService.EstimateFreight:input_type -> order.v2.EstimateFreightRequest
	1, // 1: order.v2.OrderService.EstimateFreight:output_type -> order.v2.EstimateFreightReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_order_v2_order_proto_init() }
func file_order_v2_order_proto_init() {
	if File_order_v2_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_v2_order_proto_rawDesc), len(file_order_v2_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_v2_order_proto_goTypes,
		DependencyIndexes: file_order_v2_order_proto_depIdxs,
		MessageInfos:      file_order_v2_order_proto_msgTypes,
	}.Build()
	File_order_v2_order_proto = out.File
	file_order_v2_order_proto_goTypes = nil
	file_order_v2_order_proto_depIdxs = nil
}
