// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: order/v3/order.proto

package v3

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PaymentMethod 付款方式
type PaymentMethod int32

const (
	PaymentMethod_PAYMENT_METHOD_UNSPECIFIED PaymentMethod = 0
	PaymentMethod_SENDER_PAY                 PaymentMethod = 1 // 寄付现结
	PaymentMethod_RECEIVER_PAY               PaymentMethod = 2 // 到付
	PaymentMethod_MONTHLY_SETTLE             PaymentMethod = 3 // 月结
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "PAYMENT_METHOD_UNSPECIFIED",
		1: "SENDER_PAY",
		2: "RECEIVER_PAY",
		3: "MONTHLY_SETTLE",
	}
	PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_UNSPECIFIED": 0,
		"SENDER_PAY":                 1,
		"RECEIVER_PAY":               2,
		"MONTHLY_SETTLE":             3,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_order_v3_order_proto_enumTypes[0].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_order_v3_order_proto_enumTypes[0]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_order_v3_order_proto_rawDescGZIP(), []int{0}
}

// PaymentStatus 支付状态
type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PENDING                    PaymentStatus = 1 // 待支付
	PaymentStatus_PAID                       PaymentStatus = 2 // 已支付
	PaymentStatus_EXPIRED                    PaymentStatus = 3 // 已过期
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PENDING",
		2: "PAID",
		3: "EXPIRED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PENDING":                    1,
		"PAID":                       2,
		"EXPIRED":                    3,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_order_v3_order_proto_enumTypes[1].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_order_v3_order_proto_enumTypes[1]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_order_v3_order_proto_rawDescGZIP(), []int{1}
}

// OrderStatus 订单状态
type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	OrderStatus_PENDING_PICKUP           OrderStatus = 1 // 待揽收
	OrderStatus_ACCEPTED                 OrderStatus = 2 // 已接单
	OrderStatus_AWAITING_PICKUP          OrderStatus = 3 // 待上门
	OrderStatus_PICKED_UP                OrderStatus = 4 // 已取件
	OrderStatus_IN_TRANSIT               OrderStatus = 5 // 运输中
	OrderStatus_DELIVERING               OrderStatus = 6 // 派送中
	OrderStatus_SIGNED                   OrderStatus = 7 // 已签收
	OrderStatus_CANCELLED                OrderStatus = 8 // 已取消
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "PENDING_PICKUP",
		2: "ACCEPTED",
		3: "AWAITING_PICKUP",
		4: "PICKED_UP",
		5: "IN_TRANSIT",
		6: "DELIVERING",
		7: "SIGNED",
		8: "CANCELLED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED": 0,
		"PENDING_PICKUP":           1,
		"ACCEPTED":                 2,
		"AWAITING_PICKUP":          3,
		"PICKED_UP":                4,
		"IN_TRANSIT":               5,
		"DELIVERING":               6,
		"SIGNED":                   7,
		"CANCELLED":                8,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_order_v3_order_proto_enumTypes[2].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_order_v3_order_proto_enumTypes[2]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_order_v3_order_proto_rawDescGZIP(), []int{2}
}

// ChannelCode 寄件渠道
type ChannelCode int32

const (
	ChannelCode_CHANNEL_UNSPECIFIED ChannelCode = 0
	ChannelCode_DOOR_PICKUP         ChannelCode = 1 // 上门取件
	ChannelCode_LOCKER              ChannelCode = 2 // 丰巢柜
	ChannelCode_SF_STATION          ChannelCode = 3 // 顺丰网点
	ChannelCode_PARTNER_STORE       ChannelCode = 4 // 合作门店
)

// Enum value maps for ChannelCode.
var (
	ChannelCode_name = map[int32]string{
		0: "CHANNEL_UNSPECIFIED",
		1: "DOOR_PICKUP",
		2: "LOCKER",
		3: "SF_STATION",
		4: "PARTNER_STORE",
	}
	ChannelCode_value = map[string]int32{
		"CHANNEL_UNSPECIFIED": 0,
		"DOOR_PICKUP":         1,
		"LOCKER":              2,
		"SF_STATION":          3,
		"PARTNER_STORE":       4,
	}
)

func (x ChannelCode) Enum() *ChannelCode {
	p := new(ChannelCode)
	*p = x
	return p
}

func (x ChannelCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChannelCode) Descriptor() protoreflect.EnumDescriptor {
	return file_order_v3_order_proto_enumTypes[3].Descriptor()
}

func (ChannelCode) Type() protoreflect.EnumType {
	return &file_order_v3_order_proto_enumTypes[3]
}

func (x ChannelCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChannelCode.Descriptor instead.
func (ChannelCode) EnumDescriptor() ([]byte, []int) {
	return file_order_v3_order_proto_rawDescGZIP(), []int{3}
}

type CreateExpressOrderRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 寄件人
	SenderName     string `protobuf:"bytes,2,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	SenderPhone    string `protobuf:"bytes,3,opt,name=sender_phone,json=senderPhone,proto3" json:"sender_phone,omitempty"`
	SenderProvince string `protobuf:"bytes,4,opt,name=sender_province,json=senderProvince,proto3" json:"sender_province,omitempty"`
	SenderCity     string `protobuf:"bytes,5,opt,name=sender_city,json=senderCity,proto3" json:"sender_city,omitempty"`
	SenderDistrict string `protobuf:"bytes,6,opt,name=sender_district,json=senderDistrict,proto3" json:"sender_district,omitempty"`
	SenderDetail   string `protobuf:"bytes,7,opt,name=sender_detail,json=senderDetail,proto3" json:"sender_detail,omitempty"`
	// 收件人
	ReceiverName     string `protobuf:"bytes,8,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`
	ReceiverPhone    string `protobuf:"bytes,9,opt,name=receiver_phone,json=receiverPhone,proto3" json:"receiver_phone,omitempty"`
	ReceiverProvince string `protobuf:"bytes,10,opt,name=receiver_province,json=receiverProvince,proto3" json:"receiver_province,omitempty"`
	ReceiverCity     string `protobuf:"bytes,11,opt,name=receiver_city,json=receiverCity,proto3" json:"receiver_city,omitempty"`
	ReceiverDistrict string `protobuf:"bytes,12,opt,name=receiver_district,json=receiverDistrict,proto3" json:"receiver_district,omitempty"`
	ReceiverDetail   string `protobuf:"bytes,13,opt,name=receiver_detail,json=receiverDetail,proto3" json:"receiver_detail,omitempty"`
	// 包裹
	Weight float64 `protobuf:"fixed64,14,opt,name=weight,proto3" json:"weight,omitempty"`
	Length int32   `protobuf:"varint,15,opt,name=length,proto3" json:"length,omitempty"`
	Width  int32   `protobuf:"varint,16,opt,name=width,proto3" json:"width,omitempty"`
	Height int32   `protobuf:"varint,17,opt,name=height,proto3" json:"height,omitempty"`
	// 寄件渠道
	ChannelCode    ChannelCode `protobuf:"varint,18,opt,name=channel_code,json=channelCode,proto3,enum=order.v3.ChannelCode" json:"channel_code,omitempty"`
	LockerId       int64       `protobuf:"varint,19,opt,name=locker_id,json=lockerId,proto3" json:"locker_id,omitempty"`                     // 丰巢时必填
	BoxType        string      `protobuf:"bytes,20,opt,name=box_type,json=boxType,proto3" json:"box_type,omitempty"`                         // 丰巢时必填 (SMALL/MEDIUM/LARGE)
	ServicePointId int64       `protobuf:"varint,21,opt,name=service_point_id,json=servicePointId,proto3" json:"service_point_id,omitempty"` // 网点/门店时必填
	PickupDate     string      `protobuf:"bytes,22,opt,name=pickup_date,json=pickupDate,proto3" json:"pickup_date,omitempty"`                // 上门取件时必填
	PickupSlotCode string      `protobuf:"bytes,23,opt,name=pickup_slot_code,json=pickupSlotCode,proto3" json:"pickup_slot_code,omitempty"`  // 上门取件时必填
	// 付款方式
	PaymentMethod PaymentMethod `protobuf:"varint,24,opt,name=payment_method,json=paymentMethod,proto3,enum=order.v3.PaymentMethod" json:"payment_method,omitempty"`
	// 隐私保护
	PrivacyProtection bool `protobuf:"varint,25,opt,name=privacy_protection,json=privacyProtection,proto3" json:"privacy_protection,omitempty"`
	// 快递类型（与运费预估一致：1标快 2特快 3特惠）
	ExpressType   int32   `protobuf:"varint,26,opt,name=express_type,json=expressType,proto3" json:"express_type,omitempty"`
	InsureValue   float64 `protobuf:"fixed64,27,opt,name=insure_value,json=insureValue,proto3" json:"insure_value,omitempty"` // 保价金额
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExpressOrderRequest) Reset() {
	*x = CreateExpressOrderRequest{}
	mi := &file_order_v3_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExpressOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExpressOrderRequest) ProtoMessage() {}

func (x *CreateExpressOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v3_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExpressOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateExpressOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v3_order_proto_rawDescGZIP(), []int{0}
}

func (x *CreateExpressOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateExpressOrderRequest) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *CreateExpressOrderRequest) GetSenderPhone() string {
	if x != nil {
		return x.SenderPhone
	}
	return ""
}

func (x *CreateExpressOrderRequest) GetSenderProvince() string {
	if x != nil {
		return x.SenderProvince
	}
	return ""
}

func (x *CreateExpressOrderRequest) GetSenderCity() string {
	if x != nil {
		return x.SenderCity
	}
	return ""
}

func (x *CreateExpressOrderRequest) GetSenderDistrict() string {
	if x != nil {
		return x.SenderDistrict
	}
	return ""
}

func (x *CreateExpressOrderRequest) GetSenderDetail() string {
	if x != nil {
		return x.SenderDetail
	}
	return ""
}

func (x *CreateExpressOrderRequest) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *CreateExpressOrderRequest) GetReceiverPhone() string {
	if x != nil {
		return x.ReceiverPhone
	}
	return ""
}

func (x *CreateExpressOrderRequest) GetReceiverProvince() string {
	if x != nil {
		return x.ReceiverProvince
	}
	return ""
}

func (x *CreateExpressOrderRequest) GetReceiverCity() string {
	if x != nil {
		return x.ReceiverCity
	}
	return ""
}

func (x *CreateExpressOrderRequest) GetReceiverDistrict() string {
	if x != nil {
		return x.ReceiverDistrict
	}
	return ""
}

func (x *CreateExpressOrderRequest) GetReceiverDetail() string {
	if x != nil {
		return x.ReceiverDetail
	}
	return ""
}

func (x *CreateExpressOrderRequest) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *CreateExpressOrderRequest) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *CreateExpressOrderRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CreateExpressOrderRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CreateExpressOrderRequest) GetChannelCode() ChannelCode {
	if x != nil {
		return x.ChannelCode
	}
	return ChannelCode_CHANNEL_UNSPECIFIED
}

func (x *CreateExpressOrderRequest) GetLockerId() int64 {
	if x != nil {
		return x.LockerId
	}
	return 0
}

func (x *CreateExpressOrderRequest) GetBoxType() string {
	if x != nil {
		return x.BoxType
	}
	return ""
}

func (x *CreateExpressOrderRequest) GetServicePointId() int64 {
	if x != nil {
		return x.ServicePointId
	}
	return 0
}

func (x *CreateExpressOrderRequest) GetPickupDate() string {
	if x != nil {
		return x.PickupDate
	}
	return ""
}

func (x *CreateExpressOrderRequest) GetPickupSlotCode() string {
	if x != nil {
		return x.PickupSlotCode
	}
	return ""
}

func (x *CreateExpressOrderRequest) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *CreateExpressOrderRequest) GetPrivacyProtection() bool {
	if x != nil {
		return x.PrivacyProtection
	}
	return false
}

func (x *CreateExpressOrderRequest) GetExpressType() int32 {
	if x != nil {
		return x.ExpressType
	}
	return 0
}

func (x *CreateExpressOrderRequest) GetInsureValue() float64 {
	if x != nil {
		return x.InsureValue
	}
	return 0
}

type GetExpressOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExpressOrderRequest) Reset() {
	*x = GetExpressOrderRequest{}
	mi := &file_order_v3_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpressOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpressOrderRequest) ProtoMessage() {}

func (x *GetExpressOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v3_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpressOrderRequest.ProtoReflect.Descriptor instead.
func (*GetExpressOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v3_order_proto_rawDescGZIP(), []int{1}
}

func (x *GetExpressOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetExpressOrderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SearchOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchOrdersRequest) Reset() {
	*x = SearchOrdersRequest{}
	mi := &file_order_v3_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchOrdersRequest) ProtoMessage() {}

func (x *SearchOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v3_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchOrdersRequest.ProtoReflect.Descriptor instead.
func (*SearchOrdersRequest) Descriptor() ([]byte, []int) {
	return file_order_v3_order_proto_rawDescGZIP(), []int{2}
}

func (x *SearchOrdersRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SearchOrdersRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchOrdersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchOrdersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListOrdersByCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"` // "sent" / "received" / "followed" / "unpaid"
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersByCategoryRequest) Reset() {
	*x = ListOrdersByCategoryRequest{}
	mi := &file_order_v3_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersByCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersByCategoryRequest) ProtoMessage() {}

func (x *ListOrdersByCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v3_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersByCategoryRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersByCategoryRequest) Descriptor() ([]byte, []int) {
	return file_order_v3_order_proto_rawDescGZIP(), []int{3}
}

func (x *ListOrdersByCategoryRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListOrdersByCategoryRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListOrdersByCategoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOrdersByCategoryRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type DeleteExpressOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExpressOrderRequest) Reset() {
	*x = DeleteExpressOrderRequest{}
	mi := &file_order_v3_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExpressOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExpressOrderRequest) ProtoMessage() {}

func (x *DeleteExpressOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v3_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExpressOrderRequest.ProtoReflect.Descriptor instead.
func (*DeleteExpressOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v3_order_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteExpressOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteExpressOrderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SetOrderTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Tag           string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOrderTagRequest) Reset() {
	*x = SetOrderTagRequest{}
	mi := &file_order_v3_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOrderTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOrderTagRequest) ProtoMessage() {}

func (x *SetOrderTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v3_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOrderTagRequest.ProtoReflect.Descriptor instead.
func (*SetOrderTagRequest) Descriptor() ([]byte, []int) {
	return file_order_v3_order_proto_rawDescGZIP(), []int{5}
}

func (x *SetOrderTagRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetOrderTagRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetOrderTagRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type FollowOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Follow        bool                   `protobuf:"varint,3,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowOrderRequest) Reset() {
	*x = FollowOrderRequest{}
	mi := &file_order_v3_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowOrderRequest) ProtoMessage() {}

func (x *FollowOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v3_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowOrderRequest.ProtoReflect.Descriptor instead.
func (*FollowOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v3_order_proto_rawDescGZIP(), []int{6}
}

func (x *FollowOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FollowOrderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FollowOrderRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type ShareOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareOrderRequest) Reset() {
	*x = ShareOrderRequest{}
	mi := &file_order_v3_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareOrderRequest) ProtoMessage() {}

func (x *ShareOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v3_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareOrderRequest.ProtoReflect.Descriptor instead.
func (*ShareOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v3_order_proto_rawDescGZIP(), []int{7}
}

func (x *ShareOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ShareOrderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ShareOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShareUrl      string                 `protobuf:"bytes,1,opt,name=share_url,json=shareUrl,proto3" json:"share_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareOrderReply) Reset() {
	*x = ShareOrderReply{}
	mi := &file_order_v3_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareOrderReply) ProtoMessage() {}

func (x *ShareOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_order_v3_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareOrderReply.ProtoReflect.Descriptor instead.
func (*ShareOrderReply) Descriptor() ([]byte, []int) {
	return file_order_v3_order_proto_rawDescGZIP(), []int{8}
}

func (x *ShareOrderReply) GetShareUrl() string {
	if x != nil {
		return x.ShareUrl
	}
	return ""
}

type ExpressOrderReply struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId            int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderNo           string                 `protobuf:"bytes,3,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	ExpressNo         string                 `protobuf:"bytes,4,opt,name=express_no,json=expressNo,proto3" json:"express_no,omitempty"`
	SenderName        string                 `protobuf:"bytes,5,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	SenderPhone       string                 `protobuf:"bytes,6,opt,name=sender_phone,json=senderPhone,proto3" json:"sender_phone,omitempty"`
	SenderProvince    string                 `protobuf:"bytes,7,opt,name=sender_province,json=senderProvince,proto3" json:"sender_province,omitempty"`
	SenderCity        string                 `protobuf:"bytes,8,opt,name=sender_city,json=senderCity,proto3" json:"sender_city,omitempty"`
	SenderDistrict    string                 `protobuf:"bytes,9,opt,name=sender_district,json=senderDistrict,proto3" json:"sender_district,omitempty"`
	SenderDetail      string                 `protobuf:"bytes,10,opt,name=sender_detail,json=senderDetail,proto3" json:"sender_detail,omitempty"`
	ReceiverName      string                 `protobuf:"bytes,11,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`
	ReceiverPhone     string                 `protobuf:"bytes,12,opt,name=receiver_phone,json=receiverPhone,proto3" json:"receiver_phone,omitempty"`
	ReceiverProvince  string                 `protobuf:"bytes,13,opt,name=receiver_province,json=receiverProvince,proto3" json:"receiver_province,omitempty"`
	ReceiverCity      string                 `protobuf:"bytes,14,opt,name=receiver_city,json=receiverCity,proto3" json:"receiver_city,omitempty"`
	ReceiverDistrict  string                 `protobuf:"bytes,15,opt,name=receiver_district,json=receiverDistrict,proto3" json:"receiver_district,omitempty"`
	ReceiverDetail    string                 `protobuf:"bytes,16,opt,name=receiver_detail,json=receiverDetail,proto3" json:"receiver_detail,omitempty"`
	Weight            float64                `protobuf:"fixed64,17,opt,name=weight,proto3" json:"weight,omitempty"`
	Length            int32                  `protobuf:"varint,18,opt,name=length,proto3" json:"length,omitempty"`
	Width             int32                  `protobuf:"varint,19,opt,name=width,proto3" json:"width,omitempty"`
	Height            int32                  `protobuf:"varint,20,opt,name=height,proto3" json:"height,omitempty"`
	BaseFreight       float64                `protobuf:"fixed64,21,opt,name=base_freight,json=baseFreight,proto3" json:"base_freight,omitempty"`
	InsureFee         float64                `protobuf:"fixed64,22,opt,name=insure_fee,json=insureFee,proto3" json:"insure_fee,omitempty"`
	TotalFreight      float64                `protobuf:"fixed64,23,opt,name=total_freight,json=totalFreight,proto3" json:"total_freight,omitempty"`
	ChannelCode       ChannelCode            `protobuf:"varint,24,opt,name=channel_code,json=channelCode,proto3,enum=order.v3.ChannelCode" json:"channel_code,omitempty"`
	LockerId          int64                  `protobuf:"varint,25,opt,name=locker_id,json=lockerId,proto3" json:"locker_id,omitempty"`
	BoxType           string                 `protobuf:"bytes,26,opt,name=box_type,json=boxType,proto3" json:"box_type,omitempty"`
	ServicePointId    int64                  `protobuf:"varint,27,opt,name=service_point_id,json=servicePointId,proto3" json:"service_point_id,omitempty"`
	PickupDate        string                 `protobuf:"bytes,28,opt,name=pickup_date,json=pickupDate,proto3" json:"pickup_date,omitempty"`
	PickupSlotCode    string                 `protobuf:"bytes,29,opt,name=pickup_slot_code,json=pickupSlotCode,proto3" json:"pickup_slot_code,omitempty"`
	PaymentMethod     PaymentMethod          `protobuf:"varint,30,opt,name=payment_method,json=paymentMethod,proto3,enum=order.v3.PaymentMethod" json:"payment_method,omitempty"`
	PaymentStatus     PaymentStatus          `protobuf:"varint,31,opt,name=payment_status,json=paymentStatus,proto3,enum=order.v3.PaymentStatus" json:"payment_status,omitempty"`
	PrivacyProtection bool                   `protobuf:"varint,32,opt,name=privacy_protection,json=privacyProtection,proto3" json:"privacy_protection,omitempty"`
	Status            OrderStatus            `protobuf:"varint,33,opt,name=status,proto3,enum=order.v3.OrderStatus" json:"status,omitempty"`
	Tag               string                 `protobuf:"bytes,34,opt,name=tag,proto3" json:"tag,omitempty"`
	IsFollowed        bool                   `protobuf:"varint,35,opt,name=is_followed,json=isFollowed,proto3" json:"is_followed,omitempty"`
	ShareUrl          string                 `protobuf:"bytes,36,opt,name=share_url,json=shareUrl,proto3" json:"share_url,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,37,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,38,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExpressOrderReply) Reset() {
	*x = ExpressOrderReply{}
	mi := &file_order_v3_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpressOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpressOrderReply) ProtoMessage() {}

func (x *ExpressOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_order_v3_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpressOrderReply.ProtoReflect.Descriptor instead.
func (*ExpressOrderReply) Descriptor() ([]byte, []int) {
	return file_order_v3_order_proto_rawDescGZIP(), []int{9}
}

func (x *ExpressOrderReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExpressOrderReply) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ExpressOrderReply) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *ExpressOrderReply) GetExpressNo() string {
	if x != nil {
		return x.ExpressNo
	}
	return ""
}

func (x *ExpressOrderReply) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *ExpressOrderReply) GetSenderPhone() string {
	if x != nil {
		return x.SenderPhone
	}
	return ""
}

func (x *ExpressOrderReply) GetSenderProvince() string {
	if x != nil {
		return x.SenderProvince
	}
	return ""
}

func (x *ExpressOrderReply) GetSenderCity() string {
	if x != nil {
		return x.SenderCity
	}
	return ""
}

func (x *ExpressOrderReply) GetSenderDistrict() string {
	if x != nil {
		return x.SenderDistrict
	}
	return ""
}

func (x *ExpressOrderReply) GetSenderDetail() string {
	if x != nil {
		return x.SenderDetail
	}
	return ""
}

func (x *ExpressOrderReply) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *ExpressOrderReply) GetReceiverPhone() string {
	if x != nil {
		return x.ReceiverPhone
	}
	return ""
}

func (x *ExpressOrderReply) GetReceiverProvince() string {
	if x != nil {
		return x.ReceiverProvince
	}
	return ""
}

func (x *ExpressOrderReply) GetReceiverCity() string {
	if x != nil {
		return x.ReceiverCity
	}
	return ""
}

func (x *ExpressOrderReply) GetReceiverDistrict() string {
	if x != nil {
		return x.ReceiverDistrict
	}
	return ""
}

func (x *ExpressOrderReply) GetReceiverDetail() string {
	if x != nil {
		return x.ReceiverDetail
	}
	return ""
}

func (x *ExpressOrderReply) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ExpressOrderReply) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *ExpressOrderReply) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ExpressOrderReply) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ExpressOrderReply) GetBaseFreight() float64 {
	if x != nil {
		return x.BaseFreight
	}
	return 0
}

func (x *ExpressOrderReply) GetInsureFee() float64 {
	if x != nil {
		return x.InsureFee
	}
	return 0
}

func (x *ExpressOrderReply) GetTotalFreight() float64 {
	if x != nil {
		return x.TotalFreight
	}
	return 0
}

func (x *ExpressOrderReply) GetChannelCode() ChannelCode {
	if x != nil {
		return x.ChannelCode
	}
	return ChannelCode_CHANNEL_UNSPECIFIED
}

func (x *ExpressOrderReply) GetLockerId() int64 {
	if x != nil {
		return x.LockerId
	}
	return 0
}

func (x *ExpressOrderReply) GetBoxType() string {
	if x != nil {
		return x.BoxType
	}
	return ""
}

func (x *ExpressOrderReply) GetServicePointId() int64 {
	if x != nil {
		return x.ServicePointId
	}
	return 0
}

func (x *ExpressOrderReply) GetPickupDate() string {
	if x != nil {
		return x.PickupDate
	}
	return ""
}

func (x *ExpressOrderReply) GetPickupSlotCode() string {
	if x != nil {
		return x.PickupSlotCode
	}
	return ""
}

func (x *ExpressOrderReply) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *ExpressOrderReply) GetPaymentStatus() PaymentStatus {
	if x != nil {
		return x.PaymentStatus
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *ExpressOrderReply) GetPrivacyProtection() bool {
	if x != nil {
		return x.PrivacyProtection
	}
	return false
}

func (x *ExpressOrderReply) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *ExpressOrderReply) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ExpressOrderReply) GetIsFollowed() bool {
	if x != nil {
		return x.IsFollowed
	}
	return false
}

func (x *ExpressOrderReply) GetShareUrl() string {
	if x != nil {
		return x.ShareUrl
	}
	return ""
}

func (x *ExpressOrderReply) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ExpressOrderReply) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ExpressOrderSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*ExpressOrderReply   `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	NextPageToken string                 `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpressOrderSet) Reset() {
	*x = ExpressOrderSet{}
	mi := &file_order_v3_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpressOrderSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpressOrderSet) ProtoMessage() {}

func (x *ExpressOrderSet) ProtoReflect() protoreflect.Message {
	mi := &file_order_v3_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpressOrderSet.ProtoReflect.Descriptor instead.
func (*ExpressOrderSet) Descriptor() ([]byte, []int) {
	return file_order_v3_order_proto_rawDescGZIP(), []int{10}
}

func (x *ExpressOrderSet) GetOrders() []*ExpressOrderReply {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ExpressOrderSet) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ExpressOrderSet) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_order_v3_order_proto protoreflect.FileDescriptor

const file_order_v3_order_proto_rawDesc = "" +
	"\n" +
	"\x14order/v3/order.proto\x12\border.v3\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc4\b\n" +
	"\x19CreateExpressOrderRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x06userId\x12$\n" +
	"\vsender_name\x18\x02 \x01(\tB\x03\xe0A\x02R\n" +
	"senderName\x12&\n" +
	"\fsender_phone\x18\x03 \x01(\tB\x03\xe0A\x02R\vsenderPhone\x12,\n" +
	"\x0fsender_province\x18\x04 \x01(\tB\x03\xe0A\x02R\x0esenderProvince\x12$\n" +
	"\vsender_city\x18\x05 \x01(\tB\x03\xe0A\x02R\n" +
	"senderCity\x12'\n" +
	"\x0fsender_district\x18\x06 \x01(\tR\x0esenderDistrict\x12(\n" +
	"\rsender_detail\x18\a \x01(\tB\x03\xe0A\x02R\fsenderDetail\x12(\n" +
	"\rreceiver_name\x18\b \x01(\tB\x03\xe0A\x02R\freceiverName\x12*\n" +
	"\x0ereceiver_phone\x18\t \x01(\tB\x03\xe0A\x02R\rreceiverPhone\x120\n" +
	"\x11receiver_province\x18\n" +
	" \x01(\tB\x03\xe0A\x02R\x10receiverProvince\x12(\n" +
	"\rreceiver_city\x18\v \x01(\tB\x03\xe0A\x02R\freceiverCity\x12+\n" +
	"\x11receiver_district\x18\f \x01(\tR\x10receiverDistrict\x12,\n" +
	"\x0freceiver_detail\x18\r \x01(\tB\x03\xe0A\x02R\x0ereceiverDetail\x12\x1b\n" +
	"\x06weight\x18\x0e \x01(\x01B\x03\xe0A\x02R\x06weight\x12\x16\n" +
	"\x06length\x18\x0f \x01(\x05R\x06length\x12\x14\n" +
	"\x05width\x18\x10 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x11 \x01(\x05R\x06height\x12=\n" +
	"\fchannel_code\x18\x12 \x01(\x0e2\x15.order.v3.ChannelCodeB\x03\xe0A\x02R\vchannelCode\x12\x1b\n" +
	"\tlocker_id\x18\x13 \x01(\x03R\blockerId\x12\x19\n" +
	"\bbox_type\x18\x14 \x01(\tR\aboxType\x12(\n" +
	"\x10service_point_id\x18\x15 \x01(\x03R\x0eservicePointId\x12\x1f\n" +
	"\vpickup_date\x18\x16 \x01(\tR\n" +
	"pickupDate\x12(\n" +
	"\x10pickup_slot_code\x18\x17 \x01(\tR\x0epickupSlotCode\x12C\n" +
	"\x0epayment_method\x18\x18 \x01(\x0e2\x17.order.v3.PaymentMethodB\x03\xe0A\x02R\rpaymentMethod\x12-\n" +
	"\x12privacy_protection\x18\x19 \x01(\bR\x11privacyProtection\x12!\n" +
	"\fexpress_type\x18\x1a \x01(\x05R\vexpressType\x12!\n" +
	"\finsure_value\x18\x1b \x01(\x01R\vinsureValue\"K\n" +
	"\x16GetExpressOrderRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x06userId\x12\x13\n" +
	"\x02id\x18\x02 \x01(\x03B\x03\xe0A\x02R\x02id\"\x89\x01\n" +
	"\x13SearchOrdersRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x06userId\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\x98\x01\n" +
	"\x1bListOrdersByCategoryRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x06userId\x12\x1f\n" +
	"\bcategory\x18\x02 \x01(\tB\x03\xe0A\x02R\bcategory\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"N\n" +
	"\x19DeleteExpressOrderRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x06userId\x12\x13\n" +
	"\x02id\x18\x02 \x01(\x03B\x03\xe0A\x02R\x02id\"Y\n" +
	"\x12SetOrderTagRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x06userId\x12\x13\n" +
	"\x02id\x18\x02 \x01(\x03B\x03\xe0A\x02R\x02id\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\"_\n" +
	"\x12FollowOrderRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x06userId\x12\x13\n" +
	"\x02id\x18\x02 \x01(\x03B\x03\xe0A\x02R\x02id\x12\x16\n" +
	"\x06follow\x18\x03 \x01(\bR\x06follow\"F\n" +
	"\x11ShareOrderRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x06userId\x12\x13\n" +
	"\x02id\x18\x02 \x01(\x03B\x03\xe0A\x02R\x02id\".\n" +
	"\x0fShareOrderReply\x12\x1b\n" +
	"\tshare_url\x18\x01 \x01(\tR\bshareUrl\"\x96\v\n" +
	"\x11ExpressOrderReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_no\x18\x03 \x01(\tR\aorderNo\x12\x1d\n" +
	"\n" +
	"express_no\x18\x04 \x01(\tR\texpressNo\x12\x1f\n" +
	"\vsender_name\x18\x05 \x01(\tR\n" +
	"senderName\x12!\n" +
	"\fsender_phone\x18\x06 \x01(\tR\vsenderPhone\x12'\n" +
	"\x0fsender_province\x18\a \x01(\tR\x0esenderProvince\x12\x1f\n" +
	"\vsender_city\x18\b \x01(\tR\n" +
	"senderCity\x12'\n" +
	"\x0fsender_district\x18\t \x01(\tR\x0esenderDistrict\x12#\n" +
	"\rsender_detail\x18\n" +
	" \x01(\tR\fsenderDetail\x12#\n" +
	"\rreceiver_name\x18\v \x01(\tR\freceiverName\x12%\n" +
	"\x0ereceiver_phone\x18\f \x01(\tR\rreceiverPhone\x12+\n" +
	"\x11receiver_province\x18\r \x01(\tR\x10receiverProvince\x12#\n" +
	"\rreceiver_city\x18\x0e \x01(\tR\freceiverCity\x12+\n" +
	"\x11receiver_district\x18\x0f \x01(\tR\x10receiverDistrict\x12'\n" +
	"\x0freceiver_detail\x18\x10 \x01(\tR\x0ereceiverDetail\x12\x16\n" +
	"\x06weight\x18\x11 \x01(\x01R\x06weight\x12\x16\n" +
	"\x06length\x18\x12 \x01(\x05R\x06length\x12\x14\n" +
	"\x05width\x18\x13 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x14 \x01(\x05R\x06height\x12!\n" +
	"\fbase_freight\x18\x15 \x01(\x01R\vbaseFreight\x12\x1d\n" +
	"\n" +
	"insure_fee\x18\x16 \x01(\x01R\tinsureFee\x12#\n" +
	"\rtotal_freight\x18\x17 \x01(\x01R\ftotalFreight\x128\n" +
	"\fchannel_code\x18\x18 \x01(\x0e2\x15.order.v3.ChannelCodeR\vchannelCode\x12\x1b\n" +
	"\tlocker_id\x18\x19 \x01(\x03R\blockerId\x12\x19\n" +
	"\bbox_type\x18\x1a \x01(\tR\aboxType\x12(\n" +
	"\x10service_point_id\x18\x1b \x01(\x03R\x0eservicePointId\x12\x1f\n" +
	"\vpickup_date\x18\x1c \x01(\tR\n" +
	"pickupDate\x12(\n" +
	"\x10pickup_slot_code\x18\x1d \x01(\tR\x0epickupSlotCode\x12>\n" +
	"\x0epayment_method\x18\x1e \x01(\x0e2\x17.order.v3.PaymentMethodR\rpaymentMethod\x12>\n" +
	"\x0epayment_status\x18\x1f \x01(\x0e2\x17.order.v3.PaymentStatusR\rpaymentStatus\x12-\n" +
	"\x12privacy_protection\x18  \x01(\bR\x11privacyProtection\x12-\n" +
	"\x06status\x18! \x01(\x0e2\x15.order.v3.OrderStatusR\x06status\x12\x10\n" +
	"\x03tag\x18\" \x01(\tR\x03tag\x12\x1f\n" +
	"\vis_followed\x18# \x01(\bR\n" +
	"isFollowed\x12\x1b\n" +
	"\tshare_url\x18$ \x01(\tR\bshareUrl\x129\n" +
	"\n" +
	"created_at\x18% \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18& \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8f\x01\n" +
	"\x0fExpressOrderSet\x123\n" +
	"\x06orders\x18\x01 \x03(\v2\x1b.order.v3.ExpressOrderReplyR\x06orders\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken*e\n" +
	"\rPaymentMethod\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"SENDER_PAY\x10\x01\x12\x10\n" +
	"\fRECEIVER_PAY\x10\x02\x12\x12\n" +
	"\x0eMONTHLY_SETTLE\x10\x03*S\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\b\n" +
	"\x04PAID\x10\x02\x12\v\n" +
	"\aEXPIRED\x10\x03*\xac\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0ePENDING_PICKUP\x10\x01\x12\f\n" +
	"\bACCEPTED\x10\x02\x12\x13\n" +
	"\x0fAWAITING_PICKUP\x10\x03\x12\r\n" +
	"\tPICKED_UP\x10\x04\x12\x0e\n" +
	"\n" +
	"IN_TRANSIT\x10\x05\x12\x0e\n" +
	"\n" +
	"DELIVERING\x10\x06\x12\n" +
	"\n" +
	"\x06SIGNED\x10\a\x12\r\n" +
	"\tCANCELLED\x10\b*f\n" +
	"\vChannelCode\x12\x17\n" +
	"\x13CHANNEL_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vDOOR_PICKUP\x10\x01\x12\n" +
	"\n" +
	"\x06LOCKER\x10\x02\x12\x0e\n" +
	"\n" +
	"SF_STATION\x10\x03\x12\x11\n" +
	"\rPARTNER_STORE\x10\x042\x82\a\n" +
	"\fOrderService\x12t\n" +
	"\x12CreateExpressOrder\x12#.order.v3.CreateExpressOrderRequest\x1a\x1b.order.v3.ExpressOrderReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/order/create\x12i\n" +
	"\x0fGetExpressOrder\x12 .order.v3.GetExpressOrderRequest\x1a\x1b.order.v3.ExpressOrderReply\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/order/{id}\x12c\n" +
	"\fSearchOrders\x12\x1d.order.v3.SearchOrdersRequest\x1a\x19.order.v3.ExpressOrderSet\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/order/search\x12\x80\x01\n" +
	"\x14ListOrdersByCategory\x12%.order.v3.ListOrdersByCategoryRequest\x1a\x19.order.v3.ExpressOrderSet\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/order/category/{category}\x12j\n" +
	"\x12DeleteExpressOrder\x12#.order.v3.DeleteExpressOrderRequest\x1a\x16.google.protobuf.Empty\"\x17\x82\xd3\xe4\x93\x02\x11*\x0f/api/order/{id}\x12h\n" +
	"\vSetOrderTag\x12\x1c.order.v3.SetOrderTagRequest\x1a\x1b.order.v3.ExpressOrderReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\x1a\x13/api/order/{id}/tag\x12k\n" +
	"\vFollowOrder\x12\x1c.order.v3.FollowOrderRequest\x1a\x1b.order.v3.ExpressOrderReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\x1a\x16/api/order/{id}/follow\x12f\n" +
	"\n" +
	"ShareOrder\x12\x1b.order.v3.ShareOrderRequest\x1a\x19.order.v3.ShareOrderReply\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/order/{id}/shareBO\n" +
	"\x19io.grpc.examples.order.v3B\n" +
	"OrderProtoP\x01Z$shunfeng-miniprogram/api/order/v3;v3b\x06proto3"

var (
	file_order_v3_order_proto_rawDescOnce sync.Once
	file_order_v3_order_proto_rawDescData []byte
)

func file_order_v3_order_proto_rawDescGZIP() []byte {
	file_order_v3_order_proto_rawDescOnce.Do(func() {
		file_order_v3_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_v3_order_proto_rawDesc), len(file_order_v3_order_proto_rawDesc)))
	})
	return file_order_v3_order_proto_rawDescData
}

var file_order_v3_order_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_order_v3_order_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_order_v3_order_proto_goTypes = []any{
	(PaymentMethod)(0),                  // 0: order.v3.PaymentMethod
	(PaymentStatus)(0),                  // 1: order.v3.PaymentStatus
	(OrderStatus)(0),                    // 2: order.v3.OrderStatus
	(ChannelCode)(0),                    // 3: order.v3.ChannelCode
	(*CreateExpressOrderRequest)(nil),   // 4: order.v3.CreateExpressOrderRequest
	(*GetExpressOrderRequest)(nil),      // 5: order.v3.GetExpressOrderRequest
	(*SearchOrdersRequest)(nil),         // 6: order.v3.SearchOrdersRequest
	(*ListOrdersByCategoryRequest)(nil), // 7: order.v3.ListOrdersByCategoryRequest
	(*DeleteExpressOrderRequest)(nil),   // 8: order.v3.DeleteExpressOrderRequest
	(*SetOrderTagRequest)(nil),          // 9: order.v3.SetOrderTagRequest
	(*FollowOrderRequest)(nil),          // 10: order.v3.FollowOrderRequest
	(*ShareOrderRequest)(nil),           // 11: order.v3.ShareOrderRequest
	(*ShareOrderReply)(nil),             // 12: order.v3.ShareOrderReply
	(*ExpressOrderReply)(nil),           // 13: order.v3.ExpressOrderReply
	(*ExpressOrderSet)(nil),             // 14: order.v3.ExpressOrderSet
	(*timestamppb.Timestamp)(nil),       // 15: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),               // 16: google.protobuf.Empty
}
var file_order_v3_order_proto_depIdxs = []int32{
	3,  // 0: order.v3.CreateExpressOrderRequest.channel_code:type_name -> order.v3.ChannelCode
	0,  // 1: order.v3.CreateExpressOrderRequest.payment_method:type_name -> order.v3.PaymentMethod
	3,  // 2: order.v3.ExpressOrderReply.channel_code:type_name -> order.v3.ChannelCode
	0,  // 3: order.v3.ExpressOrderReply.payment_method:type_name -> order.v3.PaymentMethod
	1,  // 4: order.v3.ExpressOrderReply.payment_status:type_name -> order.v3.PaymentStatus
	2,  // 5: order.v3.ExpressOrderReply.status:type_name -> order.v3.OrderStatus
	15, // 6: order.v3.ExpressOrderReply.created_at:type_name -> google.protobuf.Timestamp
	15, // 7: order.v3.ExpressOrderReply.updated_at:type_name -> google.protobuf.Timestamp
	13, // 8: order.v3.ExpressOrderSet.orders:type_name -> order.v3.ExpressOrderReply
	4,  // 9: order.v3.OrderService.CreateExpressOrder:input_type -> order.v3.CreateExpressOrderRequest
	5,  // 10: order.v3.OrderService.GetExpressOrder:input_type -> order.v3.GetExpressOrderRequest
	6,  // 11: order.v3.OrderService.SearchOrders:input_type -> order.v3.SearchOrdersRequest
	7,  // 12: order.v3.OrderService.ListOrdersByCategory:input_type -> order.v3.ListOrdersByCategoryRequest
	8,  // 13: order.v3.OrderService.DeleteExpressOrder:input_type -> order.v3.DeleteExpressOrderRequest
	9,  // 14: order.v3.OrderService.SetOrderTag:input_type -> order.v3.SetOrderTagRequest
	10, // 15: order.v3.OrderService.FollowOrder:input_type -> order.v3.FollowOrderRequest
	11, // 16: order.v3.OrderService.ShareOrder:input_type -> order.v3.ShareOrderRequest
	13, // 17: order.v3.OrderService.CreateExpressOrder:output_type -> order.v3.ExpressOrderReply
	13, // 18: order.v3.OrderService.GetExpressOrder:output_type -> order.v3.ExpressOrderReply
	14, // 19: order.v3.OrderService.SearchOrders:output_type -> order.v3.ExpressOrderSet
	14, // 20: order.v3.OrderService.ListOrdersByCategory:output_type -> order.v3.ExpressOrderSet
	16, // 21: order.v3.OrderService.DeleteExpressOrder:output_type -> google.protobuf.Empty
	13, // 22: order.v3.OrderService.SetOrderTag:output_type -> order.v3.ExpressOrderReply
	13, // 23: order.v3.OrderService.FollowOrder:output_type -> order.v3.ExpressOrderReply
	12, // 24: order.v3.OrderService.ShareOrder:output_type -> order.v3.ShareOrderReply
	17, // [17:25] is the sub-list for method output_type
	9,  // [9:17] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_order_v3_order_proto_init() }
func file_order_v3_order_proto_init() {
	if File_order_v3_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_v3_order_proto_rawDesc), len(file_order_v3_order_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_v3_order_proto_goTypes,
		DependencyIndexes: file_order_v3_order_proto_depIdxs,
		EnumInfos:         file_order_v3_order_proto_enumTypes,
		MessageInfos:      file_order_v3_order_proto_msgTypes,
	}.Build()
	File_order_v3_order_proto = out.File
	file_order_v3_order_proto_goTypes = nil
	file_order_v3_order_proto_depIdxs = nil
}
