// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: order/v3/order.proto

package v3

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderService_CreateExpressOrder_FullMethodName    = "/order.v3.OrderService/CreateExpressOrder"
	OrderService_GetExpressOrder_FullMethodName       = "/order.v3.OrderService/GetExpressOrder"
	OrderService_SearchOrders_FullMethodName          = "/order.v3.OrderService/SearchOrders"
	OrderService_ListOrdersByCategory_FullMethodName  = "/order.v3.OrderService/ListOrdersByCategory"
	OrderService_DeleteExpressOrder_FullMethodName    = "/order.v3.OrderService/DeleteExpressOrder"
	OrderService_SetOrderTag_FullMethodName           = "/order.v3.OrderService/SetOrderTag"
	OrderService_FollowOrder_FullMethodName           = "/order.v3.OrderService/FollowOrder"
	OrderService_ShareOrder_FullMethodName            = "/order.v3.OrderService/ShareOrder"
	OrderService_PayExpressOrder_FullMethodName       = "/order.v3.OrderService/PayExpressOrder"
	OrderService_HandlePaymentCallback_FullMethodName = "/order.v3.OrderService/HandlePaymentCallback"
)

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderServiceClient interface {
	// CreateExpressOrder 创建寄件订单
	CreateExpressOrder(ctx context.Context, in *CreateExpressOrderRequest, opts ...grpc.CallOption) (*ExpressOrderReply, error)
	// GetExpressOrder 获取订单详情
	GetExpressOrder(ctx context.Context, in *GetExpressOrderRequest, opts ...grpc.CallOption) (*ExpressOrderReply, error)
	// SearchOrders 搜索订单（按单号/姓名/手机号）
	SearchOrders(ctx context.Context, in *SearchOrdersRequest, opts ...grpc.CallOption) (*ExpressOrderSet, error)
	// ListOrdersByCategory 按分类查看订单（寄件/收件/关注/待支付）
	ListOrdersByCategory(ctx context.Context, in *ListOrdersByCategoryRequest, opts ...grpc.CallOption) (*ExpressOrderSet, error)
	// DeleteExpressOrder 删除订单记录（逻辑删除，弹窗确认由前端处理）
	DeleteExpressOrder(ctx context.Context, in *DeleteExpressOrderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// SetOrderTag 设置订单标签
	SetOrderTag(ctx context.Context, in *SetOrderTagRequest, opts ...grpc.CallOption) (*ExpressOrderReply, error)
	// FollowOrder 关注/取消关注订单
	FollowOrder(ctx context.Context, in *FollowOrderRequest, opts ...grpc.CallOption) (*ExpressOrderReply, error)
	// ShareOrder 生成物流分享链接
	ShareOrder(ctx context.Context, in *ShareOrderRequest, opts ...grpc.CallOption) (*ShareOrderReply, error)
	// PayExpressOrder 发起支付，返回支付链接
	PayExpressOrder(ctx context.Context, in *PayExpressOrderRequest, opts ...grpc.CallOption) (*PayExpressOrderReply, error)
	// HandlePaymentCallback 处理支付回调，更新支付状态
	HandlePaymentCallback(ctx context.Context, in *PaymentCallbackRequest, opts ...grpc.CallOption) (*PaymentCallbackReply, error)
}

type orderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceClient(cc grpc.ClientConnInterface) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) CreateExpressOrder(ctx context.Context, in *CreateExpressOrderRequest, opts ...grpc.CallOption) (*ExpressOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExpressOrderReply)
	err := c.cc.Invoke(ctx, OrderService_CreateExpressOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetExpressOrder(ctx context.Context, in *GetExpressOrderRequest, opts ...grpc.CallOption) (*ExpressOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExpressOrderReply)
	err := c.cc.Invoke(ctx, OrderService_GetExpressOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) SearchOrders(ctx context.Context, in *SearchOrdersRequest, opts ...grpc.CallOption) (*ExpressOrderSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExpressOrderSet)
	err := c.cc.Invoke(ctx, OrderService_SearchOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) ListOrdersByCategory(ctx context.Context, in *ListOrdersByCategoryRequest, opts ...grpc.CallOption) (*ExpressOrderSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExpressOrderSet)
	err := c.cc.Invoke(ctx, OrderService_ListOrdersByCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) DeleteExpressOrder(ctx context.Context, in *DeleteExpressOrderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, OrderService_DeleteExpressOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) SetOrderTag(ctx context.Context, in *SetOrderTagRequest, opts ...grpc.CallOption) (*ExpressOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExpressOrderReply)
	err := c.cc.Invoke(ctx, OrderService_SetOrderTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) FollowOrder(ctx context.Context, in *FollowOrderRequest, opts ...grpc.CallOption) (*ExpressOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExpressOrderReply)
	err := c.cc.Invoke(ctx, OrderService_FollowOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) ShareOrder(ctx context.Context, in *ShareOrderRequest, opts ...grpc.CallOption) (*ShareOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShareOrderReply)
	err := c.cc.Invoke(ctx, OrderService_ShareOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) PayExpressOrder(ctx context.Context, in *PayExpressOrderRequest, opts ...grpc.CallOption) (*PayExpressOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayExpressOrderReply)
	err := c.cc.Invoke(ctx, OrderService_PayExpressOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) HandlePaymentCallback(ctx context.Context, in *PaymentCallbackRequest, opts ...grpc.CallOption) (*PaymentCallbackReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentCallbackReply)
	err := c.cc.Invoke(ctx, OrderService_HandlePaymentCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
// All implementations must embed UnimplementedOrderServiceServer
// for forward compatibility.
type OrderServiceServer interface {
	// CreateExpressOrder 创建寄件订单
	CreateExpressOrder(context.Context, *CreateExpressOrderRequest) (*ExpressOrderReply, error)
	// GetExpressOrder 获取订单详情
	GetExpressOrder(context.Context, *GetExpressOrderRequest) (*ExpressOrderReply, error)
	// SearchOrders 搜索订单（按单号/姓名/手机号）
	SearchOrders(context.Context, *SearchOrdersRequest) (*ExpressOrderSet, error)
	// ListOrdersByCategory 按分类查看订单（寄件/收件/关注/待支付）
	ListOrdersByCategory(context.Context, *ListOrdersByCategoryRequest) (*ExpressOrderSet, error)
	// DeleteExpressOrder 删除订单记录（逻辑删除，弹窗确认由前端处理）
	DeleteExpressOrder(context.Context, *DeleteExpressOrderRequest) (*emptypb.Empty, error)
	// SetOrderTag 设置订单标签
	SetOrderTag(context.Context, *SetOrderTagRequest) (*ExpressOrderReply, error)
	// FollowOrder 关注/取消关注订单
	FollowOrder(context.Context, *FollowOrderRequest) (*ExpressOrderReply, error)
	// ShareOrder 生成物流分享链接
	ShareOrder(context.Context, *ShareOrderRequest) (*ShareOrderReply, error)
	// PayExpressOrder 发起支付，返回支付链接
	PayExpressOrder(context.Context, *PayExpressOrderRequest) (*PayExpressOrderReply, error)
	// HandlePaymentCallback 处理支付回调，更新支付状态
	HandlePaymentCallback(context.Context, *PaymentCallbackRequest) (*PaymentCallbackReply, error)
	mustEmbedUnimplementedOrderServiceServer()
}

// UnimplementedOrderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderServiceServer struct{}

func (UnimplementedOrderServiceServer) CreateExpressOrder(context.Context, *CreateExpressOrderRequest) (*ExpressOrderReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateExpressOrder not implemented")
}
func (UnimplementedOrderServiceServer) GetExpressOrder(context.Context, *GetExpressOrderRequest) (*ExpressOrderReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExpressOrder not implemented")
}
func (UnimplementedOrderServiceServer) SearchOrders(context.Context, *SearchOrdersRequest) (*ExpressOrderSet, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchOrders not implemented")
}
func (UnimplementedOrderServiceServer) ListOrdersByCategory(context.Context, *ListOrdersByCategoryRequest) (*ExpressOrderSet, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOrdersByCategory not implemented")
}
func (UnimplementedOrderServiceServer) DeleteExpressOrder(context.Context, *DeleteExpressOrderRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteExpressOrder not implemented")
}
func (UnimplementedOrderServiceServer) SetOrderTag(context.Context, *SetOrderTagRequest) (*ExpressOrderReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SetOrderTag not implemented")
}
func (UnimplementedOrderServiceServer) FollowOrder(context.Context, *FollowOrderRequest) (*ExpressOrderReply, error) {
	return nil, status.Error(codes.Unimplemented, "method FollowOrder not implemented")
}
func (UnimplementedOrderServiceServer) ShareOrder(context.Context, *ShareOrderRequest) (*ShareOrderReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ShareOrder not implemented")
}
func (UnimplementedOrderServiceServer) PayExpressOrder(context.Context, *PayExpressOrderRequest) (*PayExpressOrderReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PayExpressOrder not implemented")
}
func (UnimplementedOrderServiceServer) HandlePaymentCallback(context.Context, *PaymentCallbackRequest) (*PaymentCallbackReply, error) {
	return nil, status.Error(codes.Unimplemented, "method HandlePaymentCallback not implemented")
}
func (UnimplementedOrderServiceServer) mustEmbedUnimplementedOrderServiceServer() {}
func (UnimplementedOrderServiceServer) testEmbeddedByValue()                      {}

// UnsafeOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServiceServer will
// result in compilation errors.
type UnsafeOrderServiceServer interface {
	mustEmbedUnimplementedOrderServiceServer()
}

func RegisterOrderServiceServer(s grpc.ServiceRegistrar, srv OrderServiceServer) {
	// If the following call panics, it indicates UnimplementedOrderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderService_ServiceDesc, srv)
}

func _OrderService_CreateExpressOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExpressOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateExpressOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_CreateExpressOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateExpressOrder(ctx, req.(*CreateExpressOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetExpressOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExpressOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetExpressOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_GetExpressOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetExpressOrder(ctx, req.(*GetExpressOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_SearchOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).SearchOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_SearchOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).SearchOrders(ctx, req.(*SearchOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_ListOrdersByCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrdersByCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ListOrdersByCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_ListOrdersByCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ListOrdersByCategory(ctx, req.(*ListOrdersByCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_DeleteExpressOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteExpressOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).DeleteExpressOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_DeleteExpressOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).DeleteExpressOrder(ctx, req.(*DeleteExpressOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_SetOrderTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetOrderTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).SetOrderTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_SetOrderTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).SetOrderTag(ctx, req.(*SetOrderTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_FollowOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).FollowOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_FollowOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).FollowOrder(ctx, req.(*FollowOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_ShareOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ShareOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_ShareOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ShareOrder(ctx, req.(*ShareOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_PayExpressOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayExpressOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).PayExpressOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_PayExpressOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).PayExpressOrder(ctx, req.(*PayExpressOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_HandlePaymentCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).HandlePaymentCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_HandlePaymentCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).HandlePaymentCallback(ctx, req.(*PaymentCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderService_ServiceDesc is the grpc.ServiceDesc for OrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.v3.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateExpressOrder",
			Handler:    _OrderService_CreateExpressOrder_Handler,
		},
		{
			MethodName: "GetExpressOrder",
			Handler:    _OrderService_GetExpressOrder_Handler,
		},
		{
			MethodName: "SearchOrders",
			Handler:    _OrderService_SearchOrders_Handler,
		},
		{
			MethodName: "ListOrdersByCategory",
			Handler:    _OrderService_ListOrdersByCategory_Handler,
		},
		{
			MethodName: "DeleteExpressOrder",
			Handler:    _OrderService_DeleteExpressOrder_Handler,
		},
		{
			MethodName: "SetOrderTag",
			Handler:    _OrderService_SetOrderTag_Handler,
		},
		{
			MethodName: "FollowOrder",
			Handler:    _OrderService_FollowOrder_Handler,
		},
		{
			MethodName: "ShareOrder",
			Handler:    _OrderService_ShareOrder_Handler,
		},
		{
			MethodName: "PayExpressOrder",
			Handler:    _OrderService_PayExpressOrder_Handler,
		},
		{
			MethodName: "HandlePaymentCallback",
			Handler:    _OrderService_HandlePaymentCallback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order/v3/order.proto",
}
