// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: order/v3/order.proto

package v3

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationOrderServiceCreateExpressOrder = "/order.v3.OrderService/CreateExpressOrder"
const OperationOrderServiceDeleteExpressOrder = "/order.v3.OrderService/DeleteExpressOrder"
const OperationOrderServiceGetExpressOrder = "/order.v3.OrderService/GetExpressOrder"
const OperationOrderServiceListExpressOrders = "/order.v3.OrderService/ListExpressOrders"
const OperationOrderServiceUpdateExpressOrder = "/order.v3.OrderService/UpdateExpressOrder"

type OrderServiceHTTPServer interface {
	// CreateExpressOrder CreateExpressOrder 创建寄件订单。
	CreateExpressOrder(context.Context, *CreateExpressOrderRequest) (*ExpressOrder, error)
	// DeleteExpressOrder DeleteExpressOrder 删除寄件订单。
	DeleteExpressOrder(context.Context, *DeleteExpressOrderRequest) (*emptypb.Empty, error)
	// GetExpressOrder GetExpressOrder 根据订单编号获取订单详情。
	GetExpressOrder(context.Context, *GetExpressOrderRequest) (*ExpressOrder, error)
	// ListExpressOrders ListExpressOrders 列出当前用户的寄件订单。
	ListExpressOrders(context.Context, *ListExpressOrdersRequest) (*ExpressOrderSet, error)
	// UpdateExpressOrder UpdateExpressOrder 更新寄件订单（支持字段掩码局部更新）。
	UpdateExpressOrder(context.Context, *UpdateExpressOrderRequest) (*ExpressOrder, error)
}

func RegisterOrderServiceHTTPServer(s *http.Server, srv OrderServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/api/order/v3/express-orders", _OrderService_CreateExpressOrder0_HTTP_Handler(srv))
	r.Handle("GET", "/api/order/v3/express-orders/{order_no}", _OrderService_GetExpressOrder0_HTTP_Handler(srv))
	r.Handle("GET", "/api/order/v3/express-orders", _OrderService_ListExpressOrders0_HTTP_Handler(srv))
	r.Handle("PATCH", "/api/order/v3/express-orders/{order.order_no}", _OrderService_UpdateExpressOrder0_HTTP_Handler(srv))
	r.Handle("DELETE", "/api/order/v3/express-orders/{order_no}", _OrderService_DeleteExpressOrder0_HTTP_Handler(srv))
}

func _OrderService_CreateExpressOrder0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateExpressOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceCreateExpressOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateExpressOrder(ctx, req.(*CreateExpressOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExpressOrder)
		return ctx.Result(200, reply)
	}
}

func _OrderService_GetExpressOrder0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetExpressOrderRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceGetExpressOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetExpressOrder(ctx, req.(*GetExpressOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExpressOrder)
		return ctx.Result(200, reply)
	}
}

func _OrderService_ListExpressOrders0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListExpressOrdersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceListExpressOrders)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListExpressOrders(ctx, req.(*ListExpressOrdersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExpressOrderSet)
		return ctx.Result(200, reply)
	}
}

func _OrderService_UpdateExpressOrder0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateExpressOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceUpdateExpressOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateExpressOrder(ctx, req.(*UpdateExpressOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExpressOrder)
		return ctx.Result(200, reply)
	}
}

func _OrderService_DeleteExpressOrder0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteExpressOrderRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceDeleteExpressOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteExpressOrder(ctx, req.(*DeleteExpressOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type OrderServiceHTTPClient interface {
	// CreateExpressOrder CreateExpressOrder 创建寄件订单。
	CreateExpressOrder(ctx context.Context, req *CreateExpressOrderRequest, opts ...http.CallOption) (rsp *ExpressOrder, err error)
	// DeleteExpressOrder DeleteExpressOrder 删除寄件订单。
	DeleteExpressOrder(ctx context.Context, req *DeleteExpressOrderRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// GetExpressOrder GetExpressOrder 根据订单编号获取订单详情。
	GetExpressOrder(ctx context.Context, req *GetExpressOrderRequest, opts ...http.CallOption) (rsp *ExpressOrder, err error)
	// ListExpressOrders ListExpressOrders 列出当前用户的寄件订单。
	ListExpressOrders(ctx context.Context, req *ListExpressOrdersRequest, opts ...http.CallOption) (rsp *ExpressOrderSet, err error)
	// UpdateExpressOrder UpdateExpressOrder 更新寄件订单（支持字段掩码局部更新）。
	UpdateExpressOrder(ctx context.Context, req *UpdateExpressOrderRequest, opts ...http.CallOption) (rsp *ExpressOrder, err error)
}

type OrderServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewOrderServiceHTTPClient(client *http.Client) OrderServiceHTTPClient {
	return &OrderServiceHTTPClientImpl{client}
}

// CreateExpressOrder CreateExpressOrder 创建寄件订单。
func (c *OrderServiceHTTPClientImpl) CreateExpressOrder(ctx context.Context, in *CreateExpressOrderRequest, opts ...http.CallOption) (*ExpressOrder, error) {
	var out ExpressOrder
	pattern := "/api/order/v3/express-orders"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationOrderServiceCreateExpressOrder),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteExpressOrder DeleteExpressOrder 删除寄件订单。
func (c *OrderServiceHTTPClientImpl) DeleteExpressOrder(ctx context.Context, in *DeleteExpressOrderRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/order/v3/express-orders/{order_no}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationOrderServiceDeleteExpressOrder),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetExpressOrder GetExpressOrder 根据订单编号获取订单详情。
func (c *OrderServiceHTTPClientImpl) GetExpressOrder(ctx context.Context, in *GetExpressOrderRequest, opts ...http.CallOption) (*ExpressOrder, error) {
	var out ExpressOrder
	pattern := "/api/order/v3/express-orders/{order_no}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationOrderServiceGetExpressOrder),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListExpressOrders ListExpressOrders 列出当前用户的寄件订单。
func (c *OrderServiceHTTPClientImpl) ListExpressOrders(ctx context.Context, in *ListExpressOrdersRequest, opts ...http.CallOption) (*ExpressOrderSet, error) {
	var out ExpressOrderSet
	pattern := "/api/order/v3/express-orders"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationOrderServiceListExpressOrders),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateExpressOrder UpdateExpressOrder 更新寄件订单（支持字段掩码局部更新）。
func (c *OrderServiceHTTPClientImpl) UpdateExpressOrder(ctx context.Context, in *UpdateExpressOrderRequest, opts ...http.CallOption) (*ExpressOrder, error) {
	var out ExpressOrder
	pattern := "/api/order/v3/express-orders/{order.order_no}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationOrderServiceUpdateExpressOrder),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
