// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: order/v3/order.proto

package v3

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PackageItem 选用的包装材料及数量。
type PackageItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaterialId    int64                  `protobuf:"varint,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"` // 包装材料ID，对应 packaging_material 表的 ID（前端从下拉列表选择）
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`                       // 数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageItem) Reset() {
	*x = PackageItem{}
	mi := &file_order_v3_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageItem) ProtoMessage() {}

func (x *PackageItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_v3_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageItem.ProtoReflect.Descriptor instead.
func (*PackageItem) Descriptor() ([]byte, []int) {
	return file_order_v3_order_proto_rawDescGZIP(), []int{0}
}

func (x *PackageItem) GetMaterialId() int64 {
	if x != nil {
		return x.MaterialId
	}
	return 0
}

func (x *PackageItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// ExpressOrder 寄件订单资源。
type ExpressOrder struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNo          string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`                             // 内部订单号
	TrackingNo       string                 `protobuf:"bytes,3,opt,name=tracking_no,json=trackingNo,proto3" json:"tracking_no,omitempty"`                    // 快递运单号
	UserNo           string                 `protobuf:"bytes,4,opt,name=user_no,json=userNo,proto3" json:"user_no,omitempty"`                                // 关联用户编号
	ExpressCompany   string                 `protobuf:"bytes,5,opt,name=express_company,json=expressCompany,proto3" json:"express_company,omitempty"`        // 快递公司
	SenderName       string                 `protobuf:"bytes,6,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`                    // 寄件人姓名
	SenderPhone      string                 `protobuf:"bytes,7,opt,name=sender_phone,json=senderPhone,proto3" json:"sender_phone,omitempty"`                 // 寄件人电话
	SenderProvince   string                 `protobuf:"bytes,8,opt,name=sender_province,json=senderProvince,proto3" json:"sender_province,omitempty"`        // 寄件省
	SenderCity       string                 `protobuf:"bytes,9,opt,name=sender_city,json=senderCity,proto3" json:"sender_city,omitempty"`                    // 寄件市
	SenderDistrict   string                 `protobuf:"bytes,10,opt,name=sender_district,json=senderDistrict,proto3" json:"sender_district,omitempty"`       // 寄件区
	SenderAddress    string                 `protobuf:"bytes,11,opt,name=sender_address,json=senderAddress,proto3" json:"sender_address,omitempty"`          // 寄件详细地址
	ReceiverName     string                 `protobuf:"bytes,12,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`             // 收件人姓名
	ReceiverPhone    string                 `protobuf:"bytes,13,opt,name=receiver_phone,json=receiverPhone,proto3" json:"receiver_phone,omitempty"`          // 收件人电话
	ReceiverProvince string                 `protobuf:"bytes,14,opt,name=receiver_province,json=receiverProvince,proto3" json:"receiver_province,omitempty"` // 收件省
	ReceiverCity     string                 `protobuf:"bytes,15,opt,name=receiver_city,json=receiverCity,proto3" json:"receiver_city,omitempty"`             // 收件市
	ReceiverDistrict string                 `protobuf:"bytes,16,opt,name=receiver_district,json=receiverDistrict,proto3" json:"receiver_district,omitempty"` // 收件区
	ReceiverAddress  string                 `protobuf:"bytes,17,opt,name=receiver_address,json=receiverAddress,proto3" json:"receiver_address,omitempty"`    // 收件详细地址
	ItemName         string                 `protobuf:"bytes,18,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`                         // 物品名称
	ItemCategory     string                 `protobuf:"bytes,19,opt,name=item_category,json=itemCategory,proto3" json:"item_category,omitempty"`             // 物品分类
	ItemQuantity     int32                  `protobuf:"varint,20,opt,name=item_quantity,json=itemQuantity,proto3" json:"item_quantity,omitempty"`            // 物品数量
	Weight           float64                `protobuf:"fixed64,21,opt,name=weight,proto3" json:"weight,omitempty"`                                           // 重量(kg)
	Length           float64                `protobuf:"fixed64,22,opt,name=length,proto3" json:"length,omitempty"`                                           // 长(cm)
	Width            float64                `protobuf:"fixed64,23,opt,name=width,proto3" json:"width,omitempty"`                                             // 宽(cm)
	Height           float64                `protobuf:"fixed64,24,opt,name=height,proto3" json:"height,omitempty"`                                           // 高(cm)
	DeclaredValue    float64                `protobuf:"fixed64,25,opt,name=declared_value,json=declaredValue,proto3" json:"declared_value,omitempty"`        // 申报价值
	IsFragile        bool                   `protobuf:"varint,26,opt,name=is_fragile,json=isFragile,proto3" json:"is_fragile,omitempty"`                     // 是否易碎
	IsBattery        bool                   `protobuf:"varint,27,opt,name=is_battery,json=isBattery,proto3" json:"is_battery,omitempty"`                     // 是否含电池
	FreightFee       float64                `protobuf:"fixed64,28,opt,name=freight_fee,json=freightFee,proto3" json:"freight_fee,omitempty"`                 // 基础运费
	InsuranceFee     float64                `protobuf:"fixed64,29,opt,name=insurance_fee,json=insuranceFee,proto3" json:"insurance_fee,omitempty"`           // 保价费
	PackageFee       float64                `protobuf:"fixed64,30,opt,name=package_fee,json=packageFee,proto3" json:"package_fee,omitempty"`                 // 打包费
	TotalFee         float64                `protobuf:"fixed64,31,opt,name=total_fee,json=totalFee,proto3" json:"total_fee,omitempty"`                       // 总费用
	PayMethod        string                 `protobuf:"bytes,32,opt,name=pay_method,json=payMethod,proto3" json:"pay_method,omitempty"`                      // 支付方式
	PayStatus        string                 `protobuf:"bytes,33,opt,name=pay_status,json=payStatus,proto3" json:"pay_status,omitempty"`                      // 支付状态
	OrderStatus      string                 `protobuf:"bytes,34,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`                // 订单状态
	PickupTime       *timestamppb.Timestamp `protobuf:"bytes,35,opt,name=pickup_time,json=pickupTime,proto3" json:"pickup_time,omitempty"`                   // 揽收时间
	DeliveredTime    *timestamppb.Timestamp `protobuf:"bytes,36,opt,name=delivered_time,json=deliveredTime,proto3" json:"delivered_time,omitempty"`          // 签收时间
	SignedBy         string                 `protobuf:"bytes,37,opt,name=signed_by,json=signedBy,proto3" json:"signed_by,omitempty"`                         // 签收人
	Remark           string                 `protobuf:"bytes,38,opt,name=remark,proto3" json:"remark,omitempty"`                                             // 备注
	Packages         []*PackageItem         `protobuf:"bytes,41,rep,name=packages,proto3" json:"packages,omitempty"`                                         // 选用包装材料及数量
	PackageDetail    string                 `protobuf:"bytes,42,opt,name=package_detail,json=packageDetail,proto3" json:"package_detail,omitempty"`          // 费用计算过程(JSON)
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,39,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,40,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExpressOrder) Reset() {
	*x = ExpressOrder{}
	mi := &file_order_v3_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpressOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpressOrder) ProtoMessage() {}

func (x *ExpressOrder) ProtoReflect() protoreflect.Message {
	mi := &file_order_v3_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpressOrder.ProtoReflect.Descriptor instead.
func (*ExpressOrder) Descriptor() ([]byte, []int) {
	return file_order_v3_order_proto_rawDescGZIP(), []int{1}
}

func (x *ExpressOrder) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExpressOrder) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *ExpressOrder) GetTrackingNo() string {
	if x != nil {
		return x.TrackingNo
	}
	return ""
}

func (x *ExpressOrder) GetUserNo() string {
	if x != nil {
		return x.UserNo
	}
	return ""
}

func (x *ExpressOrder) GetExpressCompany() string {
	if x != nil {
		return x.ExpressCompany
	}
	return ""
}

func (x *ExpressOrder) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *ExpressOrder) GetSenderPhone() string {
	if x != nil {
		return x.SenderPhone
	}
	return ""
}

func (x *ExpressOrder) GetSenderProvince() string {
	if x != nil {
		return x.SenderProvince
	}
	return ""
}

func (x *ExpressOrder) GetSenderCity() string {
	if x != nil {
		return x.SenderCity
	}
	return ""
}

func (x *ExpressOrder) GetSenderDistrict() string {
	if x != nil {
		return x.SenderDistrict
	}
	return ""
}

func (x *ExpressOrder) GetSenderAddress() string {
	if x != nil {
		return x.SenderAddress
	}
	return ""
}

func (x *ExpressOrder) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *ExpressOrder) GetReceiverPhone() string {
	if x != nil {
		return x.ReceiverPhone
	}
	return ""
}

func (x *ExpressOrder) GetReceiverProvince() string {
	if x != nil {
		return x.ReceiverProvince
	}
	return ""
}

func (x *ExpressOrder) GetReceiverCity() string {
	if x != nil {
		return x.ReceiverCity
	}
	return ""
}

func (x *ExpressOrder) GetReceiverDistrict() string {
	if x != nil {
		return x.ReceiverDistrict
	}
	return ""
}

func (x *ExpressOrder) GetReceiverAddress() string {
	if x != nil {
		return x.ReceiverAddress
	}
	return ""
}

func (x *ExpressOrder) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *ExpressOrder) GetItemCategory() string {
	if x != nil {
		return x.ItemCategory
	}
	return ""
}

func (x *ExpressOrder) GetItemQuantity() int32 {
	if x != nil {
		return x.ItemQuantity
	}
	return 0
}

func (x *ExpressOrder) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ExpressOrder) GetLength() float64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *ExpressOrder) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ExpressOrder) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ExpressOrder) GetDeclaredValue() float64 {
	if x != nil {
		return x.DeclaredValue
	}
	return 0
}

func (x *ExpressOrder) GetIsFragile() bool {
	if x != nil {
		return x.IsFragile
	}
	return false
}

func (x *ExpressOrder) GetIsBattery() bool {
	if x != nil {
		return x.IsBattery
	}
	return false
}

func (x *ExpressOrder) GetFreightFee() float64 {
	if x != nil {
		return x.FreightFee
	}
	return 0
}

func (x *ExpressOrder) GetInsuranceFee() float64 {
	if x != nil {
		return x.InsuranceFee
	}
	return 0
}

func (x *ExpressOrder) GetPackageFee() float64 {
	if x != nil {
		return x.PackageFee
	}
	return 0
}

func (x *ExpressOrder) GetTotalFee() float64 {
	if x != nil {
		return x.TotalFee
	}
	return 0
}

func (x *ExpressOrder) GetPayMethod() string {
	if x != nil {
		return x.PayMethod
	}
	return ""
}

func (x *ExpressOrder) GetPayStatus() string {
	if x != nil {
		return x.PayStatus
	}
	return ""
}

func (x *ExpressOrder) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

func (x *ExpressOrder) GetPickupTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PickupTime
	}
	return nil
}

func (x *ExpressOrder) GetDeliveredTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveredTime
	}
	return nil
}

func (x *ExpressOrder) GetSignedBy() string {
	if x != nil {
		return x.SignedBy
	}
	return ""
}

func (x *ExpressOrder) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *ExpressOrder) GetPackages() []*PackageItem {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *ExpressOrder) GetPackageDetail() string {
	if x != nil {
		return x.PackageDetail
	}
	return ""
}

func (x *ExpressOrder) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ExpressOrder) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateExpressOrderRequest 创建订单请求。
type CreateExpressOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *ExpressOrder          `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExpressOrderRequest) Reset() {
	*x = CreateExpressOrderRequest{}
	mi := &file_order_v3_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExpressOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExpressOrderRequest) ProtoMessage() {}

func (x *CreateExpressOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v3_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExpressOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateExpressOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v3_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateExpressOrderRequest) GetOrder() *ExpressOrder {
	if x != nil {
		return x.Order
	}
	return nil
}

// GetExpressOrderRequest 获取订单请求。
type GetExpressOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExpressOrderRequest) Reset() {
	*x = GetExpressOrderRequest{}
	mi := &file_order_v3_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpressOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpressOrderRequest) ProtoMessage() {}

func (x *GetExpressOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v3_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpressOrderRequest.ProtoReflect.Descriptor instead.
func (*GetExpressOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v3_order_proto_rawDescGZIP(), []int{3}
}

func (x *GetExpressOrderRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

// ListExpressOrdersRequest 列表订单请求。
type ListExpressOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserNo        string                 `protobuf:"bytes,1,opt,name=user_no,json=userNo,proto3" json:"user_no,omitempty"`
	OrderStatus   string                 `protobuf:"bytes,2,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"` // 可选：按订单状态过滤
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExpressOrdersRequest) Reset() {
	*x = ListExpressOrdersRequest{}
	mi := &file_order_v3_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExpressOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExpressOrdersRequest) ProtoMessage() {}

func (x *ListExpressOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v3_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExpressOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListExpressOrdersRequest) Descriptor() ([]byte, []int) {
	return file_order_v3_order_proto_rawDescGZIP(), []int{4}
}

func (x *ListExpressOrdersRequest) GetUserNo() string {
	if x != nil {
		return x.UserNo
	}
	return ""
}

func (x *ListExpressOrdersRequest) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

func (x *ListExpressOrdersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListExpressOrdersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ExpressOrderSet 订单列表响应。
type ExpressOrderSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*ExpressOrder        `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	NextPageToken string                 `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpressOrderSet) Reset() {
	*x = ExpressOrderSet{}
	mi := &file_order_v3_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpressOrderSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpressOrderSet) ProtoMessage() {}

func (x *ExpressOrderSet) ProtoReflect() protoreflect.Message {
	mi := &file_order_v3_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpressOrderSet.ProtoReflect.Descriptor instead.
func (*ExpressOrderSet) Descriptor() ([]byte, []int) {
	return file_order_v3_order_proto_rawDescGZIP(), []int{5}
}

func (x *ExpressOrderSet) GetOrders() []*ExpressOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ExpressOrderSet) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ExpressOrderSet) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// UpdateExpressOrderRequest 更新订单请求。
type UpdateExpressOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *ExpressOrder          `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExpressOrderRequest) Reset() {
	*x = UpdateExpressOrderRequest{}
	mi := &file_order_v3_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExpressOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExpressOrderRequest) ProtoMessage() {}

func (x *UpdateExpressOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v3_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExpressOrderRequest.ProtoReflect.Descriptor instead.
func (*UpdateExpressOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v3_order_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateExpressOrderRequest) GetOrder() *ExpressOrder {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *UpdateExpressOrderRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// DeleteExpressOrderRequest 删除订单请求。
type DeleteExpressOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExpressOrderRequest) Reset() {
	*x = DeleteExpressOrderRequest{}
	mi := &file_order_v3_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExpressOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExpressOrderRequest) ProtoMessage() {}

func (x *DeleteExpressOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v3_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExpressOrderRequest.ProtoReflect.Descriptor instead.
func (*DeleteExpressOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v3_order_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteExpressOrderRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

var File_order_v3_order_proto protoreflect.FileDescriptor

const file_order_v3_order_proto_rawDesc = "" +
	"\n" +
	"\x14order/v3/order.proto\x12\border.v3\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"J\n" +
	"\vPackageItem\x12\x1f\n" +
	"\vmaterial_id\x18\x01 \x01(\x03R\n" +
	"materialId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"\x84\f\n" +
	"\fExpressOrder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x1f\n" +
	"\vtracking_no\x18\x03 \x01(\tR\n" +
	"trackingNo\x12\x17\n" +
	"\auser_no\x18\x04 \x01(\tR\x06userNo\x12'\n" +
	"\x0fexpress_company\x18\x05 \x01(\tR\x0eexpressCompany\x12\x1f\n" +
	"\vsender_name\x18\x06 \x01(\tR\n" +
	"senderName\x12!\n" +
	"\fsender_phone\x18\a \x01(\tR\vsenderPhone\x12'\n" +
	"\x0fsender_province\x18\b \x01(\tR\x0esenderProvince\x12\x1f\n" +
	"\vsender_city\x18\t \x01(\tR\n" +
	"senderCity\x12'\n" +
	"\x0fsender_district\x18\n" +
	" \x01(\tR\x0esenderDistrict\x12%\n" +
	"\x0esender_address\x18\v \x01(\tR\rsenderAddress\x12#\n" +
	"\rreceiver_name\x18\f \x01(\tR\freceiverName\x12%\n" +
	"\x0ereceiver_phone\x18\r \x01(\tR\rreceiverPhone\x12+\n" +
	"\x11receiver_province\x18\x0e \x01(\tR\x10receiverProvince\x12#\n" +
	"\rreceiver_city\x18\x0f \x01(\tR\freceiverCity\x12+\n" +
	"\x11receiver_district\x18\x10 \x01(\tR\x10receiverDistrict\x12)\n" +
	"\x10receiver_address\x18\x11 \x01(\tR\x0freceiverAddress\x12\x1b\n" +
	"\titem_name\x18\x12 \x01(\tR\bitemName\x12#\n" +
	"\ritem_category\x18\x13 \x01(\tR\fitemCategory\x12#\n" +
	"\ritem_quantity\x18\x14 \x01(\x05R\fitemQuantity\x12\x16\n" +
	"\x06weight\x18\x15 \x01(\x01R\x06weight\x12\x16\n" +
	"\x06length\x18\x16 \x01(\x01R\x06length\x12\x14\n" +
	"\x05width\x18\x17 \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\x18 \x01(\x01R\x06height\x12%\n" +
	"\x0edeclared_value\x18\x19 \x01(\x01R\rdeclaredValue\x12\x1d\n" +
	"\n" +
	"is_fragile\x18\x1a \x01(\bR\tisFragile\x12\x1d\n" +
	"\n" +
	"is_battery\x18\x1b \x01(\bR\tisBattery\x12\x1f\n" +
	"\vfreight_fee\x18\x1c \x01(\x01R\n" +
	"freightFee\x12#\n" +
	"\rinsurance_fee\x18\x1d \x01(\x01R\finsuranceFee\x12\x1f\n" +
	"\vpackage_fee\x18\x1e \x01(\x01R\n" +
	"packageFee\x12\x1b\n" +
	"\ttotal_fee\x18\x1f \x01(\x01R\btotalFee\x12\x1d\n" +
	"\n" +
	"pay_method\x18  \x01(\tR\tpayMethod\x12\x1d\n" +
	"\n" +
	"pay_status\x18! \x01(\tR\tpayStatus\x12!\n" +
	"\forder_status\x18\" \x01(\tR\vorderStatus\x12;\n" +
	"\vpickup_time\x18# \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"pickupTime\x12A\n" +
	"\x0edelivered_time\x18$ \x01(\v2\x1a.google.protobuf.TimestampR\rdeliveredTime\x12\x1b\n" +
	"\tsigned_by\x18% \x01(\tR\bsignedBy\x12\x16\n" +
	"\x06remark\x18& \x01(\tR\x06remark\x121\n" +
	"\bpackages\x18) \x03(\v2\x15.order.v3.PackageItemR\bpackages\x12%\n" +
	"\x0epackage_detail\x18* \x01(\tR\rpackageDetail\x129\n" +
	"\n" +
	"created_at\x18' \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18( \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"N\n" +
	"\x19CreateExpressOrderRequest\x121\n" +
	"\x05order\x18\x01 \x01(\v2\x16.order.v3.ExpressOrderB\x03\xe0A\x02R\x05order\"8\n" +
	"\x16GetExpressOrderRequest\x12\x1e\n" +
	"\border_no\x18\x01 \x01(\tB\x03\xe0A\x02R\aorderNo\"\x97\x01\n" +
	"\x18ListExpressOrdersRequest\x12\x1c\n" +
	"\auser_no\x18\x01 \x01(\tB\x03\xe0A\x02R\x06userNo\x12!\n" +
	"\forder_status\x18\x02 \x01(\tR\vorderStatus\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\x8a\x01\n" +
	"\x0fExpressOrderSet\x12.\n" +
	"\x06orders\x18\x01 \x03(\v2\x16.order.v3.ExpressOrderR\x06orders\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken\"\x8b\x01\n" +
	"\x19UpdateExpressOrderRequest\x121\n" +
	"\x05order\x18\x01 \x01(\v2\x16.order.v3.ExpressOrderB\x03\xe0A\x02R\x05order\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\";\n" +
	"\x19DeleteExpressOrderRequest\x12\x1e\n" +
	"\border_no\x18\x01 \x01(\tB\x03\xe0A\x02R\aorderNo2\x95\x05\n" +
	"\fOrderService\x12z\n" +
	"\x12CreateExpressOrder\x12#.order.v3.CreateExpressOrderRequest\x1a\x16.order.v3.ExpressOrder\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/order/v3/express-orders\x12|\n" +
	"\x0fGetExpressOrder\x12 .order.v3.GetExpressOrderRequest\x1a\x16.order.v3.ExpressOrder\"/\x82\xd3\xe4\x93\x02)\x12'/api/order/v3/express-orders/{order_no}\x12x\n" +
	"\x11ListExpressOrders\x12\".order.v3.ListExpressOrdersRequest\x1a\x19.order.v3.ExpressOrderSet\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/order/v3/express-orders\x12\x8b\x01\n" +
	"\x12UpdateExpressOrder\x12#.order.v3.UpdateExpressOrderRequest\x1a\x16.order.v3.ExpressOrder\"8\x82\xd3\xe4\x93\x022:\x01*2-/api/order/v3/express-orders/{order.order_no}\x12\x82\x01\n" +
	"\x12DeleteExpressOrder\x12#.order.v3.DeleteExpressOrderRequest\x1a\x16.google.protobuf.Empty\"/\x82\xd3\xe4\x93\x02)*'/api/order/v3/express-orders/{order_no}BO\n" +
	"\x19io.grpc.examples.order.v3B\n" +
	"OrderProtoP\x01Z$shunfeng-miniprogram/api/order/v3;v3b\x06proto3"

var (
	file_order_v3_order_proto_rawDescOnce sync.Once
	file_order_v3_order_proto_rawDescData []byte
)

func file_order_v3_order_proto_rawDescGZIP() []byte {
	file_order_v3_order_proto_rawDescOnce.Do(func() {
		file_order_v3_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_v3_order_proto_rawDesc), len(file_order_v3_order_proto_rawDesc)))
	})
	return file_order_v3_order_proto_rawDescData
}

var file_order_v3_order_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_order_v3_order_proto_goTypes = []any{
	(*PackageItem)(nil),               // 0: order.v3.PackageItem
	(*ExpressOrder)(nil),              // 1: order.v3.ExpressOrder
	(*CreateExpressOrderRequest)(nil), // 2: order.v3.CreateExpressOrderRequest
	(*GetExpressOrderRequest)(nil),    // 3: order.v3.GetExpressOrderRequest
	(*ListExpressOrdersRequest)(nil),  // 4: order.v3.ListExpressOrdersRequest
	(*ExpressOrderSet)(nil),           // 5: order.v3.ExpressOrderSet
	(*UpdateExpressOrderRequest)(nil), // 6: order.v3.UpdateExpressOrderRequest
	(*DeleteExpressOrderRequest)(nil), // 7: order.v3.DeleteExpressOrderRequest
	(*timestamppb.Timestamp)(nil),     // 8: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),     // 9: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),             // 10: google.protobuf.Empty
}
var file_order_v3_order_proto_depIdxs = []int32{
	8,  // 0: order.v3.ExpressOrder.pickup_time:type_name -> google.protobuf.Timestamp
	8,  // 1: order.v3.ExpressOrder.delivered_time:type_name -> google.protobuf.Timestamp
	0,  // 2: order.v3.ExpressOrder.packages:type_name -> order.v3.PackageItem
	8,  // 3: order.v3.ExpressOrder.created_at:type_name -> google.protobuf.Timestamp
	8,  // 4: order.v3.ExpressOrder.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 5: order.v3.CreateExpressOrderRequest.order:type_name -> order.v3.ExpressOrder
	1,  // 6: order.v3.ExpressOrderSet.orders:type_name -> order.v3.ExpressOrder
	1,  // 7: order.v3.UpdateExpressOrderRequest.order:type_name -> order.v3.ExpressOrder
	9,  // 8: order.v3.UpdateExpressOrderRequest.update_mask:type_name -> google.protobuf.FieldMask
	2,  // 9: order.v3.OrderService.CreateExpressOrder:input_type -> order.v3.CreateExpressOrderRequest
	3,  // 10: order.v3.OrderService.GetExpressOrder:input_type -> order.v3.GetExpressOrderRequest
	4,  // 11: order.v3.OrderService.ListExpressOrders:input_type -> order.v3.ListExpressOrdersRequest
	6,  // 12: order.v3.OrderService.UpdateExpressOrder:input_type -> order.v3.UpdateExpressOrderRequest
	7,  // 13: order.v3.OrderService.DeleteExpressOrder:input_type -> order.v3.DeleteExpressOrderRequest
	1,  // 14: order.v3.OrderService.CreateExpressOrder:output_type -> order.v3.ExpressOrder
	1,  // 15: order.v3.OrderService.GetExpressOrder:output_type -> order.v3.ExpressOrder
	5,  // 16: order.v3.OrderService.ListExpressOrders:output_type -> order.v3.ExpressOrderSet
	1,  // 17: order.v3.OrderService.UpdateExpressOrder:output_type -> order.v3.ExpressOrder
	10, // 18: order.v3.OrderService.DeleteExpressOrder:output_type -> google.protobuf.Empty
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_order_v3_order_proto_init() }
func file_order_v3_order_proto_init() {
	if File_order_v3_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_v3_order_proto_rawDesc), len(file_order_v3_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_v3_order_proto_goTypes,
		DependencyIndexes: file_order_v3_order_proto_depIdxs,
		MessageInfos:      file_order_v3_order_proto_msgTypes,
	}.Build()
	File_order_v3_order_proto = out.File
	file_order_v3_order_proto_goTypes = nil
	file_order_v3_order_proto_depIdxs = nil
}
