// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: order/v3/packaging_material.proto

package v3

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationPackagingMaterialServiceCreatePackagingMaterial = "/order.v3.PackagingMaterialService/CreatePackagingMaterial"
const OperationPackagingMaterialServiceDeletePackagingMaterial = "/order.v3.PackagingMaterialService/DeletePackagingMaterial"
const OperationPackagingMaterialServiceListPackagingMaterials = "/order.v3.PackagingMaterialService/ListPackagingMaterials"
const OperationPackagingMaterialServiceUpdatePackagingMaterial = "/order.v3.PackagingMaterialService/UpdatePackagingMaterial"

type PackagingMaterialServiceHTTPServer interface {
	// CreatePackagingMaterial CreatePackagingMaterial 新增包装材料。
	CreatePackagingMaterial(context.Context, *CreatePackagingMaterialRequest) (*PackagingMaterial, error)
	// DeletePackagingMaterial DeletePackagingMaterial 删除包装材料。
	DeletePackagingMaterial(context.Context, *DeletePackagingMaterialRequest) (*emptypb.Empty, error)
	// ListPackagingMaterials ListPackagingMaterials 列出可选包装材料（前端下单时下拉选择）。
	ListPackagingMaterials(context.Context, *ListPackagingMaterialsRequest) (*PackagingMaterialSet, error)
	// UpdatePackagingMaterial UpdatePackagingMaterial 更新包装材料。
	UpdatePackagingMaterial(context.Context, *UpdatePackagingMaterialRequest) (*PackagingMaterial, error)
}

func RegisterPackagingMaterialServiceHTTPServer(s *http.Server, srv PackagingMaterialServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/api/order/v3/packaging-materials", _PackagingMaterialService_ListPackagingMaterials0_HTTP_Handler(srv))
	r.Handle("POST", "/api/order/v3/packaging-materials", _PackagingMaterialService_CreatePackagingMaterial0_HTTP_Handler(srv))
	r.Handle("PATCH", "/api/order/v3/packaging-materials/{material.id}", _PackagingMaterialService_UpdatePackagingMaterial0_HTTP_Handler(srv))
	r.Handle("DELETE", "/api/order/v3/packaging-materials/{id}", _PackagingMaterialService_DeletePackagingMaterial0_HTTP_Handler(srv))
}

func _PackagingMaterialService_ListPackagingMaterials0_HTTP_Handler(srv PackagingMaterialServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListPackagingMaterialsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPackagingMaterialServiceListPackagingMaterials)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPackagingMaterials(ctx, req.(*ListPackagingMaterialsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PackagingMaterialSet)
		return ctx.Result(200, reply)
	}
}

func _PackagingMaterialService_CreatePackagingMaterial0_HTTP_Handler(srv PackagingMaterialServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreatePackagingMaterialRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPackagingMaterialServiceCreatePackagingMaterial)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreatePackagingMaterial(ctx, req.(*CreatePackagingMaterialRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PackagingMaterial)
		return ctx.Result(200, reply)
	}
}

func _PackagingMaterialService_UpdatePackagingMaterial0_HTTP_Handler(srv PackagingMaterialServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdatePackagingMaterialRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPackagingMaterialServiceUpdatePackagingMaterial)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdatePackagingMaterial(ctx, req.(*UpdatePackagingMaterialRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PackagingMaterial)
		return ctx.Result(200, reply)
	}
}

func _PackagingMaterialService_DeletePackagingMaterial0_HTTP_Handler(srv PackagingMaterialServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeletePackagingMaterialRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPackagingMaterialServiceDeletePackagingMaterial)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeletePackagingMaterial(ctx, req.(*DeletePackagingMaterialRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type PackagingMaterialServiceHTTPClient interface {
	// CreatePackagingMaterial CreatePackagingMaterial 新增包装材料。
	CreatePackagingMaterial(ctx context.Context, req *CreatePackagingMaterialRequest, opts ...http.CallOption) (rsp *PackagingMaterial, err error)
	// DeletePackagingMaterial DeletePackagingMaterial 删除包装材料。
	DeletePackagingMaterial(ctx context.Context, req *DeletePackagingMaterialRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// ListPackagingMaterials ListPackagingMaterials 列出可选包装材料（前端下单时下拉选择）。
	ListPackagingMaterials(ctx context.Context, req *ListPackagingMaterialsRequest, opts ...http.CallOption) (rsp *PackagingMaterialSet, err error)
	// UpdatePackagingMaterial UpdatePackagingMaterial 更新包装材料。
	UpdatePackagingMaterial(ctx context.Context, req *UpdatePackagingMaterialRequest, opts ...http.CallOption) (rsp *PackagingMaterial, err error)
}

type PackagingMaterialServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewPackagingMaterialServiceHTTPClient(client *http.Client) PackagingMaterialServiceHTTPClient {
	return &PackagingMaterialServiceHTTPClientImpl{client}
}

// CreatePackagingMaterial CreatePackagingMaterial 新增包装材料。
func (c *PackagingMaterialServiceHTTPClientImpl) CreatePackagingMaterial(ctx context.Context, in *CreatePackagingMaterialRequest, opts ...http.CallOption) (*PackagingMaterial, error) {
	var out PackagingMaterial
	pattern := "/api/order/v3/packaging-materials"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationPackagingMaterialServiceCreatePackagingMaterial),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeletePackagingMaterial DeletePackagingMaterial 删除包装材料。
func (c *PackagingMaterialServiceHTTPClientImpl) DeletePackagingMaterial(ctx context.Context, in *DeletePackagingMaterialRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/order/v3/packaging-materials/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationPackagingMaterialServiceDeletePackagingMaterial),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListPackagingMaterials ListPackagingMaterials 列出可选包装材料（前端下单时下拉选择）。
func (c *PackagingMaterialServiceHTTPClientImpl) ListPackagingMaterials(ctx context.Context, in *ListPackagingMaterialsRequest, opts ...http.CallOption) (*PackagingMaterialSet, error) {
	var out PackagingMaterialSet
	pattern := "/api/order/v3/packaging-materials"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationPackagingMaterialServiceListPackagingMaterials),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdatePackagingMaterial UpdatePackagingMaterial 更新包装材料。
func (c *PackagingMaterialServiceHTTPClientImpl) UpdatePackagingMaterial(ctx context.Context, in *UpdatePackagingMaterialRequest, opts ...http.CallOption) (*PackagingMaterial, error) {
	var out PackagingMaterial
	pattern := "/api/order/v3/packaging-materials/{material.id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationPackagingMaterialServiceUpdatePackagingMaterial),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
