// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: order/v3/packaging_material.proto

package v3

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PackagingMaterialService_ListPackagingMaterials_FullMethodName  = "/order.v3.PackagingMaterialService/ListPackagingMaterials"
	PackagingMaterialService_CreatePackagingMaterial_FullMethodName = "/order.v3.PackagingMaterialService/CreatePackagingMaterial"
	PackagingMaterialService_UpdatePackagingMaterial_FullMethodName = "/order.v3.PackagingMaterialService/UpdatePackagingMaterial"
	PackagingMaterialService_DeletePackagingMaterial_FullMethodName = "/order.v3.PackagingMaterialService/DeletePackagingMaterial"
)

// PackagingMaterialServiceClient is the client API for PackagingMaterialService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PackagingMaterialService 包装材料服务，提供材料的增删改查与下单计费数据源。
type PackagingMaterialServiceClient interface {
	// ListPackagingMaterials 列出可选包装材料（前端下单时下拉选择）。
	ListPackagingMaterials(ctx context.Context, in *ListPackagingMaterialsRequest, opts ...grpc.CallOption) (*PackagingMaterialSet, error)
	// CreatePackagingMaterial 新增包装材料。
	CreatePackagingMaterial(ctx context.Context, in *CreatePackagingMaterialRequest, opts ...grpc.CallOption) (*PackagingMaterial, error)
	// UpdatePackagingMaterial 更新包装材料。
	UpdatePackagingMaterial(ctx context.Context, in *UpdatePackagingMaterialRequest, opts ...grpc.CallOption) (*PackagingMaterial, error)
	// DeletePackagingMaterial 删除包装材料。
	DeletePackagingMaterial(ctx context.Context, in *DeletePackagingMaterialRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type packagingMaterialServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPackagingMaterialServiceClient(cc grpc.ClientConnInterface) PackagingMaterialServiceClient {
	return &packagingMaterialServiceClient{cc}
}

func (c *packagingMaterialServiceClient) ListPackagingMaterials(ctx context.Context, in *ListPackagingMaterialsRequest, opts ...grpc.CallOption) (*PackagingMaterialSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PackagingMaterialSet)
	err := c.cc.Invoke(ctx, PackagingMaterialService_ListPackagingMaterials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packagingMaterialServiceClient) CreatePackagingMaterial(ctx context.Context, in *CreatePackagingMaterialRequest, opts ...grpc.CallOption) (*PackagingMaterial, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PackagingMaterial)
	err := c.cc.Invoke(ctx, PackagingMaterialService_CreatePackagingMaterial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packagingMaterialServiceClient) UpdatePackagingMaterial(ctx context.Context, in *UpdatePackagingMaterialRequest, opts ...grpc.CallOption) (*PackagingMaterial, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PackagingMaterial)
	err := c.cc.Invoke(ctx, PackagingMaterialService_UpdatePackagingMaterial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packagingMaterialServiceClient) DeletePackagingMaterial(ctx context.Context, in *DeletePackagingMaterialRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PackagingMaterialService_DeletePackagingMaterial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PackagingMaterialServiceServer is the server API for PackagingMaterialService service.
// All implementations must embed UnimplementedPackagingMaterialServiceServer
// for forward compatibility.
//
// PackagingMaterialService 包装材料服务，提供材料的增删改查与下单计费数据源。
type PackagingMaterialServiceServer interface {
	// ListPackagingMaterials 列出可选包装材料（前端下单时下拉选择）。
	ListPackagingMaterials(context.Context, *ListPackagingMaterialsRequest) (*PackagingMaterialSet, error)
	// CreatePackagingMaterial 新增包装材料。
	CreatePackagingMaterial(context.Context, *CreatePackagingMaterialRequest) (*PackagingMaterial, error)
	// UpdatePackagingMaterial 更新包装材料。
	UpdatePackagingMaterial(context.Context, *UpdatePackagingMaterialRequest) (*PackagingMaterial, error)
	// DeletePackagingMaterial 删除包装材料。
	DeletePackagingMaterial(context.Context, *DeletePackagingMaterialRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedPackagingMaterialServiceServer()
}

// UnimplementedPackagingMaterialServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPackagingMaterialServiceServer struct{}

func (UnimplementedPackagingMaterialServiceServer) ListPackagingMaterials(context.Context, *ListPackagingMaterialsRequest) (*PackagingMaterialSet, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPackagingMaterials not implemented")
}
func (UnimplementedPackagingMaterialServiceServer) CreatePackagingMaterial(context.Context, *CreatePackagingMaterialRequest) (*PackagingMaterial, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePackagingMaterial not implemented")
}
func (UnimplementedPackagingMaterialServiceServer) UpdatePackagingMaterial(context.Context, *UpdatePackagingMaterialRequest) (*PackagingMaterial, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePackagingMaterial not implemented")
}
func (UnimplementedPackagingMaterialServiceServer) DeletePackagingMaterial(context.Context, *DeletePackagingMaterialRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePackagingMaterial not implemented")
}
func (UnimplementedPackagingMaterialServiceServer) mustEmbedUnimplementedPackagingMaterialServiceServer() {
}
func (UnimplementedPackagingMaterialServiceServer) testEmbeddedByValue() {}

// UnsafePackagingMaterialServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PackagingMaterialServiceServer will
// result in compilation errors.
type UnsafePackagingMaterialServiceServer interface {
	mustEmbedUnimplementedPackagingMaterialServiceServer()
}

func RegisterPackagingMaterialServiceServer(s grpc.ServiceRegistrar, srv PackagingMaterialServiceServer) {
	// If the following call panics, it indicates UnimplementedPackagingMaterialServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PackagingMaterialService_ServiceDesc, srv)
}

func _PackagingMaterialService_ListPackagingMaterials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPackagingMaterialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackagingMaterialServiceServer).ListPackagingMaterials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackagingMaterialService_ListPackagingMaterials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackagingMaterialServiceServer).ListPackagingMaterials(ctx, req.(*ListPackagingMaterialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackagingMaterialService_CreatePackagingMaterial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePackagingMaterialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackagingMaterialServiceServer).CreatePackagingMaterial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackagingMaterialService_CreatePackagingMaterial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackagingMaterialServiceServer).CreatePackagingMaterial(ctx, req.(*CreatePackagingMaterialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackagingMaterialService_UpdatePackagingMaterial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePackagingMaterialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackagingMaterialServiceServer).UpdatePackagingMaterial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackagingMaterialService_UpdatePackagingMaterial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackagingMaterialServiceServer).UpdatePackagingMaterial(ctx, req.(*UpdatePackagingMaterialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackagingMaterialService_DeletePackagingMaterial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePackagingMaterialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackagingMaterialServiceServer).DeletePackagingMaterial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackagingMaterialService_DeletePackagingMaterial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackagingMaterialServiceServer).DeletePackagingMaterial(ctx, req.(*DeletePackagingMaterialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PackagingMaterialService_ServiceDesc is the grpc.ServiceDesc for PackagingMaterialService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PackagingMaterialService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.v3.PackagingMaterialService",
	HandlerType: (*PackagingMaterialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPackagingMaterials",
			Handler:    _PackagingMaterialService_ListPackagingMaterials_Handler,
		},
		{
			MethodName: "CreatePackagingMaterial",
			Handler:    _PackagingMaterialService_CreatePackagingMaterial_Handler,
		},
		{
			MethodName: "UpdatePackagingMaterial",
			Handler:    _PackagingMaterialService_UpdatePackagingMaterial_Handler,
		},
		{
			MethodName: "DeletePackagingMaterial",
			Handler:    _PackagingMaterialService_DeletePackagingMaterial_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order/v3/packaging_material.proto",
}
