// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: order/v3/packaging_material.proto

package v3

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PackagingMaterial 包装材料（打包费计费数据源）。
type PackagingMaterial struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                 // 主键
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                              // 材料名称（唯一）
	UnitPrice     float64                `protobuf:"fixed64,3,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"` // 单价（元）
	Unit          string                 `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`                              // 计价单位（个/卷/张/件）
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`                // 说明
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackagingMaterial) Reset() {
	*x = PackagingMaterial{}
	mi := &file_order_v3_packaging_material_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackagingMaterial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackagingMaterial) ProtoMessage() {}

func (x *PackagingMaterial) ProtoReflect() protoreflect.Message {
	mi := &file_order_v3_packaging_material_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackagingMaterial.ProtoReflect.Descriptor instead.
func (*PackagingMaterial) Descriptor() ([]byte, []int) {
	return file_order_v3_packaging_material_proto_rawDescGZIP(), []int{0}
}

func (x *PackagingMaterial) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PackagingMaterial) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PackagingMaterial) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *PackagingMaterial) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *PackagingMaterial) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PackagingMaterial) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PackagingMaterial) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ListPackagingMaterialsRequest 包装材料列表请求。
type ListPackagingMaterialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPackagingMaterialsRequest) Reset() {
	*x = ListPackagingMaterialsRequest{}
	mi := &file_order_v3_packaging_material_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPackagingMaterialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPackagingMaterialsRequest) ProtoMessage() {}

func (x *ListPackagingMaterialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v3_packaging_material_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPackagingMaterialsRequest.ProtoReflect.Descriptor instead.
func (*ListPackagingMaterialsRequest) Descriptor() ([]byte, []int) {
	return file_order_v3_packaging_material_proto_rawDescGZIP(), []int{1}
}

func (x *ListPackagingMaterialsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPackagingMaterialsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// PackagingMaterialSet 包装材料列表响应。
type PackagingMaterialSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Materials     []*PackagingMaterial   `protobuf:"bytes,1,rep,name=materials,proto3" json:"materials,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	NextPageToken string                 `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackagingMaterialSet) Reset() {
	*x = PackagingMaterialSet{}
	mi := &file_order_v3_packaging_material_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackagingMaterialSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackagingMaterialSet) ProtoMessage() {}

func (x *PackagingMaterialSet) ProtoReflect() protoreflect.Message {
	mi := &file_order_v3_packaging_material_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackagingMaterialSet.ProtoReflect.Descriptor instead.
func (*PackagingMaterialSet) Descriptor() ([]byte, []int) {
	return file_order_v3_packaging_material_proto_rawDescGZIP(), []int{2}
}

func (x *PackagingMaterialSet) GetMaterials() []*PackagingMaterial {
	if x != nil {
		return x.Materials
	}
	return nil
}

func (x *PackagingMaterialSet) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *PackagingMaterialSet) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// CreatePackagingMaterialRequest 创建包装材料请求。
type CreatePackagingMaterialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Material      *PackagingMaterial     `protobuf:"bytes,1,opt,name=material,proto3" json:"material,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePackagingMaterialRequest) Reset() {
	*x = CreatePackagingMaterialRequest{}
	mi := &file_order_v3_packaging_material_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePackagingMaterialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePackagingMaterialRequest) ProtoMessage() {}

func (x *CreatePackagingMaterialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v3_packaging_material_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePackagingMaterialRequest.ProtoReflect.Descriptor instead.
func (*CreatePackagingMaterialRequest) Descriptor() ([]byte, []int) {
	return file_order_v3_packaging_material_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePackagingMaterialRequest) GetMaterial() *PackagingMaterial {
	if x != nil {
		return x.Material
	}
	return nil
}

// UpdatePackagingMaterialRequest 更新包装材料请求。
type UpdatePackagingMaterialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Material      *PackagingMaterial     `protobuf:"bytes,1,opt,name=material,proto3" json:"material,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePackagingMaterialRequest) Reset() {
	*x = UpdatePackagingMaterialRequest{}
	mi := &file_order_v3_packaging_material_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePackagingMaterialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePackagingMaterialRequest) ProtoMessage() {}

func (x *UpdatePackagingMaterialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v3_packaging_material_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePackagingMaterialRequest.ProtoReflect.Descriptor instead.
func (*UpdatePackagingMaterialRequest) Descriptor() ([]byte, []int) {
	return file_order_v3_packaging_material_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePackagingMaterialRequest) GetMaterial() *PackagingMaterial {
	if x != nil {
		return x.Material
	}
	return nil
}

func (x *UpdatePackagingMaterialRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// DeletePackagingMaterialRequest 删除包装材料请求。
type DeletePackagingMaterialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePackagingMaterialRequest) Reset() {
	*x = DeletePackagingMaterialRequest{}
	mi := &file_order_v3_packaging_material_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePackagingMaterialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePackagingMaterialRequest) ProtoMessage() {}

func (x *DeletePackagingMaterialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v3_packaging_material_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePackagingMaterialRequest.ProtoReflect.Descriptor instead.
func (*DeletePackagingMaterialRequest) Descriptor() ([]byte, []int) {
	return file_order_v3_packaging_material_proto_rawDescGZIP(), []int{5}
}

func (x *DeletePackagingMaterialRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_order_v3_packaging_material_proto protoreflect.FileDescriptor

const file_order_v3_packaging_material_proto_rawDesc = "" +
	"\n" +
	"!order/v3/packaging_material.proto\x12\border.v3\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x82\x02\n" +
	"\x11PackagingMaterial\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x03 \x01(\x01R\tunitPrice\x12\x12\n" +
	"\x04unit\x18\x04 \x01(\tR\x04unit\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"[\n" +
	"\x1dListPackagingMaterialsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\x9a\x01\n" +
	"\x14PackagingMaterialSet\x129\n" +
	"\tmaterials\x18\x01 \x03(\v2\x1b.order.v3.PackagingMaterialR\tmaterials\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken\"^\n" +
	"\x1eCreatePackagingMaterialRequest\x12<\n" +
	"\bmaterial\x18\x01 \x01(\v2\x1b.order.v3.PackagingMaterialB\x03\xe0A\x02R\bmaterial\"\x9b\x01\n" +
	"\x1eUpdatePackagingMaterialRequest\x12<\n" +
	"\bmaterial\x18\x01 \x01(\v2\x1b.order.v3.PackagingMaterialB\x03\xe0A\x02R\bmaterial\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"5\n" +
	"\x1eDeletePackagingMaterialRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id2\xe7\x04\n" +
	"\x18PackagingMaterialService\x12\x8c\x01\n" +
	"\x16ListPackagingMaterials\x12'.order.v3.ListPackagingMaterialsRequest\x1a\x1e.order.v3.PackagingMaterialSet\")\x82\xd3\xe4\x93\x02#\x12!/api/order/v3/packaging-materials\x12\x8e\x01\n" +
	"\x17CreatePackagingMaterial\x12(.order.v3.CreatePackagingMaterialRequest\x1a\x1b.order.v3.PackagingMaterial\",\x82\xd3\xe4\x93\x02&:\x01*\"!/api/order/v3/packaging-materials\x12\x9c\x01\n" +
	"\x17UpdatePackagingMaterial\x12(.order.v3.UpdatePackagingMaterialRequest\x1a\x1b.order.v3.PackagingMaterial\":\x82\xd3\xe4\x93\x024:\x01*2//api/order/v3/packaging-materials/{material.id}\x12\x8b\x01\n" +
	"\x17DeletePackagingMaterial\x12(.order.v3.DeletePackagingMaterialRequest\x1a\x16.google.protobuf.Empty\".\x82\xd3\xe4\x93\x02(*&/api/order/v3/packaging-materials/{id}B[\n" +
	"\x19io.grpc.examples.order.v3B\x16PackagingMaterialProtoP\x01Z$shunfeng-miniprogram/api/order/v3;v3b\x06proto3"

var (
	file_order_v3_packaging_material_proto_rawDescOnce sync.Once
	file_order_v3_packaging_material_proto_rawDescData []byte
)

func file_order_v3_packaging_material_proto_rawDescGZIP() []byte {
	file_order_v3_packaging_material_proto_rawDescOnce.Do(func() {
		file_order_v3_packaging_material_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_v3_packaging_material_proto_rawDesc), len(file_order_v3_packaging_material_proto_rawDesc)))
	})
	return file_order_v3_packaging_material_proto_rawDescData
}

var file_order_v3_packaging_material_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_order_v3_packaging_material_proto_goTypes = []any{
	(*PackagingMaterial)(nil),              // 0: order.v3.PackagingMaterial
	(*ListPackagingMaterialsRequest)(nil),  // 1: order.v3.ListPackagingMaterialsRequest
	(*PackagingMaterialSet)(nil),           // 2: order.v3.PackagingMaterialSet
	(*CreatePackagingMaterialRequest)(nil), // 3: order.v3.CreatePackagingMaterialRequest
	(*UpdatePackagingMaterialRequest)(nil), // 4: order.v3.UpdatePackagingMaterialRequest
	(*DeletePackagingMaterialRequest)(nil), // 5: order.v3.DeletePackagingMaterialRequest
	(*timestamppb.Timestamp)(nil),          // 6: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),          // 7: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),                  // 8: google.protobuf.Empty
}
var file_order_v3_packaging_material_proto_depIdxs = []int32{
	6,  // 0: order.v3.PackagingMaterial.created_at:type_name -> google.protobuf.Timestamp
	6,  // 1: order.v3.PackagingMaterial.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: order.v3.PackagingMaterialSet.materials:type_name -> order.v3.PackagingMaterial
	0,  // 3: order.v3.CreatePackagingMaterialRequest.material:type_name -> order.v3.PackagingMaterial
	0,  // 4: order.v3.UpdatePackagingMaterialRequest.material:type_name -> order.v3.PackagingMaterial
	7,  // 5: order.v3.UpdatePackagingMaterialRequest.update_mask:type_name -> google.protobuf.FieldMask
	1,  // 6: order.v3.PackagingMaterialService.ListPackagingMaterials:input_type -> order.v3.ListPackagingMaterialsRequest
	3,  // 7: order.v3.PackagingMaterialService.CreatePackagingMaterial:input_type -> order.v3.CreatePackagingMaterialRequest
	4,  // 8: order.v3.PackagingMaterialService.UpdatePackagingMaterial:input_type -> order.v3.UpdatePackagingMaterialRequest
	5,  // 9: order.v3.PackagingMaterialService.DeletePackagingMaterial:input_type -> order.v3.DeletePackagingMaterialRequest
	2,  // 10: order.v3.PackagingMaterialService.ListPackagingMaterials:output_type -> order.v3.PackagingMaterialSet
	0,  // 11: order.v3.PackagingMaterialService.CreatePackagingMaterial:output_type -> order.v3.PackagingMaterial
	0,  // 12: order.v3.PackagingMaterialService.UpdatePackagingMaterial:output_type -> order.v3.PackagingMaterial
	8,  // 13: order.v3.PackagingMaterialService.DeletePackagingMaterial:output_type -> google.protobuf.Empty
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_order_v3_packaging_material_proto_init() }
func file_order_v3_packaging_material_proto_init() {
	if File_order_v3_packaging_material_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_v3_packaging_material_proto_rawDesc), len(file_order_v3_packaging_material_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_v3_packaging_material_proto_goTypes,
		DependencyIndexes: file_order_v3_packaging_material_proto_depIdxs,
		MessageInfos:      file_order_v3_packaging_material_proto_msgTypes,
	}.Build()
	File_order_v3_packaging_material_proto = out.File
	file_order_v3_packaging_material_proto_goTypes = nil
	file_order_v3_packaging_material_proto_depIdxs = nil
}
