server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    user: root
    password: mysql
    host: 115.190.225.153
    port: 3306
    database: express
  redis:
    addr: 115.190.225.153:6379
    password: "redis"
    db: 0
    read_timeout: 0.2s
    write_timeout: 0.2s
  elasticsearch:
    addr: http://115.190.225.153:9200
registry:
  nacos:
    addr: 115.190.225.153
    port: 8848
    namespace_id: public
    log_dir: /tmp/nacos/log
    cache_dir: /tmp/nacos/cache
    log_level: debug
    data_id: shunfeng-miniprogram
    group: DEFAULT_GROUP
