// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: shipping/v1/error_reason.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorReason enumerates all domain-specific error codes for the shipping
// service. HTTP/gRPC mappings follow the conventions in the global constraint
// document:
//   - INVALID_ARGUMENT / bad-request → 400
//   - UNAUTHORIZED                    → 40101
//   - FORBIDDEN (account banned)     → 40302
//   - NOT_FOUND                      → 404
//   - RESOURCE_OCCUPIED (concurrency)→ 40903
//   - RATE_LIMIT_EXCEEDED            → 429
//   - INTERNAL                       → 500
type ErrorReason int32

const (
	ErrorReason_SHIPPING_UNSPECIFIED ErrorReason = 0
	// The shipping channel requested is not available in the current region.
	ErrorReason_SHIPPING_CHANNEL_UNAVAILABLE ErrorReason = 1
	// The requested resource (locker, time slot, etc.) was not found.
	ErrorReason_SHIPPING_NOT_FOUND ErrorReason = 2
	// One or more request parameters are invalid or missing.
	ErrorReason_SHIPPING_INVALID_ARGUMENT ErrorReason = 3
	// The compartment type is incompatible with the parcel dimensions or weight.
	ErrorReason_SHIPPING_BOX_TYPE_MISMATCH ErrorReason = 4
	// No free compartments available in the selected locker.
	ErrorReason_SHIPPING_LOCKER_FULL ErrorReason = 5
	// No free compartments available for the requested box type.
	ErrorReason_SHIPPING_BOX_TYPE_FULL ErrorReason = 6
	// The selected time slot has been fully occupied by other users.
	ErrorReason_SHIPPING_SLOT_FULL ErrorReason = 7
	// Optimistic-lock conflict: the resource was updated by another request
	// before this one completed. The client should retry after refreshing
	// the resource state.
	ErrorReason_SHIPPING_RESOURCE_OCCUPIED ErrorReason = 8
	// The pickup date is out of the allowed range (today ~ day+2).
	ErrorReason_SHIPPING_PICKUP_DATE_OUT_OF_RANGE ErrorReason = 9
	// The requested channel does not support the supplied parameters
	// (e.g. pickup params for a locker channel).
	ErrorReason_SHIPPING_PARAMS_MISMATCH ErrorReason = 10
	// The user has exceeded the rate limit for this API (20 req/min per user
	// for locker / service-point queries).
	ErrorReason_SHIPPING_RATE_LIMIT_EXCEEDED ErrorReason = 11
	// Any other business-rule violation not covered above.
	ErrorReason_SHIPPING_BUSINESS_ERROR ErrorReason = 12
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:  "SHIPPING_UNSPECIFIED",
		1:  "SHIPPING_CHANNEL_UNAVAILABLE",
		2:  "SHIPPING_NOT_FOUND",
		3:  "SHIPPING_INVALID_ARGUMENT",
		4:  "SHIPPING_BOX_TYPE_MISMATCH",
		5:  "SHIPPING_LOCKER_FULL",
		6:  "SHIPPING_BOX_TYPE_FULL",
		7:  "SHIPPING_SLOT_FULL",
		8:  "SHIPPING_RESOURCE_OCCUPIED",
		9:  "SHIPPING_PICKUP_DATE_OUT_OF_RANGE",
		10: "SHIPPING_PARAMS_MISMATCH",
		11: "SHIPPING_RATE_LIMIT_EXCEEDED",
		12: "SHIPPING_BUSINESS_ERROR",
	}
	ErrorReason_value = map[string]int32{
		"SHIPPING_UNSPECIFIED":              0,
		"SHIPPING_CHANNEL_UNAVAILABLE":      1,
		"SHIPPING_NOT_FOUND":                2,
		"SHIPPING_INVALID_ARGUMENT":         3,
		"SHIPPING_BOX_TYPE_MISMATCH":        4,
		"SHIPPING_LOCKER_FULL":              5,
		"SHIPPING_BOX_TYPE_FULL":            6,
		"SHIPPING_SLOT_FULL":                7,
		"SHIPPING_RESOURCE_OCCUPIED":        8,
		"SHIPPING_PICKUP_DATE_OUT_OF_RANGE": 9,
		"SHIPPING_PARAMS_MISMATCH":          10,
		"SHIPPING_RATE_LIMIT_EXCEEDED":      11,
		"SHIPPING_BUSINESS_ERROR":           12,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_shipping_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_shipping_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_shipping_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_shipping_v1_error_reason_proto protoreflect.FileDescriptor

const file_shipping_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1eshipping/v1/error_reason.proto\x12\vshipping.v1*\x92\x03\n" +
	"\vErrorReason\x12\x18\n" +
	"\x14SHIPPING_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cSHIPPING_CHANNEL_UNAVAILABLE\x10\x01\x12\x16\n" +
	"\x12SHIPPING_NOT_FOUND\x10\x02\x12\x1d\n" +
	"\x19SHIPPING_INVALID_ARGUMENT\x10\x03\x12\x1e\n" +
	"\x1aSHIPPING_BOX_TYPE_MISMATCH\x10\x04\x12\x18\n" +
	"\x14SHIPPING_LOCKER_FULL\x10\x05\x12\x1a\n" +
	"\x16SHIPPING_BOX_TYPE_FULL\x10\x06\x12\x16\n" +
	"\x12SHIPPING_SLOT_FULL\x10\a\x12\x1e\n" +
	"\x1aSHIPPING_RESOURCE_OCCUPIED\x10\b\x12%\n" +
	"!SHIPPING_PICKUP_DATE_OUT_OF_RANGE\x10\t\x12\x1c\n" +
	"\x18SHIPPING_PARAMS_MISMATCH\x10\n" +
	"\x12 \n" +
	"\x1cSHIPPING_RATE_LIMIT_EXCEEDED\x10\v\x12\x1b\n" +
	"\x17SHIPPING_BUSINESS_ERROR\x10\fBH\n" +
	"\vshipping.v1P\x01Z'shunfeng-miniprogram/api/shipping/v1;v1\xa2\x02\rAPIShippingV1b\x06proto3"

var (
	file_shipping_v1_error_reason_proto_rawDescOnce sync.Once
	file_shipping_v1_error_reason_proto_rawDescData []byte
)

func file_shipping_v1_error_reason_proto_rawDescGZIP() []byte {
	file_shipping_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_shipping_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shipping_v1_error_reason_proto_rawDesc), len(file_shipping_v1_error_reason_proto_rawDesc)))
	})
	return file_shipping_v1_error_reason_proto_rawDescData
}

var file_shipping_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shipping_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: shipping.v1.ErrorReason
}
var file_shipping_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shipping_v1_error_reason_proto_init() }
func file_shipping_v1_error_reason_proto_init() {
	if File_shipping_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shipping_v1_error_reason_proto_rawDesc), len(file_shipping_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shipping_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_shipping_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_shipping_v1_error_reason_proto_enumTypes,
	}.Build()
	File_shipping_v1_error_reason_proto = out.File
	file_shipping_v1_error_reason_proto_goTypes = nil
	file_shipping_v1_error_reason_proto_depIdxs = nil
}
