// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: shipping/v1/shipping.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShippingService_ListChannels_FullMethodName        = "/shipping.v1.ShippingService/ListChannels"
	ShippingService_ListLockers_FullMethodName         = "/shipping.v1.ShippingService/ListLockers"
	ShippingService_ListBoxTypes_FullMethodName        = "/shipping.v1.ShippingService/ListBoxTypes"
	ShippingService_ListServicePoints_FullMethodName   = "/shipping.v1.ShippingService/ListServicePoints"
	ShippingService_ListPickupDates_FullMethodName     = "/shipping.v1.ShippingService/ListPickupDates"
	ShippingService_ListPickupTimeSlots_FullMethodName = "/shipping.v1.ShippingService/ListPickupTimeSlots"
)

// ShippingServiceClient is the client API for ShippingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ShippingService manages shipping channel selection, locker browsing,
// service point queries, and pickup appointment scheduling.
type ShippingServiceClient interface {
	// ListChannels returns all available shipping channels in the current
	// region together with their availability status and extra fees.
	ListChannels(ctx context.Context, in *ListChannelsRequest, opts ...grpc.CallOption) (*ListChannelsResponse, error)
	// ListLockers returns nearby operational locker cabinets ordered by
	// distance ascending. Returns INVALID_ARGUMENT when lat/lng are missing.
	ListLockers(ctx context.Context, in *ListLockersRequest, opts ...grpc.CallOption) (*ListLockersResponse, error)
	// ListBoxTypes returns all box-type specifications, inventory counts,
	// and extra fees for a given locker cabinet.
	ListBoxTypes(ctx context.Context, in *ListBoxTypesRequest, opts ...grpc.CallOption) (*ListBoxTypesResponse, error)
	// ListServicePoints returns nearby SF stations or partner stores
	// filtered by point_type, ordered by distance ascending.
	ListServicePoints(ctx context.Context, in *ListServicePointsRequest, opts ...grpc.CallOption) (*ListServicePointsResponse, error)
	// ListPickupDates returns the available pickup dates (today, tomorrow,
	// day-after-tomorrow) for the door-pickup channel. Expired time slots
	// for today are already excluded.
	ListPickupDates(ctx context.Context, in *ListPickupDatesRequest, opts ...grpc.CallOption) (*ListPickupDatesResponse, error)
	// ListPickupTimeSlots returns all time slots for a given date together
	// with their remaining capacity. Slots with zero capacity are marked
	// unavailable.
	ListPickupTimeSlots(ctx context.Context, in *ListPickupTimeSlotsRequest, opts ...grpc.CallOption) (*ListPickupTimeSlotsResponse, error)
}

type shippingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShippingServiceClient(cc grpc.ClientConnInterface) ShippingServiceClient {
	return &shippingServiceClient{cc}
}

func (c *shippingServiceClient) ListChannels(ctx context.Context, in *ListChannelsRequest, opts ...grpc.CallOption) (*ListChannelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChannelsResponse)
	err := c.cc.Invoke(ctx, ShippingService_ListChannels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingServiceClient) ListLockers(ctx context.Context, in *ListLockersRequest, opts ...grpc.CallOption) (*ListLockersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLockersResponse)
	err := c.cc.Invoke(ctx, ShippingService_ListLockers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingServiceClient) ListBoxTypes(ctx context.Context, in *ListBoxTypesRequest, opts ...grpc.CallOption) (*ListBoxTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBoxTypesResponse)
	err := c.cc.Invoke(ctx, ShippingService_ListBoxTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingServiceClient) ListServicePoints(ctx context.Context, in *ListServicePointsRequest, opts ...grpc.CallOption) (*ListServicePointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServicePointsResponse)
	err := c.cc.Invoke(ctx, ShippingService_ListServicePoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingServiceClient) ListPickupDates(ctx context.Context, in *ListPickupDatesRequest, opts ...grpc.CallOption) (*ListPickupDatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPickupDatesResponse)
	err := c.cc.Invoke(ctx, ShippingService_ListPickupDates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingServiceClient) ListPickupTimeSlots(ctx context.Context, in *ListPickupTimeSlotsRequest, opts ...grpc.CallOption) (*ListPickupTimeSlotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPickupTimeSlotsResponse)
	err := c.cc.Invoke(ctx, ShippingService_ListPickupTimeSlots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShippingServiceServer is the server API for ShippingService service.
// All implementations must embed UnimplementedShippingServiceServer
// for forward compatibility.
//
// ShippingService manages shipping channel selection, locker browsing,
// service point queries, and pickup appointment scheduling.
type ShippingServiceServer interface {
	// ListChannels returns all available shipping channels in the current
	// region together with their availability status and extra fees.
	ListChannels(context.Context, *ListChannelsRequest) (*ListChannelsResponse, error)
	// ListLockers returns nearby operational locker cabinets ordered by
	// distance ascending. Returns INVALID_ARGUMENT when lat/lng are missing.
	ListLockers(context.Context, *ListLockersRequest) (*ListLockersResponse, error)
	// ListBoxTypes returns all box-type specifications, inventory counts,
	// and extra fees for a given locker cabinet.
	ListBoxTypes(context.Context, *ListBoxTypesRequest) (*ListBoxTypesResponse, error)
	// ListServicePoints returns nearby SF stations or partner stores
	// filtered by point_type, ordered by distance ascending.
	ListServicePoints(context.Context, *ListServicePointsRequest) (*ListServicePointsResponse, error)
	// ListPickupDates returns the available pickup dates (today, tomorrow,
	// day-after-tomorrow) for the door-pickup channel. Expired time slots
	// for today are already excluded.
	ListPickupDates(context.Context, *ListPickupDatesRequest) (*ListPickupDatesResponse, error)
	// ListPickupTimeSlots returns all time slots for a given date together
	// with their remaining capacity. Slots with zero capacity are marked
	// unavailable.
	ListPickupTimeSlots(context.Context, *ListPickupTimeSlotsRequest) (*ListPickupTimeSlotsResponse, error)
	mustEmbedUnimplementedShippingServiceServer()
}

// UnimplementedShippingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShippingServiceServer struct{}

func (UnimplementedShippingServiceServer) ListChannels(context.Context, *ListChannelsRequest) (*ListChannelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListChannels not implemented")
}
func (UnimplementedShippingServiceServer) ListLockers(context.Context, *ListLockersRequest) (*ListLockersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLockers not implemented")
}
func (UnimplementedShippingServiceServer) ListBoxTypes(context.Context, *ListBoxTypesRequest) (*ListBoxTypesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBoxTypes not implemented")
}
func (UnimplementedShippingServiceServer) ListServicePoints(context.Context, *ListServicePointsRequest) (*ListServicePointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServicePoints not implemented")
}
func (UnimplementedShippingServiceServer) ListPickupDates(context.Context, *ListPickupDatesRequest) (*ListPickupDatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPickupDates not implemented")
}
func (UnimplementedShippingServiceServer) ListPickupTimeSlots(context.Context, *ListPickupTimeSlotsRequest) (*ListPickupTimeSlotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPickupTimeSlots not implemented")
}
func (UnimplementedShippingServiceServer) mustEmbedUnimplementedShippingServiceServer() {}
func (UnimplementedShippingServiceServer) testEmbeddedByValue()                         {}

// UnsafeShippingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShippingServiceServer will
// result in compilation errors.
type UnsafeShippingServiceServer interface {
	mustEmbedUnimplementedShippingServiceServer()
}

func RegisterShippingServiceServer(s grpc.ServiceRegistrar, srv ShippingServiceServer) {
	// If the following call panics, it indicates UnimplementedShippingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShippingService_ServiceDesc, srv)
}

func _ShippingService_ListChannels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChannelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).ListChannels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingService_ListChannels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).ListChannels(ctx, req.(*ListChannelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingService_ListLockers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLockersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).ListLockers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingService_ListLockers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).ListLockers(ctx, req.(*ListLockersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingService_ListBoxTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBoxTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).ListBoxTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingService_ListBoxTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).ListBoxTypes(ctx, req.(*ListBoxTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingService_ListServicePoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicePointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).ListServicePoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingService_ListServicePoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).ListServicePoints(ctx, req.(*ListServicePointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingService_ListPickupDates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPickupDatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).ListPickupDates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingService_ListPickupDates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).ListPickupDates(ctx, req.(*ListPickupDatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingService_ListPickupTimeSlots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPickupTimeSlotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).ListPickupTimeSlots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingService_ListPickupTimeSlots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).ListPickupTimeSlots(ctx, req.(*ListPickupTimeSlotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShippingService_ServiceDesc is the grpc.ServiceDesc for ShippingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShippingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shipping.v1.ShippingService",
	HandlerType: (*ShippingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListChannels",
			Handler:    _ShippingService_ListChannels_Handler,
		},
		{
			MethodName: "ListLockers",
			Handler:    _ShippingService_ListLockers_Handler,
		},
		{
			MethodName: "ListBoxTypes",
			Handler:    _ShippingService_ListBoxTypes_Handler,
		},
		{
			MethodName: "ListServicePoints",
			Handler:    _ShippingService_ListServicePoints_Handler,
		},
		{
			MethodName: "ListPickupDates",
			Handler:    _ShippingService_ListPickupDates_Handler,
		},
		{
			MethodName: "ListPickupTimeSlots",
			Handler:    _ShippingService_ListPickupTimeSlots_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shipping/v1/shipping.proto",
}
