// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"github.com/go-kratos/kratos/v3/registry"
	"log/slog"
	"shunfeng-miniprogram/internal/biz"
	"shunfeng-miniprogram/internal/conf"
	"shunfeng-miniprogram/internal/data"
	"shunfeng-miniprogram/internal/server"
	"shunfeng-miniprogram/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger *slog.Logger, registrar registry.Registrar) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	todoRepo := data.NewTodoRepo(dataData)
	todoUsecase := biz.NewTodoUsecase(todoRepo)
	todoService := service.NewTodoService(todoUsecase)
	userRepo := data.NewUserRepo(dataData)
	userUsecase := biz.NewUserUsecase(userRepo)
	userService := service.NewUserService(userUsecase)
	addressRepo := data.NewAddressRepo(dataData)
	addressUsecase := biz.NewAddressUsecase(addressRepo)
	addressService := service.NewAddressService(addressUsecase)
	orderRepo := data.NewOrderRepo(dataData)
	orderUsecase := biz.NewOrderUsecase(orderRepo)
	orderService := service.NewOrderService(orderUsecase)
	grpcServer := server.NewGRPCServer(confServer, todoService, userService, addressService, orderService)
	httpServer := server.NewHTTPServer(confServer, todoService, userService, addressService, orderService)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
