// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"github.com/go-kratos/kratos/v3/registry"
	"log/slog"
	"shunfeng-miniprogram/internal/biz"
	"shunfeng-miniprogram/internal/conf"
	"shunfeng-miniprogram/internal/data"
	"shunfeng-miniprogram/internal/server"
	"shunfeng-miniprogram/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger *slog.Logger, registrar registry.Registrar) (*kratos.App, func(), error) {
	todoRepo := data.NewTodoRepo()
	todoUsecase := biz.NewTodoUsecase(todoRepo)
	todoService := service.NewTodoService(todoUsecase)
	userRepo := data.NewUserRepo()
	userUsecase := biz.NewUserUsecase(userRepo)
	userService := service.NewUserService(userUsecase)
	addressRepo := data.NewAddressRepo()
	addressUsecase := biz.NewAddressUsecase(addressRepo)
	addressService := service.NewAddressService(addressUsecase)
	orderRepo := data.NewOrderRepo()
	orderUsecase := biz.NewOrderUsecase(orderRepo)
	orderService := service.NewOrderService(orderUsecase)
	channelRepo := data.NewChannelRepo()
	channelUsecase := biz.NewChannelUsecase(channelRepo)
	lockerRepo := data.NewLockerRepo()
	lockerBoxRepo := data.NewLockerBoxRepo()
	lockerUsecase := biz.NewLockerUsecase(lockerRepo, lockerBoxRepo)
	servicePointRepo := data.NewServicePointRepo()
	servicePointUsecase := biz.NewServicePointUsecase(servicePointRepo)
	pickupRepo := data.NewPickupRepo()
	pickupUsecase := biz.NewPickupUsecase(pickupRepo)
	shippingService := service.NewShippingService(channelUsecase, lockerUsecase, servicePointUsecase, pickupUsecase)
	grpcServer := server.NewGRPCServer(confServer, todoService, userService, addressService, orderService, shippingService)
	httpServer := server.NewHTTPServer(confServer, todoService, userService, addressService, orderService, shippingService)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
	}, nil
}
