// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: auth/v1/auth.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendVerificationCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	TargetType    string                 `protobuf:"bytes,2,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	Scene         string                 `protobuf:"bytes,3,opt,name=scene,proto3" json:"scene,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendVerificationCodeRequest) Reset() {
	*x = SendVerificationCodeRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendVerificationCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendVerificationCodeRequest) ProtoMessage() {}

func (x *SendVerificationCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendVerificationCodeRequest.ProtoReflect.Descriptor instead.
func (*SendVerificationCodeRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *SendVerificationCodeRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *SendVerificationCodeRequest) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *SendVerificationCodeRequest) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

type VerificationCodeReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VerificationId string                 `protobuf:"bytes,1,opt,name=verification_id,json=verificationId,proto3" json:"verification_id,omitempty"`
	ExpiresIn      int32                  `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerificationCodeReply) Reset() {
	*x = VerificationCodeReply{}
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationCodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationCodeReply) ProtoMessage() {}

func (x *VerificationCodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationCodeReply.ProtoReflect.Descriptor instead.
func (*VerificationCodeReply) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *VerificationCodeReply) GetVerificationId() string {
	if x != nil {
		return x.VerificationId
	}
	return ""
}

func (x *VerificationCodeReply) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	VerifyCode    string                 `protobuf:"bytes,3,opt,name=verify_code,json=verifyCode,proto3" json:"verify_code,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	DeviceId      string                 `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type TokenReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	AccountStatus string                 `protobuf:"bytes,5,opt,name=account_status,json=accountStatus,proto3" json:"account_status,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,6,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenReply) Reset() {
	*x = TokenReply{}
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenReply) ProtoMessage() {}

func (x *TokenReply) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenReply.ProtoReflect.Descriptor instead.
func (*TokenReply) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *TokenReply) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TokenReply) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenReply) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TokenReply) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *TokenReply) GetAccountStatus() string {
	if x != nil {
		return x.AccountStatus
	}
	return ""
}

func (x *TokenReply) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type RefreshTokenReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenReply) Reset() {
	*x = RefreshTokenReply{}
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenReply) ProtoMessage() {}

func (x *RefreshTokenReply) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenReply.ProtoReflect.Descriptor instead.
func (*RefreshTokenReply) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshTokenReply) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenReply) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenReply) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	DeviceId      string                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	LogoutAll     bool                   `protobuf:"varint,5,opt,name=logout_all,json=logoutAll,proto3" json:"logout_all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *LogoutRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LogoutRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LogoutRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *LogoutRequest) GetLogoutAll() bool {
	if x != nil {
		return x.LogoutAll
	}
	return false
}

type ChangePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OldPassword   string                 `protobuf:"bytes,2,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword   string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *ChangePasswordRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ChangePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type SubmitRealNameAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RealName      string                 `protobuf:"bytes,2,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	IdCardNo      string                 `protobuf:"bytes,3,opt,name=id_card_no,json=idCardNo,proto3" json:"id_card_no,omitempty"`
	ImageUrls     []string               `protobuf:"bytes,4,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRealNameAuthRequest) Reset() {
	*x = SubmitRealNameAuthRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRealNameAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRealNameAuthRequest) ProtoMessage() {}

func (x *SubmitRealNameAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRealNameAuthRequest.ProtoReflect.Descriptor instead.
func (*SubmitRealNameAuthRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitRealNameAuthRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubmitRealNameAuthRequest) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *SubmitRealNameAuthRequest) GetIdCardNo() string {
	if x != nil {
		return x.IdCardNo
	}
	return ""
}

func (x *SubmitRealNameAuthRequest) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

type RealNameAuthReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthId        int64                  `protobuf:"varint,1,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealNameAuthReply) Reset() {
	*x = RealNameAuthReply{}
	mi := &file_auth_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealNameAuthReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealNameAuthReply) ProtoMessage() {}

func (x *RealNameAuthReply) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealNameAuthReply.ProtoReflect.Descriptor instead.
func (*RealNameAuthReply) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *RealNameAuthReply) GetAuthId() int64 {
	if x != nil {
		return x.AuthId
	}
	return 0
}

func (x *RealNameAuthReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetRealNameAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRealNameAuthRequest) Reset() {
	*x = GetRealNameAuthRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRealNameAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRealNameAuthRequest) ProtoMessage() {}

func (x *GetRealNameAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRealNameAuthRequest.ProtoReflect.Descriptor instead.
func (*GetRealNameAuthRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *GetRealNameAuthRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RealNameAuthInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthId        int64                  `protobuf:"varint,1,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RealNameMask  string                 `protobuf:"bytes,3,opt,name=real_name_mask,json=realNameMask,proto3" json:"real_name_mask,omitempty"`
	IdCardMask    string                 `protobuf:"bytes,4,opt,name=id_card_mask,json=idCardMask,proto3" json:"id_card_mask,omitempty"`
	ImageUrls     []string               `protobuf:"bytes,5,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	RejectReason  string                 `protobuf:"bytes,7,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealNameAuthInfo) Reset() {
	*x = RealNameAuthInfo{}
	mi := &file_auth_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealNameAuthInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealNameAuthInfo) ProtoMessage() {}

func (x *RealNameAuthInfo) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealNameAuthInfo.ProtoReflect.Descriptor instead.
func (*RealNameAuthInfo) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{12}
}

func (x *RealNameAuthInfo) GetAuthId() int64 {
	if x != nil {
		return x.AuthId
	}
	return 0
}

func (x *RealNameAuthInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RealNameAuthInfo) GetRealNameMask() string {
	if x != nil {
		return x.RealNameMask
	}
	return ""
}

func (x *RealNameAuthInfo) GetIdCardMask() string {
	if x != nil {
		return x.IdCardMask
	}
	return ""
}

func (x *RealNameAuthInfo) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *RealNameAuthInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RealNameAuthInfo) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

var File_auth_v1_auth_proto protoreflect.FileDescriptor

const file_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x12auth/v1/auth.proto\x12\aauth.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\"{\n" +
	"\x1bSendVerificationCodeRequest\x12\x1b\n" +
	"\x06target\x18\x01 \x01(\tB\x03\xe0A\x02R\x06target\x12$\n" +
	"\vtarget_type\x18\x02 \x01(\tB\x03\xe0A\x02R\n" +
	"targetType\x12\x19\n" +
	"\x05scene\x18\x03 \x01(\tB\x03\xe0A\x02R\x05scene\"_\n" +
	"\x15VerificationCodeReply\x12'\n" +
	"\x0fverification_id\x18\x01 \x01(\tR\x0everificationId\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\x05R\texpiresIn\"\xa6\x01\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12$\n" +
	"\vverify_code\x18\x03 \x01(\tB\x03\xe0A\x02R\n" +
	"verifyCode\x12\x1f\n" +
	"\bpassword\x18\x04 \x01(\tB\x03\xe0A\x02R\bpassword\x12 \n" +
	"\tdevice_id\x18\x05 \x01(\tB\x03\xe0A\x02R\bdeviceId\"p\n" +
	"\fLoginRequest\x12\x1d\n" +
	"\aaccount\x18\x01 \x01(\tB\x03\xe0A\x02R\aaccount\x12\x1f\n" +
	"\bpassword\x18\x02 \x01(\tB\x03\xe0A\x02R\bpassword\x12 \n" +
	"\tdevice_id\x18\x03 \x01(\tB\x03\xe0A\x02R\bdeviceId\"\xc7\x01\n" +
	"\n" +
	"TokenReply\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12%\n" +
	"\x0eaccount_status\x18\x05 \x01(\tR\raccountStatus\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x06 \x01(\x03R\texpiresIn\"a\n" +
	"\x13RefreshTokenRequest\x12(\n" +
	"\rrefresh_token\x18\x01 \x01(\tB\x03\xe0A\x02R\frefreshToken\x12 \n" +
	"\tdevice_id\x18\x02 \x01(\tB\x03\xe0A\x02R\bdeviceId\"z\n" +
	"\x11RefreshTokenReply\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\"\xbb\x01\n" +
	"\rLogoutRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x06userId\x12&\n" +
	"\faccess_token\x18\x02 \x01(\tB\x03\xe0A\x02R\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12 \n" +
	"\tdevice_id\x18\x04 \x01(\tB\x03\xe0A\x02R\bdeviceId\x12\x1d\n" +
	"\n" +
	"logout_all\x18\x05 \x01(\bR\tlogoutAll\"\x85\x01\n" +
	"\x15ChangePasswordRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x06userId\x12&\n" +
	"\fold_password\x18\x02 \x01(\tB\x03\xe0A\x02R\voldPassword\x12&\n" +
	"\fnew_password\x18\x03 \x01(\tB\x03\xe0A\x02R\vnewPassword\"\x9d\x01\n" +
	"\x19SubmitRealNameAuthRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x06userId\x12 \n" +
	"\treal_name\x18\x02 \x01(\tB\x03\xe0A\x02R\brealName\x12!\n" +
	"\n" +
	"id_card_no\x18\x03 \x01(\tB\x03\xe0A\x02R\bidCardNo\x12\x1d\n" +
	"\n" +
	"image_urls\x18\x04 \x03(\tR\timageUrls\"D\n" +
	"\x11RealNameAuthReply\x12\x17\n" +
	"\aauth_id\x18\x01 \x01(\x03R\x06authId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"6\n" +
	"\x16GetRealNameAuthRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x06userId\"\xe8\x01\n" +
	"\x10RealNameAuthInfo\x12\x17\n" +
	"\aauth_id\x18\x01 \x01(\x03R\x06authId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12$\n" +
	"\x0ereal_name_mask\x18\x03 \x01(\tR\frealNameMask\x12 \n" +
	"\fid_card_mask\x18\x04 \x01(\tR\n" +
	"idCardMask\x12\x1d\n" +
	"\n" +
	"image_urls\x18\x05 \x03(\tR\timageUrls\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12#\n" +
	"\rreject_reason\x18\a \x01(\tR\frejectReason2\xf8\x06\n" +
	"\vAuthService\x12\x88\x01\n" +
	"\x14SendVerificationCode\x12$.auth.v1.SendVerificationCodeRequest\x1a\x1e.auth.v1.VerificationCodeReply\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/v1/auth/verification-codes\x12[\n" +
	"\bRegister\x12\x18.auth.v1.RegisterRequest\x1a\x13.auth.v1.TokenReply\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/auth/register\x12R\n" +
	"\x05Login\x12\x15.auth.v1.LoginRequest\x1a\x13.auth.v1.TokenReply\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/auth/login\x12i\n" +
	"\fRefreshToken\x12\x1c.auth.v1.RefreshTokenRequest\x1a\x1a.auth.v1.RefreshTokenReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/auth/refresh\x12X\n" +
	"\x06Logout\x12\x16.auth.v1.LogoutRequest\x1a\x16.google.protobuf.Empty\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/auth/logout\x12m\n" +
	"\x0eChangePassword\x12\x1e.auth.v1.ChangePasswordRequest\x1a\x16.google.protobuf.Empty\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\x1a\x18/api/v1/account/password\x12\x80\x01\n" +
	"\x12SubmitRealNameAuth\x12\".auth.v1.SubmitRealNameAuthRequest\x1a\x1a.auth.v1.RealNameAuthReply\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/v1/users/me/real-name-auth\x12v\n" +
	"\x0fGetRealNameAuth\x12\x1f.auth.v1.GetRealNameAuthRequest\x1a\x19.auth.v1.RealNameAuthInfo\"'\x82\xd3\xe4\x93\x02!\x12\x1f/api/v1/users/me/real-name-authBL\n" +
	"\x18io.grpc.examples.auth.v1B\tAuthProtoP\x01Z#shunfeng-miniprogram/api/auth/v1;v1b\x06proto3"

var (
	file_auth_v1_auth_proto_rawDescOnce sync.Once
	file_auth_v1_auth_proto_rawDescData []byte
)

func file_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)))
	})
	return file_auth_v1_auth_proto_rawDescData
}

var file_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_auth_v1_auth_proto_goTypes = []any{
	(*SendVerificationCodeRequest)(nil), // 0: auth.v1.SendVerificationCodeRequest
	(*VerificationCodeReply)(nil),       // 1: auth.v1.VerificationCodeReply
	(*RegisterRequest)(nil),             // 2: auth.v1.RegisterRequest
	(*LoginRequest)(nil),                // 3: auth.v1.LoginRequest
	(*TokenReply)(nil),                  // 4: auth.v1.TokenReply
	(*RefreshTokenRequest)(nil),         // 5: auth.v1.RefreshTokenRequest
	(*RefreshTokenReply)(nil),           // 6: auth.v1.RefreshTokenReply
	(*LogoutRequest)(nil),               // 7: auth.v1.LogoutRequest
	(*ChangePasswordRequest)(nil),       // 8: auth.v1.ChangePasswordRequest
	(*SubmitRealNameAuthRequest)(nil),   // 9: auth.v1.SubmitRealNameAuthRequest
	(*RealNameAuthReply)(nil),           // 10: auth.v1.RealNameAuthReply
	(*GetRealNameAuthRequest)(nil),      // 11: auth.v1.GetRealNameAuthRequest
	(*RealNameAuthInfo)(nil),            // 12: auth.v1.RealNameAuthInfo
	(*emptypb.Empty)(nil),               // 13: google.protobuf.Empty
}
var file_auth_v1_auth_proto_depIdxs = []int32{
	0,  // 0: auth.v1.AuthService.SendVerificationCode:input_type -> auth.v1.SendVerificationCodeRequest
	2,  // 1: auth.v1.AuthService.Register:input_type -> auth.v1.RegisterRequest
	3,  // 2: auth.v1.AuthService.Login:input_type -> auth.v1.LoginRequest
	5,  // 3: auth.v1.AuthService.RefreshToken:input_type -> auth.v1.RefreshTokenRequest
	7,  // 4: auth.v1.AuthService.Logout:input_type -> auth.v1.LogoutRequest
	8,  // 5: auth.v1.AuthService.ChangePassword:input_type -> auth.v1.ChangePasswordRequest
	9,  // 6: auth.v1.AuthService.SubmitRealNameAuth:input_type -> auth.v1.SubmitRealNameAuthRequest
	11, // 7: auth.v1.AuthService.GetRealNameAuth:input_type -> auth.v1.GetRealNameAuthRequest
	1,  // 8: auth.v1.AuthService.SendVerificationCode:output_type -> auth.v1.VerificationCodeReply
	4,  // 9: auth.v1.AuthService.Register:output_type -> auth.v1.TokenReply
	4,  // 10: auth.v1.AuthService.Login:output_type -> auth.v1.TokenReply
	6,  // 11: auth.v1.AuthService.RefreshToken:output_type -> auth.v1.RefreshTokenReply
	13, // 12: auth.v1.AuthService.Logout:output_type -> google.protobuf.Empty
	13, // 13: auth.v1.AuthService.ChangePassword:output_type -> google.protobuf.Empty
	10, // 14: auth.v1.AuthService.SubmitRealNameAuth:output_type -> auth.v1.RealNameAuthReply
	12, // 15: auth.v1.AuthService.GetRealNameAuth:output_type -> auth.v1.RealNameAuthInfo
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_auth_v1_auth_proto_init() }
func file_auth_v1_auth_proto_init() {
	if File_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_auth_v1_auth_proto = out.File
	file_auth_v1_auth_proto_goTypes = nil
	file_auth_v1_auth_proto_depIdxs = nil
}
