syntax = "proto3";

package auth.v1;

option go_package = "shunfeng-miniprogram/api/auth/v1;v1";
option java_multiple_files = true;
option java_package = "io.grpc.examples.auth.v1";
option java_outer_classname = "AuthErrorReasonProto";

enum ErrorReason {
  ERROR_REASON_UNSPECIFIED = 0;
  AUTH_INVALID_ARGUMENT = 1;
  AUTH_UNAUTHENTICATED = 2;
  AUTH_TOKEN_EXPIRED = 3;
  AUTH_PERMISSION_DENIED = 4;
  AUTH_ACCOUNT_DISABLED = 5;
  AUTH_RESOURCE_NOT_FOUND = 6;
  AUTH_DUPLICATE_REQUEST = 7;
  AUTH_INVALID_STATUS = 8;
}
