syntax = "proto3";

package express.v1;

option go_package = "shunfeng-miniprogram/api/express/v1;v1";
option java_multiple_files = true;
option java_package = "express.v1";
option objc_class_prefix = "APIExpressV1";

enum ErrorReason {
  EXPRESS_UNSPECIFIED = 0;
  EXPRESS_SEARCH_FAILED = 1;
  EXPRESS_ORDER_NOT_FOUND = 2;
  EXPRESS_LABEL_INVALID = 3;
  EXPRESS_SHARE_INVALID = 4;
  EXPRESS_SHARE_EXPIRED = 5;
  EXPRESS_SHARE_FREQ_LIMIT = 6;
  EXPRESS_MSG_NOT_FOUND = 7;
  EXPRESS_ORDER_NO_PERM = 8;
}
