// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: express/v1/express.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- 搜索 ---
type SearchOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchOrdersRequest) Reset() {
	*x = SearchOrdersRequest{}
	mi := &file_express_v1_express_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchOrdersRequest) ProtoMessage() {}

func (x *SearchOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_express_v1_express_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchOrdersRequest.ProtoReflect.Descriptor instead.
func (*SearchOrdersRequest) Descriptor() ([]byte, []int) {
	return file_express_v1_express_proto_rawDescGZIP(), []int{0}
}

func (x *SearchOrdersRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchOrdersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchOrdersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	ExpressNo     string                 `protobuf:"bytes,3,opt,name=express_no,json=expressNo,proto3" json:"express_no,omitempty"`
	SenderName    string                 `protobuf:"bytes,4,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	ReceiverName  string                 `protobuf:"bytes,5,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	HasFollowed   bool                   `protobuf:"varint,7,opt,name=has_followed,json=hasFollowed,proto3" json:"has_followed,omitempty"`
	Label         string                 `protobuf:"bytes,8,opt,name=label,proto3" json:"label,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_express_v1_express_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_express_v1_express_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_express_v1_express_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderItem) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderItem) GetExpressNo() string {
	if x != nil {
		return x.ExpressNo
	}
	return ""
}

func (x *OrderItem) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *OrderItem) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *OrderItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderItem) GetHasFollowed() bool {
	if x != nil {
		return x.HasFollowed
	}
	return false
}

func (x *OrderItem) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *OrderItem) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type SearchOrdersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*OrderItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchOrdersReply) Reset() {
	*x = SearchOrdersReply{}
	mi := &file_express_v1_express_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchOrdersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchOrdersReply) ProtoMessage() {}

func (x *SearchOrdersReply) ProtoReflect() protoreflect.Message {
	mi := &file_express_v1_express_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchOrdersReply.ProtoReflect.Descriptor instead.
func (*SearchOrdersReply) Descriptor() ([]byte, []int) {
	return file_express_v1_express_proto_rawDescGZIP(), []int{2}
}

func (x *SearchOrdersReply) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SearchOrdersReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// --- 关注/取消关注 ---
type FollowOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowOrderRequest) Reset() {
	*x = FollowOrderRequest{}
	mi := &file_express_v1_express_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowOrderRequest) ProtoMessage() {}

func (x *FollowOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_express_v1_express_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowOrderRequest.ProtoReflect.Descriptor instead.
func (*FollowOrderRequest) Descriptor() ([]byte, []int) {
	return file_express_v1_express_proto_rawDescGZIP(), []int{3}
}

func (x *FollowOrderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FollowOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Followed      bool                   `protobuf:"varint,1,opt,name=followed,proto3" json:"followed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowOrderReply) Reset() {
	*x = FollowOrderReply{}
	mi := &file_express_v1_express_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowOrderReply) ProtoMessage() {}

func (x *FollowOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_express_v1_express_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowOrderReply.ProtoReflect.Descriptor instead.
func (*FollowOrderReply) Descriptor() ([]byte, []int) {
	return file_express_v1_express_proto_rawDescGZIP(), []int{4}
}

func (x *FollowOrderReply) GetFollowed() bool {
	if x != nil {
		return x.Followed
	}
	return false
}

type UnfollowOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowOrderRequest) Reset() {
	*x = UnfollowOrderRequest{}
	mi := &file_express_v1_express_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowOrderRequest) ProtoMessage() {}

func (x *UnfollowOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_express_v1_express_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowOrderRequest.ProtoReflect.Descriptor instead.
func (*UnfollowOrderRequest) Descriptor() ([]byte, []int) {
	return file_express_v1_express_proto_rawDescGZIP(), []int{5}
}

func (x *UnfollowOrderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UnfollowOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Followed      bool                   `protobuf:"varint,1,opt,name=followed,proto3" json:"followed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowOrderReply) Reset() {
	*x = UnfollowOrderReply{}
	mi := &file_express_v1_express_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowOrderReply) ProtoMessage() {}

func (x *UnfollowOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_express_v1_express_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowOrderReply.ProtoReflect.Descriptor instead.
func (*UnfollowOrderReply) Descriptor() ([]byte, []int) {
	return file_express_v1_express_proto_rawDescGZIP(), []int{6}
}

func (x *UnfollowOrderReply) GetFollowed() bool {
	if x != nil {
		return x.Followed
	}
	return false
}

// --- 标签 ---
type SetOrderLabelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOrderLabelRequest) Reset() {
	*x = SetOrderLabelRequest{}
	mi := &file_express_v1_express_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOrderLabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOrderLabelRequest) ProtoMessage() {}

func (x *SetOrderLabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_express_v1_express_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOrderLabelRequest.ProtoReflect.Descriptor instead.
func (*SetOrderLabelRequest) Descriptor() ([]byte, []int) {
	return file_express_v1_express_proto_rawDescGZIP(), []int{7}
}

func (x *SetOrderLabelRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetOrderLabelRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SetOrderLabelReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOrderLabelReply) Reset() {
	*x = SetOrderLabelReply{}
	mi := &file_express_v1_express_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOrderLabelReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOrderLabelReply) ProtoMessage() {}

func (x *SetOrderLabelReply) ProtoReflect() protoreflect.Message {
	mi := &file_express_v1_express_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOrderLabelReply.ProtoReflect.Descriptor instead.
func (*SetOrderLabelReply) Descriptor() ([]byte, []int) {
	return file_express_v1_express_proto_rawDescGZIP(), []int{8}
}

func (x *SetOrderLabelReply) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ClearOrderLabelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearOrderLabelRequest) Reset() {
	*x = ClearOrderLabelRequest{}
	mi := &file_express_v1_express_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearOrderLabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearOrderLabelRequest) ProtoMessage() {}

func (x *ClearOrderLabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_express_v1_express_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearOrderLabelRequest.ProtoReflect.Descriptor instead.
func (*ClearOrderLabelRequest) Descriptor() ([]byte, []int) {
	return file_express_v1_express_proto_rawDescGZIP(), []int{9}
}

func (x *ClearOrderLabelRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ClearOrderLabelReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearOrderLabelReply) Reset() {
	*x = ClearOrderLabelReply{}
	mi := &file_express_v1_express_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearOrderLabelReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearOrderLabelReply) ProtoMessage() {}

func (x *ClearOrderLabelReply) ProtoReflect() protoreflect.Message {
	mi := &file_express_v1_express_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearOrderLabelReply.ProtoReflect.Descriptor instead.
func (*ClearOrderLabelReply) Descriptor() ([]byte, []int) {
	return file_express_v1_express_proto_rawDescGZIP(), []int{10}
}

func (x *ClearOrderLabelReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetOrderLabelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderLabelRequest) Reset() {
	*x = GetOrderLabelRequest{}
	mi := &file_express_v1_express_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderLabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderLabelRequest) ProtoMessage() {}

func (x *GetOrderLabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_express_v1_express_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderLabelRequest.ProtoReflect.Descriptor instead.
func (*GetOrderLabelRequest) Descriptor() ([]byte, []int) {
	return file_express_v1_express_proto_rawDescGZIP(), []int{11}
}

func (x *GetOrderLabelRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetOrderLabelReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	HasLabel      bool                   `protobuf:"varint,2,opt,name=has_label,json=hasLabel,proto3" json:"has_label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderLabelReply) Reset() {
	*x = GetOrderLabelReply{}
	mi := &file_express_v1_express_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderLabelReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderLabelReply) ProtoMessage() {}

func (x *GetOrderLabelReply) ProtoReflect() protoreflect.Message {
	mi := &file_express_v1_express_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderLabelReply.ProtoReflect.Descriptor instead.
func (*GetOrderLabelReply) Descriptor() ([]byte, []int) {
	return file_express_v1_express_proto_rawDescGZIP(), []int{12}
}

func (x *GetOrderLabelReply) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetOrderLabelReply) GetHasLabel() bool {
	if x != nil {
		return x.HasLabel
	}
	return false
}

// --- 分享 ---
type CreateOrderShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ExpireHours   int32                  `protobuf:"varint,2,opt,name=expire_hours,json=expireHours,proto3" json:"expire_hours,omitempty"`
	ShowSender    bool                   `protobuf:"varint,3,opt,name=show_sender,json=showSender,proto3" json:"show_sender,omitempty"`
	ShowReceiver  bool                   `protobuf:"varint,4,opt,name=show_receiver,json=showReceiver,proto3" json:"show_receiver,omitempty"`
	ShowPhone     bool                   `protobuf:"varint,5,opt,name=show_phone,json=showPhone,proto3" json:"show_phone,omitempty"`
	ShowStatus    bool                   `protobuf:"varint,6,opt,name=show_status,json=showStatus,proto3" json:"show_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderShareRequest) Reset() {
	*x = CreateOrderShareRequest{}
	mi := &file_express_v1_express_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderShareRequest) ProtoMessage() {}

func (x *CreateOrderShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_express_v1_express_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderShareRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderShareRequest) Descriptor() ([]byte, []int) {
	return file_express_v1_express_proto_rawDescGZIP(), []int{13}
}

func (x *CreateOrderShareRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateOrderShareRequest) GetExpireHours() int32 {
	if x != nil {
		return x.ExpireHours
	}
	return 0
}

func (x *CreateOrderShareRequest) GetShowSender() bool {
	if x != nil {
		return x.ShowSender
	}
	return false
}

func (x *CreateOrderShareRequest) GetShowReceiver() bool {
	if x != nil {
		return x.ShowReceiver
	}
	return false
}

func (x *CreateOrderShareRequest) GetShowPhone() bool {
	if x != nil {
		return x.ShowPhone
	}
	return false
}

func (x *CreateOrderShareRequest) GetShowStatus() bool {
	if x != nil {
		return x.ShowStatus
	}
	return false
}

type CreateOrderShareReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShareCode     string                 `protobuf:"bytes,1,opt,name=share_code,json=shareCode,proto3" json:"share_code,omitempty"`
	ShareUrl      string                 `protobuf:"bytes,2,opt,name=share_url,json=shareUrl,proto3" json:"share_url,omitempty"`
	ExpireAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderShareReply) Reset() {
	*x = CreateOrderShareReply{}
	mi := &file_express_v1_express_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderShareReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderShareReply) ProtoMessage() {}

func (x *CreateOrderShareReply) ProtoReflect() protoreflect.Message {
	mi := &file_express_v1_express_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderShareReply.ProtoReflect.Descriptor instead.
func (*CreateOrderShareReply) Descriptor() ([]byte, []int) {
	return file_express_v1_express_proto_rawDescGZIP(), []int{14}
}

func (x *CreateOrderShareReply) GetShareCode() string {
	if x != nil {
		return x.ShareCode
	}
	return ""
}

func (x *CreateOrderShareReply) GetShareUrl() string {
	if x != nil {
		return x.ShareUrl
	}
	return ""
}

func (x *CreateOrderShareReply) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

type GetOrderShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderShareRequest) Reset() {
	*x = GetOrderShareRequest{}
	mi := &file_express_v1_express_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderShareRequest) ProtoMessage() {}

func (x *GetOrderShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_express_v1_express_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderShareRequest.ProtoReflect.Descriptor instead.
func (*GetOrderShareRequest) Descriptor() ([]byte, []int) {
	return file_express_v1_express_proto_rawDescGZIP(), []int{15}
}

func (x *GetOrderShareRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetOrderShareReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	SenderName    string                 `protobuf:"bytes,2,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	ReceiverName  string                 `protobuf:"bytes,3,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	OrderStatus   string                 `protobuf:"bytes,6,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderShareReply) Reset() {
	*x = GetOrderShareReply{}
	mi := &file_express_v1_express_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderShareReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderShareReply) ProtoMessage() {}

func (x *GetOrderShareReply) ProtoReflect() protoreflect.Message {
	mi := &file_express_v1_express_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderShareReply.ProtoReflect.Descriptor instead.
func (*GetOrderShareReply) Descriptor() ([]byte, []int) {
	return file_express_v1_express_proto_rawDescGZIP(), []int{16}
}

func (x *GetOrderShareReply) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *GetOrderShareReply) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *GetOrderShareReply) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *GetOrderShareReply) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetOrderShareReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetOrderShareReply) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

// --- 消息 ---
type ListUserMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageType   string                 `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	ReadStatus    string                 `protobuf:"bytes,2,opt,name=read_status,json=readStatus,proto3" json:"read_status,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserMessagesRequest) Reset() {
	*x = ListUserMessagesRequest{}
	mi := &file_express_v1_express_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserMessagesRequest) ProtoMessage() {}

func (x *ListUserMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_express_v1_express_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListUserMessagesRequest) Descriptor() ([]byte, []int) {
	return file_express_v1_express_proto_rawDescGZIP(), []int{17}
}

func (x *ListUserMessagesRequest) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *ListUserMessagesRequest) GetReadStatus() string {
	if x != nil {
		return x.ReadStatus
	}
	return ""
}

func (x *ListUserMessagesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUserMessagesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UserMessageItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MessageType   string                 `protobuf:"bytes,2,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	BusinessType  string                 `protobuf:"bytes,5,opt,name=business_type,json=businessType,proto3" json:"business_type,omitempty"`
	BusinessId    string                 `protobuf:"bytes,6,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	Priority      int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	IsRead        bool                   `protobuf:"varint,8,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	ReadAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=read_at,json=readAt,proto3" json:"read_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMessageItem) Reset() {
	*x = UserMessageItem{}
	mi := &file_express_v1_express_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMessageItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMessageItem) ProtoMessage() {}

func (x *UserMessageItem) ProtoReflect() protoreflect.Message {
	mi := &file_express_v1_express_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMessageItem.ProtoReflect.Descriptor instead.
func (*UserMessageItem) Descriptor() ([]byte, []int) {
	return file_express_v1_express_proto_rawDescGZIP(), []int{18}
}

func (x *UserMessageItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserMessageItem) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *UserMessageItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UserMessageItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UserMessageItem) GetBusinessType() string {
	if x != nil {
		return x.BusinessType
	}
	return ""
}

func (x *UserMessageItem) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *UserMessageItem) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *UserMessageItem) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *UserMessageItem) GetReadAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReadAt
	}
	return nil
}

func (x *UserMessageItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListUserMessagesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*UserMessageItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	UnreadCount   int32                  `protobuf:"varint,3,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserMessagesReply) Reset() {
	*x = ListUserMessagesReply{}
	mi := &file_express_v1_express_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserMessagesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserMessagesReply) ProtoMessage() {}

func (x *ListUserMessagesReply) ProtoReflect() protoreflect.Message {
	mi := &file_express_v1_express_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserMessagesReply.ProtoReflect.Descriptor instead.
func (*ListUserMessagesReply) Descriptor() ([]byte, []int) {
	return file_express_v1_express_proto_rawDescGZIP(), []int{19}
}

func (x *ListUserMessagesReply) GetItems() []*UserMessageItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListUserMessagesReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListUserMessagesReply) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

type MarkMessageReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkMessageReadRequest) Reset() {
	*x = MarkMessageReadRequest{}
	mi := &file_express_v1_express_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkMessageReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkMessageReadRequest) ProtoMessage() {}

func (x *MarkMessageReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_express_v1_express_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkMessageReadRequest.ProtoReflect.Descriptor instead.
func (*MarkMessageReadRequest) Descriptor() ([]byte, []int) {
	return file_express_v1_express_proto_rawDescGZIP(), []int{20}
}

func (x *MarkMessageReadRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MarkMessageReadReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UnreadCount   int32                  `protobuf:"varint,2,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkMessageReadReply) Reset() {
	*x = MarkMessageReadReply{}
	mi := &file_express_v1_express_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkMessageReadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkMessageReadReply) ProtoMessage() {}

func (x *MarkMessageReadReply) ProtoReflect() protoreflect.Message {
	mi := &file_express_v1_express_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkMessageReadReply.ProtoReflect.Descriptor instead.
func (*MarkMessageReadReply) Descriptor() ([]byte, []int) {
	return file_express_v1_express_proto_rawDescGZIP(), []int{21}
}

func (x *MarkMessageReadReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MarkMessageReadReply) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

type MarkAllMessagesReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllMessagesReadRequest) Reset() {
	*x = MarkAllMessagesReadRequest{}
	mi := &file_express_v1_express_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllMessagesReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllMessagesReadRequest) ProtoMessage() {}

func (x *MarkAllMessagesReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_express_v1_express_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllMessagesReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAllMessagesReadRequest) Descriptor() ([]byte, []int) {
	return file_express_v1_express_proto_rawDescGZIP(), []int{22}
}

type MarkAllMessagesReadReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdatedCount  int32                  `protobuf:"varint,1,opt,name=updated_count,json=updatedCount,proto3" json:"updated_count,omitempty"`
	UnreadCount   int32                  `protobuf:"varint,2,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllMessagesReadReply) Reset() {
	*x = MarkAllMessagesReadReply{}
	mi := &file_express_v1_express_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllMessagesReadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllMessagesReadReply) ProtoMessage() {}

func (x *MarkAllMessagesReadReply) ProtoReflect() protoreflect.Message {
	mi := &file_express_v1_express_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllMessagesReadReply.ProtoReflect.Descriptor instead.
func (*MarkAllMessagesReadReply) Descriptor() ([]byte, []int) {
	return file_express_v1_express_proto_rawDescGZIP(), []int{23}
}

func (x *MarkAllMessagesReadReply) GetUpdatedCount() int32 {
	if x != nil {
		return x.UpdatedCount
	}
	return 0
}

func (x *MarkAllMessagesReadReply) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

type DeleteUserMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserMessageRequest) Reset() {
	*x = DeleteUserMessageRequest{}
	mi := &file_express_v1_express_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserMessageRequest) ProtoMessage() {}

func (x *DeleteUserMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_express_v1_express_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserMessageRequest) Descriptor() ([]byte, []int) {
	return file_express_v1_express_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteUserMessageRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteUserMessageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UnreadCount   int32                  `protobuf:"varint,2,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserMessageReply) Reset() {
	*x = DeleteUserMessageReply{}
	mi := &file_express_v1_express_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserMessageReply) ProtoMessage() {}

func (x *DeleteUserMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_express_v1_express_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserMessageReply.ProtoReflect.Descriptor instead.
func (*DeleteUserMessageReply) Descriptor() ([]byte, []int) {
	return file_express_v1_express_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteUserMessageReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteUserMessageReply) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

// --- 内部 gRPC: order-service 回调创建消息 ---
type CreateBusinessMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BusinessType  string                 `protobuf:"bytes,2,opt,name=business_type,json=businessType,proto3" json:"business_type,omitempty"`
	BusinessId    string                 `protobuf:"bytes,3,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	MessageType   string                 `protobuf:"bytes,4,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBusinessMessageRequest) Reset() {
	*x = CreateBusinessMessageRequest{}
	mi := &file_express_v1_express_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBusinessMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBusinessMessageRequest) ProtoMessage() {}

func (x *CreateBusinessMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_express_v1_express_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBusinessMessageRequest.ProtoReflect.Descriptor instead.
func (*CreateBusinessMessageRequest) Descriptor() ([]byte, []int) {
	return file_express_v1_express_proto_rawDescGZIP(), []int{26}
}

func (x *CreateBusinessMessageRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateBusinessMessageRequest) GetBusinessType() string {
	if x != nil {
		return x.BusinessType
	}
	return ""
}

func (x *CreateBusinessMessageRequest) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *CreateBusinessMessageRequest) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *CreateBusinessMessageRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateBusinessMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateBusinessMessageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBusinessMessageReply) Reset() {
	*x = CreateBusinessMessageReply{}
	mi := &file_express_v1_express_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBusinessMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBusinessMessageReply) ProtoMessage() {}

func (x *CreateBusinessMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_express_v1_express_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBusinessMessageReply.ProtoReflect.Descriptor instead.
func (*CreateBusinessMessageReply) Descriptor() ([]byte, []int) {
	return file_express_v1_express_proto_rawDescGZIP(), []int{27}
}

func (x *CreateBusinessMessageReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_express_v1_express_proto protoreflect.FileDescriptor

const file_express_v1_express_proto_rawDesc = "" +
	"\n" +
	"\x18express/v1/express.proto\x12\n" +
	"express.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"e\n" +
	"\x13SearchOrdersRequest\x12\x1d\n" +
	"\akeyword\x18\x01 \x01(\tB\x03\xe0A\x02R\akeyword\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xa9\x02\n" +
	"\tOrderItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x1d\n" +
	"\n" +
	"express_no\x18\x03 \x01(\tR\texpressNo\x12\x1f\n" +
	"\vsender_name\x18\x04 \x01(\tR\n" +
	"senderName\x12#\n" +
	"\rreceiver_name\x18\x05 \x01(\tR\freceiverName\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12!\n" +
	"\fhas_followed\x18\a \x01(\bR\vhasFollowed\x12\x14\n" +
	"\x05label\x18\b \x01(\tR\x05label\x12;\n" +
	"\vcreate_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\"V\n" +
	"\x11SearchOrdersReply\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.express.v1.OrderItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\")\n" +
	"\x12FollowOrderRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\".\n" +
	"\x10FollowOrderReply\x12\x1a\n" +
	"\bfollowed\x18\x01 \x01(\bR\bfollowed\"+\n" +
	"\x14UnfollowOrderRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\"0\n" +
	"\x12UnfollowOrderReply\x12\x1a\n" +
	"\bfollowed\x18\x01 \x01(\bR\bfollowed\"J\n" +
	"\x14SetOrderLabelRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\x12\x1d\n" +
	"\acontent\x18\x02 \x01(\tB\x03\xe0A\x02R\acontent\".\n" +
	"\x12SetOrderLabelReply\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"-\n" +
	"\x16ClearOrderLabelRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\"0\n" +
	"\x14ClearOrderLabelReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"+\n" +
	"\x14GetOrderLabelRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\"K\n" +
	"\x12GetOrderLabelReply\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1b\n" +
	"\thas_label\x18\x02 \x01(\bR\bhasLabel\"\xdc\x01\n" +
	"\x17CreateOrderShareRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\x12&\n" +
	"\fexpire_hours\x18\x02 \x01(\x05B\x03\xe0A\x02R\vexpireHours\x12\x1f\n" +
	"\vshow_sender\x18\x03 \x01(\bR\n" +
	"showSender\x12#\n" +
	"\rshow_receiver\x18\x04 \x01(\bR\fshowReceiver\x12\x1d\n" +
	"\n" +
	"show_phone\x18\x05 \x01(\bR\tshowPhone\x12\x1f\n" +
	"\vshow_status\x18\x06 \x01(\bR\n" +
	"showStatus\"\x8c\x01\n" +
	"\x15CreateOrderShareReply\x12\x1d\n" +
	"\n" +
	"share_code\x18\x01 \x01(\tR\tshareCode\x12\x1b\n" +
	"\tshare_url\x18\x02 \x01(\tR\bshareUrl\x127\n" +
	"\texpire_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bexpireAt\"/\n" +
	"\x14GetOrderShareRequest\x12\x17\n" +
	"\x04code\x18\x01 \x01(\tB\x03\xe0A\x02R\x04code\"\xc6\x01\n" +
	"\x12GetOrderShareReply\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x1f\n" +
	"\vsender_name\x18\x02 \x01(\tR\n" +
	"senderName\x12#\n" +
	"\rreceiver_name\x18\x03 \x01(\tR\freceiverName\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12!\n" +
	"\forder_status\x18\x06 \x01(\tR\vorderStatus\"\x93\x01\n" +
	"\x17ListUserMessagesRequest\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x12\x1f\n" +
	"\vread_status\x18\x02 \x01(\tR\n" +
	"readStatus\x12\x17\n" +
	"\x04page\x18\x03 \x01(\x05B\x03\xe0A\x02R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xdf\x02\n" +
	"\x0fUserMessageItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fmessage_type\x18\x02 \x01(\tR\vmessageType\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12#\n" +
	"\rbusiness_type\x18\x05 \x01(\tR\fbusinessType\x12\x1f\n" +
	"\vbusiness_id\x18\x06 \x01(\tR\n" +
	"businessId\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\x12\x17\n" +
	"\ais_read\x18\b \x01(\bR\x06isRead\x123\n" +
	"\aread_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x06readAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x83\x01\n" +
	"\x15ListUserMessagesReply\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.express.v1.UserMessageItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12!\n" +
	"\funread_count\x18\x03 \x01(\x05R\vunreadCount\"-\n" +
	"\x16MarkMessageReadRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\"S\n" +
	"\x14MarkMessageReadReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\funread_count\x18\x02 \x01(\x05R\vunreadCount\"\x1c\n" +
	"\x1aMarkAllMessagesReadRequest\"b\n" +
	"\x18MarkAllMessagesReadReply\x12#\n" +
	"\rupdated_count\x18\x01 \x01(\x05R\fupdatedCount\x12!\n" +
	"\funread_count\x18\x02 \x01(\x05R\vunreadCount\"/\n" +
	"\x18DeleteUserMessageRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\"U\n" +
	"\x16DeleteUserMessageReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\funread_count\x18\x02 \x01(\x05R\vunreadCount\"\xd0\x01\n" +
	"\x1cCreateBusinessMessageRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12#\n" +
	"\rbusiness_type\x18\x02 \x01(\tR\fbusinessType\x12\x1f\n" +
	"\vbusiness_id\x18\x03 \x01(\tR\n" +
	"businessId\x12!\n" +
	"\fmessage_type\x18\x04 \x01(\tR\vmessageType\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\"6\n" +
	"\x1aCreateBusinessMessageReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xa1\r\n" +
	"\x0eExpressService\x12u\n" +
	"\fSearchOrders\x12\x1f.express.v1.SearchOrdersRequest\x1a\x1d.express.v1.SearchOrdersReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/express/orders/search\x12t\n" +
	"\vFollowOrder\x12\x1e.express.v1.FollowOrderRequest\x1a\x1c.express.v1.FollowOrderReply\"'\x82\xd3\xe4\x93\x02!\"\x1f/api/express/orders/{id}/follow\x12z\n" +
	"\rUnfollowOrder\x12 .express.v1.UnfollowOrderRequest\x1a\x1e.express.v1.UnfollowOrderReply\"'\x82\xd3\xe4\x93\x02!*\x1f/api/express/orders/{id}/follow\x12|\n" +
	"\rSetOrderLabel\x12 .express.v1.SetOrderLabelRequest\x1a\x1e.express.v1.SetOrderLabelReply\")\x82\xd3\xe4\x93\x02#:\x01*\x1a\x1e/api/express/orders/{id}/label\x12\x7f\n" +
	"\x0fClearOrderLabel\x12\".express.v1.ClearOrderLabelRequest\x1a .express.v1.ClearOrderLabelReply\"&\x82\xd3\xe4\x93\x02 *\x1e/api/express/orders/{id}/label\x12y\n" +
	"\rGetOrderLabel\x12 .express.v1.GetOrderLabelRequest\x1a\x1e.express.v1.GetOrderLabelReply\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/express/orders/{id}/label\x12\x86\x01\n" +
	"\x10CreateOrderShare\x12#.express.v1.CreateOrderShareRequest\x1a!.express.v1.CreateOrderShareReply\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/express/orders/{id}/shares\x12\x82\x01\n" +
	"\rGetOrderShare\x12 .express.v1.GetOrderShareRequest\x1a\x1e.express.v1.GetOrderShareReply\"/\x82\xd3\xe4\x93\x02)\x12'/api/express/public/order-shares/{code}\x12\x82\x01\n" +
	"\x10ListUserMessages\x12#.express.v1.ListUserMessagesRequest\x1a!.express.v1.ListUserMessagesReply\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/express/users/me/messages\x12\x89\x01\n" +
	"\x0fMarkMessageRead\x12\".express.v1.MarkMessageReadRequest\x1a .express.v1.MarkMessageReadReply\"0\x82\xd3\xe4\x93\x02*\x1a(/api/express/users/me/messages/{id}/read\x12\x94\x01\n" +
	"\x13MarkAllMessagesRead\x12&.express.v1.MarkAllMessagesReadRequest\x1a$.express.v1.MarkAllMessagesReadReply\"/\x82\xd3\xe4\x93\x02)\x1a'/api/express/users/me/messages/read-all\x12\x8a\x01\n" +
	"\x11DeleteUserMessage\x12$.express.v1.DeleteUserMessageRequest\x1a\".express.v1.DeleteUserMessageReply\"+\x82\xd3\xe4\x93\x02%*#/api/express/users/me/messages/{id}\x12i\n" +
	"\x15CreateBusinessMessage\x12(.express.v1.CreateBusinessMessageRequest\x1a&.express.v1.CreateBusinessMessageReplyBU\n" +
	"\x1bio.grpc.examples.express.v1B\fExpressProtoP\x01Z&shunfeng-miniprogram/api/express/v1;v1b\x06proto3"

var (
	file_express_v1_express_proto_rawDescOnce sync.Once
	file_express_v1_express_proto_rawDescData []byte
)

func file_express_v1_express_proto_rawDescGZIP() []byte {
	file_express_v1_express_proto_rawDescOnce.Do(func() {
		file_express_v1_express_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_express_v1_express_proto_rawDesc), len(file_express_v1_express_proto_rawDesc)))
	})
	return file_express_v1_express_proto_rawDescData
}

var file_express_v1_express_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_express_v1_express_proto_goTypes = []any{
	(*SearchOrdersRequest)(nil),          // 0: express.v1.SearchOrdersRequest
	(*OrderItem)(nil),                    // 1: express.v1.OrderItem
	(*SearchOrdersReply)(nil),            // 2: express.v1.SearchOrdersReply
	(*FollowOrderRequest)(nil),           // 3: express.v1.FollowOrderRequest
	(*FollowOrderReply)(nil),             // 4: express.v1.FollowOrderReply
	(*UnfollowOrderRequest)(nil),         // 5: express.v1.UnfollowOrderRequest
	(*UnfollowOrderReply)(nil),           // 6: express.v1.UnfollowOrderReply
	(*SetOrderLabelRequest)(nil),         // 7: express.v1.SetOrderLabelRequest
	(*SetOrderLabelReply)(nil),           // 8: express.v1.SetOrderLabelReply
	(*ClearOrderLabelRequest)(nil),       // 9: express.v1.ClearOrderLabelRequest
	(*ClearOrderLabelReply)(nil),         // 10: express.v1.ClearOrderLabelReply
	(*GetOrderLabelRequest)(nil),         // 11: express.v1.GetOrderLabelRequest
	(*GetOrderLabelReply)(nil),           // 12: express.v1.GetOrderLabelReply
	(*CreateOrderShareRequest)(nil),      // 13: express.v1.CreateOrderShareRequest
	(*CreateOrderShareReply)(nil),        // 14: express.v1.CreateOrderShareReply
	(*GetOrderShareRequest)(nil),         // 15: express.v1.GetOrderShareRequest
	(*GetOrderShareReply)(nil),           // 16: express.v1.GetOrderShareReply
	(*ListUserMessagesRequest)(nil),      // 17: express.v1.ListUserMessagesRequest
	(*UserMessageItem)(nil),              // 18: express.v1.UserMessageItem
	(*ListUserMessagesReply)(nil),        // 19: express.v1.ListUserMessagesReply
	(*MarkMessageReadRequest)(nil),       // 20: express.v1.MarkMessageReadRequest
	(*MarkMessageReadReply)(nil),         // 21: express.v1.MarkMessageReadReply
	(*MarkAllMessagesReadRequest)(nil),   // 22: express.v1.MarkAllMessagesReadRequest
	(*MarkAllMessagesReadReply)(nil),     // 23: express.v1.MarkAllMessagesReadReply
	(*DeleteUserMessageRequest)(nil),     // 24: express.v1.DeleteUserMessageRequest
	(*DeleteUserMessageReply)(nil),       // 25: express.v1.DeleteUserMessageReply
	(*CreateBusinessMessageRequest)(nil), // 26: express.v1.CreateBusinessMessageRequest
	(*CreateBusinessMessageReply)(nil),   // 27: express.v1.CreateBusinessMessageReply
	(*timestamppb.Timestamp)(nil),        // 28: google.protobuf.Timestamp
}
var file_express_v1_express_proto_depIdxs = []int32{
	28, // 0: express.v1.OrderItem.create_time:type_name -> google.protobuf.Timestamp
	1,  // 1: express.v1.SearchOrdersReply.items:type_name -> express.v1.OrderItem
	28, // 2: express.v1.CreateOrderShareReply.expire_at:type_name -> google.protobuf.Timestamp
	28, // 3: express.v1.UserMessageItem.read_at:type_name -> google.protobuf.Timestamp
	28, // 4: express.v1.UserMessageItem.created_at:type_name -> google.protobuf.Timestamp
	18, // 5: express.v1.ListUserMessagesReply.items:type_name -> express.v1.UserMessageItem
	0,  // 6: express.v1.ExpressService.SearchOrders:input_type -> express.v1.SearchOrdersRequest
	3,  // 7: express.v1.ExpressService.FollowOrder:input_type -> express.v1.FollowOrderRequest
	5,  // 8: express.v1.ExpressService.UnfollowOrder:input_type -> express.v1.UnfollowOrderRequest
	7,  // 9: express.v1.ExpressService.SetOrderLabel:input_type -> express.v1.SetOrderLabelRequest
	9,  // 10: express.v1.ExpressService.ClearOrderLabel:input_type -> express.v1.ClearOrderLabelRequest
	11, // 11: express.v1.ExpressService.GetOrderLabel:input_type -> express.v1.GetOrderLabelRequest
	13, // 12: express.v1.ExpressService.CreateOrderShare:input_type -> express.v1.CreateOrderShareRequest
	15, // 13: express.v1.ExpressService.GetOrderShare:input_type -> express.v1.GetOrderShareRequest
	17, // 14: express.v1.ExpressService.ListUserMessages:input_type -> express.v1.ListUserMessagesRequest
	20, // 15: express.v1.ExpressService.MarkMessageRead:input_type -> express.v1.MarkMessageReadRequest
	22, // 16: express.v1.ExpressService.MarkAllMessagesRead:input_type -> express.v1.MarkAllMessagesReadRequest
	24, // 17: express.v1.ExpressService.DeleteUserMessage:input_type -> express.v1.DeleteUserMessageRequest
	26, // 18: express.v1.ExpressService.CreateBusinessMessage:input_type -> express.v1.CreateBusinessMessageRequest
	2,  // 19: express.v1.ExpressService.SearchOrders:output_type -> express.v1.SearchOrdersReply
	4,  // 20: express.v1.ExpressService.FollowOrder:output_type -> express.v1.FollowOrderReply
	6,  // 21: express.v1.ExpressService.UnfollowOrder:output_type -> express.v1.UnfollowOrderReply
	8,  // 22: express.v1.ExpressService.SetOrderLabel:output_type -> express.v1.SetOrderLabelReply
	10, // 23: express.v1.ExpressService.ClearOrderLabel:output_type -> express.v1.ClearOrderLabelReply
	12, // 24: express.v1.ExpressService.GetOrderLabel:output_type -> express.v1.GetOrderLabelReply
	14, // 25: express.v1.ExpressService.CreateOrderShare:output_type -> express.v1.CreateOrderShareReply
	16, // 26: express.v1.ExpressService.GetOrderShare:output_type -> express.v1.GetOrderShareReply
	19, // 27: express.v1.ExpressService.ListUserMessages:output_type -> express.v1.ListUserMessagesReply
	21, // 28: express.v1.ExpressService.MarkMessageRead:output_type -> express.v1.MarkMessageReadReply
	23, // 29: express.v1.ExpressService.MarkAllMessagesRead:output_type -> express.v1.MarkAllMessagesReadReply
	25, // 30: express.v1.ExpressService.DeleteUserMessage:output_type -> express.v1.DeleteUserMessageReply
	27, // 31: express.v1.ExpressService.CreateBusinessMessage:output_type -> express.v1.CreateBusinessMessageReply
	19, // [19:32] is the sub-list for method output_type
	6,  // [6:19] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_express_v1_express_proto_init() }
func file_express_v1_express_proto_init() {
	if File_express_v1_express_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_express_v1_express_proto_rawDesc), len(file_express_v1_express_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_express_v1_express_proto_goTypes,
		DependencyIndexes: file_express_v1_express_proto_depIdxs,
		MessageInfos:      file_express_v1_express_proto_msgTypes,
	}.Build()
	File_express_v1_express_proto = out.File
	file_express_v1_express_proto_goTypes = nil
	file_express_v1_express_proto_depIdxs = nil
}
